### PR TITLE
Intersector.intersectSegmentRectangle()

### PR DESCRIPTION
**Pull request by riki137**
i couldn't believe this method was missing in the awesome Intersector.

### CODE REVIEW

**Comment by Darkyenus** [comment]
Please run the [formatter](https://github.com/libgdx/libgdx/blob/master/.github/CONTRIBUTING.md#eclipse-formatter).

**Comment by riki137** [comment]
@NathanSweet @Darkyenus done

**Comment by NathanSweet** [comment]
Do we want to handle the segment being completely inside the rectangle? To do that, as a final check we could check if one end of the segment is inside the rectangle (no need to check both ends).

**Comment by obigu** [comment]
There's also the special case of the segment being parallel to one of the rectangle edges and sharing at least one point in which case it would return false. I guess most times the Intersector class is used to check collsions/overlaps so in my opinion it should return yes. That would also make it consistent with intersectSegmentCircle (which has an open PR (https://github.com/libgdx/libgdx/pull/5098) that requires a review :P)

**Comment by riki137** [comment]
@NathanSweet i was thinking about that possibility day after the commit, but didn't get myself to fix it. that is done.

**Comment by riki137** [comment]
I also removed intersection vector argument since intersection point in this context makes no sense.

**Pull request merged**
