### PR TITLE
Update bullet to 2.87

### PR DESCRIPTION
**Pull request by nicolaichuk**
Continue bullet update PR https://github.com/libgdx/libgdx/pull/4636

fix all swig warnings
update jni header files
improved work with some bullet templates 
add BulletInverseDynamics
add Vehicle

this bullet version 2.87 ( https://github.com/bulletphysics/bullet3/releases/tag/2.87 )
with apply patch https://github.com/bulletphysics/bullet3/pull/1052 (Fix some bullet build warnings)

check for:
- [ ] build-android32
- [ ] build-ios32
- [ ] build-linux32
- [ ] build-linux64
- [ ] build-macosx32
- [ ] build-macosx64
- [X] build-windows32
- [X] build-windows32home
- [X] build-windows64

need build logs for unchecked platforms.

### CODE REVIEW

**Comment by nicolaichuk** [comment]
@Tom-Ski, please code review.

**Comment by xoppa** [comment]
It looks like you based your code on 2.87 or perhaps master instead of version 2.86.1 of bullet.

**Comment by nicolaichuk** [comment]
@xoppa:

> It looks like you based your code on 2.87 or perhaps master instead of version 2.86.1 of bullet.

it based on 2.86.1 tag https://github.com/bulletphysics/bullet3/tree/2.86.1 with this two PR
bulletphysics/bullet3#1036
bulletphysics/bullet3#1052

I did not notice that bullet 2.87 already release. I try update code to 2.87 now.

**Comment by nicolaichuk** [comment]
@xoppa: update to bullet version 2.87 ( https://github.com/bulletphysics/bullet3/releases/tag/2.87 )

**Comment by Tom-Ski** [comment]
Hi @nicolaichuk, same comments as the last PR. Pretty hard to review these PRs unless they are very clean.

In future could you please have separate commits for swig file updates, the actual swig gen, and any source code changes. That will help out a lot. Any other changes should be done in a separate PR.
Could you also please compile and run the tests, or state if you haven't done so.

I've updated to 2.87 using the majority of your swig updates, some had some breaking changes that were reverted, but for the most part they are as is. The patch hasn't been applied, we'd need a discussion on if its worth it or not, as currently we have near enough completely clean bullet source to work from, which is great.

Your PR is very much appreciated, thanks!

**Pull request closed without merging**
