### PR TITLE
Add warning about setLooping method in Sound interface

### PR DESCRIPTION
**Pull request by jaeheonshim**
As mentioned in issue #5822 , sounds on Android do not loop when the setLooping method is called after the play method because of a SoundPool bug. This commit adds a notice to the java documentation on the setLooping method of interface Sound.

### CODE REVIEW

**Comment by mgsx-dev** [comment]
maybe specify it's for Android only, since other backends work fine.

also, better use taglets when referencing other methods (eg. `{@link #play()}` )

**Comment by MobiDevelop** [comment]
Having trouble finding a bug report on Android tracker indicating there is a known bug in SoundPool. Got a link?

**Comment by jaeheonshim** [comment]
@mgsx-dev 
I've added a note which specifies the bug relates only to the Android backend.
I also added the @link taglets for the methods in my documentation. Forgot about those!

**Comment by jaeheonshim** [comment]
> 
> 
> Having trouble finding a bug report on Android tracker indicating there is a known bug in SoundPool. Got a link?

Unfortunately, I can't seem to find a bug report for the issue. I just know that the bug is there from the issue I mentioned above, and I added documentation to support it.

**Comment by obigu** [comment]
Being specific to Android I think this java doc should be added to AndroidSound implementation instead.

**Comment by mgsx-dev** [comment]
@obigu i think it's better to have documentation in core because this is where users read documentation. There are already a bunch of this kind of specification for other methods/interfaces in core (eg. Preferences, Files, Clipboard, Input, ...)

**Comment by MobiDevelop** [comment]
We could make it work as opposed to documenting a flaw.

**Comment by obigu** [comment]
@mgsx-dev you're right, I've realised the problem of documenting the implentation later on. It's kind of against best practices to make the interface aware of its implementations (even if it's only javadocs)  but it's actually the best option.

**Comment by jaeheonshim** [comment]
@obigu Just to be clear, you're suggesting to document the problem for now, right?

**Comment by MobiDevelop** [comment]
This commit seems to resolve the issue - https://github.com/MobiDevelop/libgdx/commit/805476b6b0be5060667d550707169f6b0cda17ef if someone wants to give it a try and confirm, I'll push the fix to the main repo.

**Comment by Monarchis** [comment]
> This commit seems to resolve the issue - MobiDevelop@805476b if someone wants to give it a try and confirm, I'll push the fix to the main repo.

Am I wrong or does this pr only changes the docs? @MobiDevelop

**Comment by MobiDevelop** [comment]
That's correct @Monarchis. This PR changes the docs, I was suggesting to address the issue instead.

**Comment by noblemaster** [comment]
@MobiDevelop: I haven't tested it but it looks harmless enough. :) It can't be worse than what we have now. Don't think updating only the docu makes sense.

How about you push it to the main repo (please also update the CHANGES file, so we know what we have done)!

**Comment by wheelergames** [comment]
Does anyone else have issue with music not looping on Android? I've seen it mentioned a lot of times across the internet, for Android but also for LibGDX. I have a workaround that I use, but do others have it too, or is it only me? I don't think that https://github.com/MobiDevelop/libgdx/commit/805476b would fix it, only the soundPool issue. Would it be worth opening another PR for that one?

**Pull request closed without merging**
