### PR TITLE
Add badges for readme

### PR DESCRIPTION
**Pull request by fabiitch**
Hey all.
I want to contribute to gdx, 
For learn github pull request i start with readme.

 i add badge on readme (licence/downloads/forums/website/discord/patreon)
and group on line by style (build, community, supports)
For look result : https://github.com/fabiitch/libgdx/tree/readme-badge

I just got a problem with discord , see https://img.shields.io/discord/348229412858101762?logo=discord   widget are disabled, so if someone can enabled widget it can be cool (i gonna ask on discord too). or i can remove this badge.

Thanks for reading.

### CODE REVIEW

**Comment by crykn** [comment]
I think that many badges make the README seem rather cramped. However, I agree that a badge for discord would be a good idea.

**Comment by fabiitch** [comment]
y i agree ^^, i let main contributors choose. 

You can close this PR , no problem
or i can modify too for let only some badges.

**Comment by MrStahlfelge** [comment]
I also think the badges are too much, but I would appreciate the Discord badge.

**Comment by MrStahlfelge** [comment]
General consensus here is that these are too much badges. #6142 was opened with Discord badge only.

**Pull request closed without merging**
