### PR TITLE
Support for launching libGDX from a native iOS app

### PR DESCRIPTION
**Pull request by Dzamir**
I implemented the support for launching libGDX from a native iOS application. 

**Example usage:**

The host application must include a framework like in the [MyJavaFramework example](https://github.com/robovm/robovm-samples/tree/master/MyJavaFramework) that embeds the libGDX application.

In the libGDX application I added a class in the iOS module:

```
public class TestApplication {
    private IOSApplication iosApplication;

    public TestApplication() {
    }

    public void createApplication() {
        IOSApplicationConfiguration config = new IOSApplicationConfiguration();
        iosApplication = new IOSApplication(new Main(), config);
        iosApplication.launch("yourFrameworkName");
    }

    public void destroyApplication() {
        Singletons.close();
        iosApplication.destroy();
        iosApplication = null;
        System.gc();
    }

}
```

Inside the iOS application I can now create the TestApplication object and launch it by using the JNI, like in the [MyJavaFramework example](https://github.com/robovm/robovm-samples/tree/master/MyJavaFramework) :

```
- (IBAction)startLibGDX:(id)sender
{
    JavaVMInitArgs vm_args;
    vm_args.version = JNI_VERSION_1_4;
    vm_args.nOptions = 0;
    vm_args.options = NULL;

    jint res;
    JNIEnv *env;
    res = JNI_CreateJavaVM(&vm, &env, &vm_args);
    if (res != JNI_OK)
    {
        [NSException raise:@"JNI_CreateJavaVM() failed" format:@"%d", res];
    }

    _javaVM = javaVM;

    JNIEnv *env;
    jint res = (*[_javaVM vm])->AttachCurrentThread([_javaVM vm], (void**) &env, NULL);
    if (res != JNI_OK) {
        [NSException raise:@"AttachCurrentThread() failed" format:@"%d", res];
    }

    // get the class and methods reference
    testApplicationServiceClass = (*env)->FindClass(env, "net/yourcompany/yourproject/TestApplication");
    if (!testApplicationServiceClass) {
        [NSException raise:@"Failed to find class net.yourcompany.yourproject.TestApplication" format:@""];
    }
    createApplicationMethod = (*env)->GetMethodID(env, testApplicationServiceClass, "createApplication", "()V");
    if (!createApplicationMethod) {
        [NSException raise:@"Failed to find method net.yourcompany.yourproject.TestApplication.createApplication()" format:@""];
    }
    destroyApplicationMethod = (*env)->GetMethodID(env, testApplicationServiceClass, "destroyApplication", "()V");
    if (!destroyApplicationMethod) {
        [NSException raise:@"Failed to find method net.yourcompany.yourproject.TestApplication.destroyApplication()" format:@""];
    }
    constructor = (*env)->GetMethodID(env, testApplicationServiceClass, "<init>", "()V");

    // create the TestApplication object
    object = (*env)->NewObject(env, testApplicationServiceClass, constructor);

    // launch the libGDX application
    (*env)->CallVoidMethod(env, object, createApplicationMethod);
    (*[_javaVM vm])->DetachCurrentThread([_javaVM vm]);

}

- (void)closeLibGDX:()
{
    JNIEnv *env;
    jint res = (*[_javaVM vm])->AttachCurrentThread([_javaVM vm], (void**) &env, NULL);
    if (res != JNI_OK) {
        [NSException raise:@"AttachCurrentThread() failed" format:@"%d", res];
    }
    (*env)->CallVoidMethod(env, object, destroyApplicationMethod);
    (*[_javaVM vm])->DetachCurrentThread([_javaVM vm]);
}
```

### CODE REVIEW

**Comment by badlogic** [comment]
This is not supported by the Robo indie license.

**Comment by Dzamir** [comment]
Isn't possible to leave this feature only for whom has a RoboVM business license and broadcast a warning for who has the indie license?

It's a very small use case but it's really important for this subset of users.

**Comment by intrigus** [comment]
@badlogic Out of interest, why isn't this supported by the Indie license?

**Comment by badlogic** [comment]
@Dzamir i see your point. Could you squash the commits?

@intrigus because RoboVM are evil overlords out there to kill indies! Seriously though, the framework feature has always been a commercial one. We got the debugger, which used to be commercial only.

**Comment by Tom-Ski** [comment]
Please don't push binaries to the repository.

**Comment by Dzamir** [comment]
I squashed the commits

**Comment by intrigus** [comment]
You either still squashing the commits or you didn't squash all, because I can still see more than one commit. 

@badlogic
I just asked. I've never said that you kill indies or anything else.
I asked because I couldn't find anywhere any information that frameworks are commercial only.

**Comment by Dzamir** [comment]
I tried again to to squash the commits but unfortunately I never used this feature and I'm not sure how it works.

**Comment by Dzamir** [comment]
I finally squashed the commits in the right way

**Comment by VoidZombie** [comment]
Please, add this to LibGDX, I need it in my project too. Would be very good and useful. Thanks.

**Comment by lxl631** [comment]
I need it in my project too. Would be very good and useful. Thanks.

**Comment by xeoshow** [comment]
+1， strongly need this

2016-04-13 17:07 GMT+08:00 lxl631 <notifications@github.com>:

**Comment by AHIOS** [comment]
I really need this on my app. Please accept this PR.

**Comment by Dzamir** [comment]
Now that libgdx is using RoboVM open source, I think that we can easily test this against it and merge this pull request.

**Comment by devmacmari** [comment]
@Dzamir what'll happen to this pull request? I heard that libgdx is going to use MultiOS engine as MS killed roboVM...

ps: +1 on this feature! definitely need it 👍

**Review by MrStahlfelge — CHANGES_REQUESTED** [review]
The changes itself look good for me. However, the design choice has room to improve in my opinion:

        // if not null, the application is launched as a framework
	String frameworkName;

The ios backend was improved to be more extendable in the meantime. You should define a new `IosFrameworkApplication` extending `IOSApplication` overriding and adding the needed parts instead of changing it directly. Same for `IOSFiles`

RoboVM license should be no problem any more.

**Comment by MrStahlfelge** [comment]
Although the addition is a good idea in general, it seems there is no interest anymore in it. I can't test myself because I don't know how gdx could get integrated into a native app, so we let the PR open for another month and see if someone chimes in. If not, we should close it.

**Comment by SimonIT** [comment]
@Dzamir

**Comment by Dzamir** [comment]
I personally don't need this Pull Request anymore and I'm unable to reproduce or help anymore, cause I don't work anymore with libDGX on iOS projects.

**Pull request closed without merging**
