### PR TITLE
LWJGL3 Added the possibility to create windows initially hidden

### PR DESCRIPTION
**Pull request by ClaasJG**
Hey folks,

in the moment it is possible to hide windows using Lwjgl3Window#setVisible. This pull requests adds the option to configure windows to be hidden on creation by default. This is handy if the Lwjgl3Application is supposed to only 'spawn' windows using #newWindow. Or (the case why I made the request) if you desire to do offscreen rendering.

While I am not sure if this would be a widely used feature it is a small change and therefor worth considering imho.

-ClaasJG

### CODE REVIEW

**Comment by intrigus** [comment]
Could you please apply the formatter to your changes?

**Comment by ClaasJG** [comment]
It seems like the formatter changed a lot of code I never touched. I dont know how much of an issue that is? (And I am sorry I forgot the formatter, it was not my intention to make Nate upset. :)

**Comment by js78** [comment]
@ClaasJG Why don't you use Framebuffer to do offscreen rendering ?

**Comment by Darkyenus** [comment]
@js78 If I understand correctly, this is not for offscreen rendering when you have window up but when you want to do some OpenGL rendering without _any_ windows visible (sort of headless). If it is as I understand it, it could be useful for tools which need OpenGL but don't want to display anything. (And I could use just that!)

**Comment by ClaasJG** [comment]
@Darkyenus exactly

**Comment by badlogic** [comment]
Awesome, thanks!

**Pull request merged**
