### PR TITLE
Input improvements for the LWJGL2 backend

### PR DESCRIPTION
**Pull request by NathanSweet**
- InputEventQueue: no longer implements InputProcessor (never meant to be used as one), added time to the event methods rather than using the current time (LWJGL2 uses that), synchronization for setProcessor.
- LWJGL2 input: use InputEventQueue, missing `@Override` (if we're going to use the silly thing in a file, should at least be consistent :p), removed obsolete methods (supportsMultitouch, etc).
- LWJGL3 input: pass time to InputEventQueue, source format, avoid synthetic accessors for AbstractInput fields (in GLFWKeyCallback).
- Made getGdxKeyCode public (made protected in #6351).

### CODE REVIEW

**Comment by NathanSweet** [comment]
Oh boy, the PR included lots of commits for some reason. The actual files changed are correct, just need to be sure we squash when merging.

**Comment by MrStahlfelge** [comment]
Yeah we discussed on the other PR if the method is needed public, so you do use it not from subclasses but from somewhere else? What for (this is just out of interest).

Also out of interest, why the changes in initializing the variables in AbstractInput?

**Comment by crykn** [comment]
Uhm, with the PR `Gdx.input.isKeyPressed(...)` no longer works with the LWJGL2 backend. This is because the `pressedKeys` array is no longer updated.

**Comment by NathanSweet** [comment]
> so you do use it not from subclasses but from somewhere else? What for (this is just out of interest).
@MrStahlfelge I have a fork for LWJGL2 input that replaces the event queue with one that processes only one touch up per frame (simplifies some things in my app).

> Also out of interest, why the changes in initializing the variables in AbstractInput?
@MrStahlfelge It's not a big difference, but the idea is less code is easier to read code. If I see values assigned I have to read what they are. If there are no values it's the tiniest bit easier to see they are the default.

> with the PR Gdx.input.isKeyPressed(...) no longer works with the LWJGL2 backend
@crykn Yikes, good catch! Fixed.

**Comment by tommyettinger** [comment]
Is there a plan for how long we'll maintain the LWJGL2 backend? The plan could be "forever," I guess, or at least until OpenGL stops being supported. It certainly isn't going to work on new Macs natively, due to the ARM libraries not existing and no one writing new LWJGL2 code, but could be emulated probably for as long as Apple decides to permit that.

This PR looks good, also. I don't really understand InputEventQueue or how to use it, but if it's mostly internal to libGDX, that makes more sense. I also have not figured out why Git sometimes remembers previous PRs and keeps their history in a later one, but since we always squash-merge now, it doesn't pollute the repo.

**Comment by NathanSweet** [comment]
I'm stuck with LWJGL2 until LWJGL3 can be used with AWT. Seems like that's in progress. We don't need to keep LWJGL2 for me though, I can fork it if it's removed from libgdx. Though if it isn't hurting anything, it may as well stay.

InputEventQueue stores input events that can occur on any thread and later fires them on the game thread.

**Comment by crykn** [comment]
> I'm stuck with LWJGL2 until LWJGL3 can be used with AWT. Seems like that's in progress. 

It's not only in progress; #6190 contains a working Lwjgl3AWTFrame based on [lwjgl3-awt](https://github.com/LWJGLX/lwjgl3-awt).

**Comment by NathanSweet** [comment]
Yeah that looks cool. I'll need to find time to dig into it deeper.

**Pull request merged**
