### PR TITLE
remove texture artifacts for FreeTypeFontGenerator

### PR DESCRIPTION
**Pull request by JFixby**
Fixing https://github.com/libgdx/libgdx/issues/3521
- ```PixmapPacker``` has a new parameter ```Color currentTransparentColor;``` used by ```Page``` constructor to fill transparent pixels.
- ```FreeTypeFontGenerator``` sets packer to use color of the font but with zero alpha for transparent pixels to avoid leaks.

### CODE REVIEW

**Comment by MobiDevelop** [comment]
Can you please try not to open and close 3 PRs per change request?

**Comment by JFixby** [comment]
I am sorry for disturbing. Still learning the craft.

**Comment by intrigus** [comment]
Then I suggest that you first learn git and after that send PRs.

Create a sample repo and try git there. 

It's nothing personal, but 6 PRs per change are a little bit annoying.

**Comment by badlogic** [comment]
Please add docs, please add an entry to CHANGES. Why do youmset alpha to 0 on the transparent color?

**Comment by JFixby** [comment]
Transparent color is intended to replace all the pixels with alpha=0; When new glyphs page created it is filled with the ```transparentColor``` before drawing glyphs on top.

**Comment by NathanSweet** [comment]
PR seems OK to me. Could leave alpha, please can be expected to set a valid transparent color.

I expect it you use PMA the problem would go away entirely.

**Comment by JFixby** [comment]
I'm sorry @NathanSweet but I didn't understand your comments.

Let me give some details about the PR. Current master code does the following:
1) FreeTypeFontGenerator creates PixmapPacker
2) PixmapPacker creates pages with default ARGB=#00000000
3) FreeTypeFontGenerator  draws glyphs with the specified font color.
4) When the specified font color is not equal to the default color from the step (1) the glyphs leak, because alpha mask border is getting blurred and reveals transparent pixels.

In the PR:
1) FreeTypeFontGenerator creates PixmapPacker and sets it's default color ARGB=#00RRGGBB where RRGGBB are taken from the font color - https://github.com/libgdx/libgdx/pull/3927/files#diff-0b6e873945e2b28ba82f95c11ecf9667R348
2) PixmapPacker creates pages with the default ARGB=#00RRGGBB - https://github.com/libgdx/libgdx/pull/3927/files#diff-7d471251b67a93e5a37864c211ffd868R353
3) FreeTypeFontGenerator  draws glyphs with the specified font color.
4) The font color is equal to the default color from the step (1) so the glyphs do not leak, because revealed transparent pixels has the same color as their non-transparent neighbors.

So
A) You can set any transparent color here: https://github.com/libgdx/libgdx/pull/3927/files#diff-7d471251b67a93e5a37864c211ffd868R598 alpha is not affected or anything.
B) Not sure if the  premultiplied alpha is relevant here.

**Pull request merged**
