### PR TITLE
64-bit flag updated

### PR DESCRIPTION
**Pull request by entangledloops**
armv8 (64-bit) android accounted for

### CODE REVIEW

**Comment by intrigus** [comment]
Looks like it won't always work, see http://stackoverflow.com/a/33752302.
It may be better to use http://developer.android.com/reference/android/os/Build.html#SUPPORTED_64_BIT_ABIS.

**Comment by entangledloops** [comment]
@intrigus That stackoverflow user's post looks incorrect (i.e. their device is 64-bit according to the manufacturer, not sure how they determined it's 32). I've responded on stackoverflow with the relevant links.

**Comment by intrigus** [comment]
i

**Comment by xoppa** [comment]
Please verify your code before sending a pull request. Looks like you used github web editor for this?

**Comment by xoppa** [comment]
Closing this since it doesn't compile. Please reopen when you fixed it.

**Pull request closed without merging**
