### PR TITLE
Generate updated MobiVM MetalANGLE backend

### PR DESCRIPTION
**Pull request by Berstanio**
Follow up of #7371

### CODE REVIEW

**Comment by obigu** [comment]
I'm confused, isn't the MetalAngle generated automatically?

**Comment by Berstanio** [comment]
> I'm confused, isn't the MetalAngle generated automatically?

Usually it does, but as discussed on discord, the GHA was broken this time for some reason:
https://github.com/libgdx/libgdx/actions/runs/8570938601/job/23508292620#step:8:17

**Comment by obigu** [comment]
> Usually it does, but as discussed on discord, the GHA was broken this time for some reason: https://github.com/libgdx/libgdx/actions/runs/8570938601/job/23508292620#step:8:17

I see, shouldn't we fix that and re-run the tasks instead?

**Review by obigu — APPROVED** [review]

**Review by auraxangelic — APPROVED** [review]

**Comment by auraxangelic** [comment]
Thanks for making this change.

**Pull request merged**
