### PR TITLE
Geometry utils add

### PR DESCRIPTION
**Pull request by fabiitch**
Hey again, after work on my issues [#6679](https://github.com/libgdx/libgdx/issues/6679)
I find the answer (polygon p2 muste be clockwise)

I add some methods similar to CCW but for clockWise  (check, ensure)

Thanks for reading

### CODE REVIEW

**Comment by noblemaster** [comment]
This looks fine in my opinion.

**Review by noblemaster — APPROVED** [review]

**Comment by mgsx-dev** [comment]
i would name it "CounterClockWise" instead of "CCW" for consistency with existing "ClockWise" method names.

**Comment by noblemaster** [comment]
The original method is called "CCW", so you mean the new method should be called "CW"? I think typing it "Clockwise" is fine as naming it "CW" is very similar to "CCW" and could lead to problems if you forget at 'C' (very similar).

**Comment by mgsx-dev** [comment]
what i meant is that existing method is named "isClockwise" and new method is named "isCCW". I think it's better to have consistency, that's why i propose to name the new method "isCounterClockwise" instead of "isCCW". 
But if it doesn't matter to you, i won't fight against that :D

**Comment by noblemaster** [comment]
My bad, I just looked at the existing `ensureCCW` method. I see now that there is a new `isCCW` but it matches `ensureCCW`. I guess `isCCW` can be changed to `CounterClockwise` but then it won't match `ensureCCW` anymore.

Also, I don't mind either way. I somewhat prefer it how it is in now, but maybe there is a better solution?

**Comment by mgsx-dev** [comment]
Ah ah ! yes indeed, it was already inconsistent... my bad too. I agree, let's keep the inconsistency consistent :D

**Review by mgsx-dev — APPROVED** [review]

**Pull request merged**
