### PR TITLE
Remove unnecessary check for boolean

### PR DESCRIPTION
**Pull request by htynkn**
`musics.get(i).wasPlaying` is a boolean value, no need to use `== true` to check it.

### CODE REVIEW

**Comment by warmwaffles** [comment]
Correct me if I am wrong, but doesn't the java compiler know to fold that down to what you posted?

**Comment by deathbeam** [comment]
More useless pull requests please.

**Comment by badlogic** [comment]
@deathbeam hi, i decide what's useless :)

**Comment by MobiDevelop** [comment]
You tell'em Mario.

**Comment by badlogic** [comment]
you are useless, he is useless, she is useless, i am useless, EVERYONE IS
USELESS :D

**Comment by warmwaffles** [comment]
useless

**Comment by deathbeam** [comment]
@badlogic Farm them all :smile:

**Pull request merged**
