### PR TITLE
Updated IOSDevice list with last year devices

### PR DESCRIPTION
**Pull request by obigu**
Updated `IOSDeviceList` with last year devices.

I think we could consider removing unsupported devices (max iOS version < 8). The list keeps growing and I don't think it makes sense to have devices not supported by libGDX.

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
To review this, I need to know from where these values can be obtained. What's the source? This information should be added in a comment to the file as well in my opinion.

**Comment by obigu** [comment]
I got the info from this library https://github.com/lmirosevic/GBDeviceInfo but in order to follow previous style with the namings (Wifi, Cellular) and confirm I used https://gist.github.com/adamawolf/3048717. It should be good but it's not official, shall we add it anyway?

**Comment by MrStahlfelge** [comment]
Better to have the information for the future than to not have it, so yes!

**Comment by obigu** [comment]
Ok, added!

**Review by MrStahlfelge — APPROVED** [review]
No problem spotted

**Pull request merged**
