### PR TITLE
Hiero - add .json file format for webgl / javascript use

### PR DESCRIPTION
**Pull request by toloudis**
I write the .fnt data out to json, mimicking the bmfont text format as closely as possible.
Added a -j command line option to indicate output should go to json, and a new menu item to direct output to json.

### CODE REVIEW

**Comment by MobiDevelop** [comment]
What is wrong with the text format?

**Comment by toloudis** [comment]
In the interest of small code size for mobile web apps, it is very convenient to have a .json file that can be downloaded and parsed with no extra code.

**Comment by darthdurden** [comment]
I'd also love for Hiero to output in the AngelCode xml format.  I have some tools that read that in already, and it'd be a lot easier to fix the output than to fix the input.  Is that already support somehow that I'm not aware of?

**Comment by darthdurden** [comment]
After digging a bit more, it looks like XML is supported in the code, but not actually exposed via the UI (or commandline).  Am I missing something?

**Comment by NathanSweet** [comment]
This PR has conflicts, it doesn't seem to use the libgdx formatter, and it adds a dependency to emit JSON when the libgdx JsonWriter could be used instead.

I'm not sure Hiero should output the data in JSON, since we'd be creating a new format that is unlikely to be supported by any tools. I'm not completely against it though.

If there is an AngelCode XML format it would make sense for Hiero to export to that. Probably it just needs a menu item, I don't remember the state of the XML export code.

**Comment by nhydock** [comment]
Seeing as Hiero is a valuable tool for more than just LibGDX applications, is there a reason why it is still packaged directly with LibGDX instead of in a separate repository that depends on LibGDX?

**Comment by nhydock** [comment]
> /me marks this as libgdx 2.0

Could we please have a roadmap or at least a milestone added to the project's issue tracker for planned libgdx 2.0 features/ideas?

**Comment by nhydock** [comment]
Regarding the JSON exporting implementation, should we really be adding the javax.json dependency to the tools project when LibGDX already has its own [json parser](https://github.com/libgdx/libgdx/wiki/Reading-%26-writing-JSON) built-in?  

Usually I'm all for using more standard libraries to leverage dependency on the JVM reference implementation as opposed to nothing but internal/third-party libraries.  However, javax.json, even though it is the reference implementation of JSR 353, is targeted more for Java EE as opposed to Java SE.   Additionally, it competes with org.json which is what Android primarily uses.  

Even though gdx-tools is a desktop only project, LibGDX as a whole is multiplatform.  I recommend sticking with what LibGDX already has and uses instead of introducing competing standards into the project, as that was the purpose of having the parsers in the first place.

**Comment by badlogic** [comment]
Closed out due to @NathanSweet 's comments. As for milestones/roadmaps, there's a libGDX 2.0 issue on the tracker where peeps can put together a wish list. Thing is, the core team can't commit to that.

**Comment by toloudis** [comment]
I agree with the comments.  At some point I will revisit, fix conflicts, and use the internal json writer library. If I do those things, I'll resubmit.  It seems the interest in having this as a feature is not so high, so it'll stay for my internal use for the time being.

**Pull request closed without merging**
