### PR TITLE
Update Sound Manager 2

### PR DESCRIPTION
**Pull request by intrigus**
Update Sound Manager to version V2.97a.20150601.
This should fix http://www.badlogicgames.com/forum/viewtopic.php?f=15&t=24079 .

### CODE REVIEW

**Comment by BenMcLean** [comment]
GWT builds successfully with this change, but fails to actually run in the browser on desktop. Causes some kind of exception, even in apps that don't have any sounds.

Seems to work in browsers on Android though, oddly enough.

**Comment by Tom-Ski** [comment]
Works just fine in browser.

**Comment by BenMcLean** [comment]
Oh, I should have mentioned, This bug only seems to occur about 50% of the time, but I've tested it on multiple browsers on multiple computers. They're all running Windows 10 though.

**Comment by Tom-Ski** [comment]
Are you running gdx tests from source? I've ran this on chrome and firefox no issue.

**Comment by BenMcLean** [comment]
I suggest you try refreshing the page a few times to see if that makes it occur.

Maybe it might have something to do with Windows 10 sound drivers somehow.

**Comment by BenMcLean** [comment]
Just tried it on Windows 7, same issue. See my page here: https://benmclean.github.io/Planet-Generator/html/build/dist/ (btw it may be updated by tomorrow)

**Comment by Tom-Ski** [comment]
Run the gdx-tests please.

**Comment by BenMcLean** [comment]
I will give that a try after work. :)

**Comment by BenMcLean** [comment]
I will be trying out the tests as you suggest, but just FYI here is the error from the javascript console:

```
Uncaught Error: soundManager: Fatal: JavaScript file build "V2.97a.20130512" does not match Flash SWF build "V2.97a.20150601" at https://benmclean.github.io/Planet-Generator/html/build/dist/html/soundmanager2_flash9_debug.swf. Ensure both are up-to-date.
    at soundmanager2-jsmin.js:94
(anonymous) @ soundmanager2-jsmin.js:94
soundmanager2-jsmin.js:32 soundManager: No Flash response within expected time. Likely causes: Flash blocked or JS-Flash security error.
_writeDebug @ soundmanager2-jsmin.js:32
(anonymous) @ soundmanager2-jsmin.js:102
soundmanager2-jsmin.js:32 soundManager.disable(): Shutting down
soundmanager2-jsmin.js:32 SoundManager 2 failed to load (Flash security/load error)
_writeDebug @ soundmanager2-jsmin.js:32
X @ soundmanager2-jsmin.js:105
disable @ soundmanager2-jsmin.js:30
Ga @ soundmanager2-jsmin.js:81
(anonymous) @ soundmanager2-jsmin.js:103
html-0.js:5919 Uncaught TypeError: Cannot set property 'k' of undefined
    at Cd (html-0.js:5919)
    at Dd (html-0.js:5575)
    at fd (html-0.js:2350)
    at qd.sd [as Ac] (html-0.js:7564)
    at ontimeout (html-0.js:6835)
    at M (soundmanager2-jsmin.js:88)
    at X (soundmanager2-jsmin.js:105)
    at fa.disable (soundmanager2-jsmin.js:30)
    at Ga (soundmanager2-jsmin.js:81)
    at soundmanager2-jsmin.js:103
```

**Comment by BenMcLean** [comment]
I'll try to get this done soon but not today.

**Comment by MrStahlfelge** [comment]
I also have this problem after updating from 1.9.4 to 1.9.6. I am using Windows 10. The error message is logged only on Firefox with Flash enabled. Firefox without Flash and Chrome are working.


Error: soundManager: Fatal: JavaScript file build "V2.97a.20130512" does not match Flash SWF build "V2.97a.20150601" at https://v6p9d9t4.ssl.hwcdn.net/html/495497/html/soundmanager2_flash9_debug.swf. Ensure both are up-to-date.  soundmanager2-jsmin.js:94:452
soundManager: No Flash response within expected time. Likely causes: Flash blocked or JS-Flash security error.  soundmanager2-jsmin.js:32:357
soundManager.disable(): Shutting down  soundmanager2-jsmin.js:32:357
SoundManager 2 failed to load (Flash security/load error)  soundmanager2-jsmin.js:32:357

**Comment by MrStahlfelge** [comment]
@Tom-Ski problem exists in Firefox on Windows with Flash installed. Probably you are using Firefox without Flash. See #4771 for console log. I think this should be classified as a critical problem because it is preventing the whole application to start on a widely used configuration.

**Comment by intrigus** [comment]
@MrStahlfelge you are probably using a gdx project which has been created by an old version.
The soundmanager files are directly stored in your project and aren't updated when you update your libgdx project (by changing the libgdx version in your build.gradle).

You have to either regenerate your project or copy over the new files.

**Comment by MrStahlfelge** [comment]
@intrigus Thank you for the hint. I updated according to the [doc in the wiki](https://github.com/libgdx/libgdx/wiki/Updating-LibGDX) -- is this documentation incomplete? Where can I find the information which files to copy? (probably the two js files in /webapp, but I want to make sure)

**Comment by MrStahlfelge** [comment]
@intrigus can you please add the information which files to copy to the Update documentation? I would add it myself it I would know which files from where need to be replaced.

**Comment by intrigus** [comment]
Busy right now. Sorry.

**Pull request merged**
