### PR TITLE
private and public methods sorted by name to simplify syncing with Playn HtmlGl20

### PR DESCRIPTION
**Pull request by stefanhaustein**
Both variants have some independent improvements that may make sense to carry over.
Sorting simplifies the comparison.

### CODE REVIEW

**Comment by stefanhaustein** [comment]
ping?

**Comment by badlogic** [comment]
Pong :)

**Comment by intrigus** [comment]
Sorting the glXyz methods makes sense, but sorting the special methods (ensureCapacity(), allocateUniform(), ... ) doesn't imo.

**Comment by stefanhaustein** [comment]
I'll delete them in a followup

**Pull request merged**
