### PR TITLE
Fixes problems with lossy image data when using premultiplied alpha on GWT for textures

### PR DESCRIPTION
**Pull request by barkholt**
Fixes problem reported in #3782 and #3316.

Texture loading in the GWT backend makes use of the Pixmap class (as in the other backends). The GWT Pixmap is backed by a JavaScript Canvas element in order to make it mutable, as required by the Pixmap class. This is a problem since the round-trip to the Canvas in certain cases is lossy (as documented in the official specs), creating visual artifacts when using the alpha channel (see referenced tickets and supplied test case).

The PR proposes to delay the creation of the Canvas until absolutely necessary. In the typical texture loading case, there is no need for this extra representation, and we can just use the already created ImageElement when uploading the texture using OpenGL.

External users of the Pixmap class should be unaffected

### CODE REVIEW

**Comment by Tom-Ski** [comment]
Not a huge fan of the lazy loading of the canvas.   What about a private constructor path to an ImageElement only Pixmap? TextureData is emulated, so a custom constructor for Pixmap could be used that skips the canvas when uploading for a Texture.

**Comment by WillCalderwood** [comment]
@barkholt Any response to @Tom-Ski ? I'd love to see this fixed as I've just hit problems again.

@Tom-Ski Why do you not like the lazy loading of the canvas? You don't like the existance checks?

Thanks

**Comment by Tom-Ski** [comment]
The existance checks aren't the worse, I'd just prefer clean routes.  This is OK though, can be merged as a fix for now, just needs testing. I can do that this weekend, unless someone beats me to it.

**Comment by barkholt** [comment]
@Tom-Ski I'd love if you could do the testing and merging, or alternative throw the solution out definitively. I have several projects that suffer due to this issue. 
There might be a better way, and would love to investigate it at some point. In the mean time this solution is designed to minimize the changes in the back-end, and avoid creating side effects.

**Pull request merged**
