### PR TITLE
AndroidGL20 JNI Removal

### PR DESCRIPTION
**Pull request by PokeMMO**
See https://github.com/libgdx/libgdx/issues/5485

Removes dependency on [greylisted](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces) [NIOAccess api's](https://android.googlesource.com/platform/frameworks/base/+/pie-release/config/hiddenapi-light-greylist.txt#8982)

https://developer.android.com/reference/android/opengl/GLES20 was added in api level 8, libgdx's minimum is already 9.

Several functions rely on an unchecked cast from Buffer to (IntBuffer). It might be better to update the base GL20 interface to restrict buffer type.

Initial runthrough of gdx-tests-android with newly generated natives seems to work without issue.

As usual needs jnigen code regenerated manually:
```
mvn install

cd gdx
mvn clean compile exec:java -Dexec.mainClass="com.badlogic.gdx.utils.GdxBuild"
```

### CODE REVIEW

**Comment by noblemaster** [comment]
Given the deprecation warning by Google, it makes sense to have `AndroidGL20` call `GLES20` directly without JNI.

**Comment by PokeMMO** [comment]
The jnigen artifacts still need regenerated for this.

**Comment by noblemaster** [comment]
Not so sure how this has to be done? Can you take care of it?

**Comment by PokeMMO** [comment]
Sure, will open a new PR in a few here.

**Comment by noblemaster** [comment]
Thanks for the hard work! I have merged it. :)

**Pull request merged**
