### PR TITLE
Upgrade Android SDK lib we compile against to 30

### PR DESCRIPTION
**Pull request by obigu**
Upgraded Android SDK we build against to 30. This will allow support for new features such as Haptics.

Having the android.jar on the repo uploaded by a contributor is not ideal, hopefully https://github.com/libgdx/libgdx/pull/5976 will fix this.

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Comparing with 7693da46147cde4d67, at least dependencies.gradle should be changed. DependencyBank is useful to change, too.

**Comment by obigu** [comment]
> Comparing with [7693da4](https://github.com/libgdx/libgdx/commit/7693da46147cde4d67c8ee8c16cf40a7778bfe69), at least dependencies.gradle should be changed. DependencyBank is useful to change, too.

Wouldn't that set target SDK to 30 on new gdx setup projects? That may require some more testing. The motivation for this is to be able to compile API 29 code on libGDX project. IMO, upgrading the default target SDK to 30 on libGDX projects may be done separately.

**Review by MrStahlfelge — COMMENTED** [review]
- [X] Checked the jar file against android sdk 30 - same
- [X] Android Tests are still compiling and running
- [ ] I can't test if Maven builds successfully

I still think it would be better to raise compileSdk for the tests to 30 as well, but that might not be necessary.

**Comment by obigu** [comment]
Thanks for the tests. Ok, I agree we can update `dependencies.gradle` compile sdk to 30 for consistency sake between Maven/Ant and Gradle builds. Considering they're independent, Id rather set it on this other PR https://github.com/libgdx/libgdx/pull/6289 that already makes some changes on the names of the variables and other Gradle build related stuff, is that ok?

**Comment by MrStahlfelge** [comment]
Maven and me, we have some kind of hate relationship, that's why I fell in love with Gradle so fast.

**Pull request merged**
