### PR TITLE
iOS RoboVM: Fix crash if getCurrentEventTime is called before first t…

### PR DESCRIPTION
**Pull request by MrStahlfelge**
…ouch was made

This can happen if the game is controlled without touches.

### CODE REVIEW

**Comment by Tom-Ski** [comment]
Docs state that this is the time of the event currently reported by the InputProcessor. When are you calling this?

**Comment by MrStahlfelge** [comment]
It's called by a GestureDetector if it is notified by a faked touchDown or touchUp event. My extension to make Scene2d.ui useable by button and key fires these events on Actors to simulate user input, as touchDown/touchUp events are built-in.

https://github.com/MrStahlfelge/gdx-controllerutils/blob/4e62c1b59b1796d63c02140477fa57c7db2d619d/core-scene2d/src/de/golfgl/gdx/controllers/ControllerMenuStage.java#L256

Before you judge that this is not intended usage, please take into account that all other backends return 0 if this method is called before the first touch is done. The problem just exists on iOS. Thanks :)

**Comment by Tom-Ski** [comment]
This is not the case on android, which is what we follow mostly for the ios backends. All the other backends seem to do this more appropriately anyway. Instead of doing this null check, why not store the time as a field like the other backends are doing. Default value of 0 (maybe we should also change android to have this default too to be consistent)

**Comment by MrStahlfelge** [comment]
That's a good way, too. I will change it like that and make a new PR if you prefer it.

Yes, Android returns the startup time - that's weird. I will change it to 0, too.

**Comment by MrStahlfelge** [comment]
Done for MOE, too.

**Comment by Tom-Ski** [comment]
Awesome, thanks!

**Pull request merged**
