### PR TITLE
Fix #4934: Option in TexturePacker.Settings to specify the InterpolationMode when scaling

### LINKED ISSUE #4934: TexturePacker with settings.interpolationMode?
Hi,

I'm making a pixel art game and I need to upscale the images. I would like to do it while packing.
Is it possible that we have a settings.interpolationMode in [TexturePacker](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/ImageProcessor.java#L168) when settings.scale[n] >1? 

Thanks!

### PR DESCRIPTION
**Pull request by Velocity-**
As per request in #4934, new option addition in Settings under TexturePacker to specify the array of interpolation modes per scale factor. No breaking changes in the API, and fully backwards-compatible assuming Bicubic (which was the default) in case nothing is being specified.

Contributor agreement has been signed and emailed.

### CODE REVIEW

**Comment by Velocity-** [comment]
@Tom-Ski @NathanSweet I noticed 1.9.8 is the current now, but the changes are documented under 1.9.7. Do you guys want me to close this pull request and reopen one that puts the changes under 1.9.8?

**Comment by Tom-Ski** [comment]
Thanks for the PR. You can just make a new commit changing it to under 1.9.8 and push. The PR will be updated.
Or if you prefer, you can always remake it the PR entirely.

**Comment by Velocity-** [comment]
Gotcha, @Tom-Ski. It conflicted anyway, so I've just edited it to be under 1.9.8. Any chance it's eligible for merge? Small change, plus a 'test case'.

**Comment by Tom-Ski** [comment]
@Velocity- didn't notice your comment, sorry, I broke your PR again :]

**Comment by Velocity-** [comment]
Oh no! No worries @Tom-Ski, I've fixed them. Quick! Merge! 😉

**Comment by Velocity-** [comment]
@xoppa @MobiDevelop Any of you guys able to merge this PR? I don't want to come across as impatient but I'm trying to help out the developer in the linked issue to help fix it. :)

**Comment by NathanSweet** [comment]
It's a nice addition, thanks!

**Pull request merged**
