### PR TITLE
Bits add cpy() method

### PR DESCRIPTION
**Pull request by fabiitch**
I Was looking to [https://github.com/libgdx/ashley/issues/267](https://github.com/libgdx/ashley/issues/267), i dont find method to copy a Bits.

I have missing something ? 

If not  :
Im not sure about function nomenclature, i love method builder pattern (like vector2) but Bits dont use it.
Maybe a constructor is better ?
Thanks for reading

### CODE REVIEW

**Comment by MobiDevelop** [comment]
I personally like copy constructors, but don't feel strongly one way or the other. Apart from the conflict in the changes file, this seems fine to me.

**Comment by fabiitch** [comment]
Hey, i update pr to constructor method. 
Why not and why not not ^^

But im not sure about the utility of this PR.

Finally, i don't need to copy a Gdx BitSet for my project.
If after so many years and so many dev  using Gdx, this method wasnt add, its maybe useless.

I let gdx team choose.
No prob to close pr.

thanks for reading

**Comment by badlogic** [comment]
Can be merged once the CHANGES file conflict (and incorrect method name) is fixed.

**Comment by fabiitch** [comment]
changeslog fixed !

**Pull request merged**
