### PR TITLE
Opening access to the BitmapFontCache.idx field for custom render

### PR DESCRIPTION
**Pull request by JFixby**
Hello,

For custom rendering I need access to the IDX field of the BitmapFontCache class.
One simple method added:
```
public int[] getIDX () {
        return this.idx;
}
```
Have a nice day,
J

### CODE REVIEW

**Comment by NathanSweet** [comment]
`idx` isn't a great name for the public API. How about:

```
	public int getVertexCount (int page) {
		return idx[page];
	}
```

**Comment by JFixby** [comment]
Fine with me.

**Comment by JFixby** [comment]
oh wait, oh

**Comment by JFixby** [comment]
The problem is that I need the full array, not the VertexCount

**Comment by JFixby** [comment]
Ok now it is:
```
	final public int getVertexCount (final int j) {
		return this.idx[j];
	}
```

usage: ```final int spriteSize = gdx_font_cache.getVertexCount(j);```

**Comment by NathanSweet** [comment]
Unnecessary finals, no source format, param name makes sense as `page`, commits need squashing.

I'll just commit the method. :)

**Comment by JFixby** [comment]
Ok, thanx.

**Pull request closed without merging**
