### PR TITLE
Added gdx-facebook extension (v1.1.0)

### PR DESCRIPTION
**Pull request by TomGrill**
I have added my gdx-facebook extension to the 3rd party extension list.

Extension:
https://github.com/TomGrill/gdx-facebook

Example App:
https://github.com/TomGrill/gdx-facebook-app

### CODE REVIEW

**Comment by Tom-Ski** [comment]
Cool, Thanks! I'm away, but back in 2 days so I can test and give a review then, unless someone beats me to it.

**Comment by Tom-Ski** [comment]
Looks good, I'd suggest adding the required java versions to the readme of the project, and also that javafx is required for the desktop backend.

What's the story with the web backend? Is it just not implemented yet? Or are you not supporting it?

**Comment by TomGrill** [comment]
I have updated the readme. 

I did not need any web backend for my projects so far.

**Comment by Tom-Ski** [comment]
I don't see anything in the readme about supported versions, could you point me to where they are??

**Comment by TomGrill** [comment]
my bad, forgot to push the master branch

**Comment by Tom-Ski** [comment]
Cool, Thanks!

**Pull request merged**
