### PR TITLE
Fix for tooltip not working on android

### PR DESCRIPTION
**Pull request by Dakror**
Fix for issue #4924

### CODE REVIEW

**Comment by Tom-Ski** [comment]
You are using a USB mouse?

**Comment by Dakror** [comment]
Yes I am, why does this matter though? :o

**Comment by Tom-Ski** [comment]
For reproduction steps. Will have to order an adapter.

**Comment by Dakror** [comment]
It's reproducible on an actual android phone, if you've got one of those. Not sure about emulator though.

**Comment by Tom-Ski** [comment]
Sure, I just don't have a micro USB adapter to actually use a mouse, so I ordered one.

**Comment by Zomby2D** [comment]
I can't reproduce the initial issue, but this fix actually causes some weird behavior if you press the multi-line button in the UITest without a mouse plugged in. The multi-line tooltip text is floating and it's background is not sized/positioned to match the the text.

**Comment by Dakror** [comment]
The fix leads to the correct behaviour on both my desktop and my android phone... Strange

**Comment by MrStahlfelge** [comment]
Closing this. Fixing an issue on android only in scene2d core doesn't make sense to me at short glance, and here is no explanation what's happening and why this should fix it. Additionaly, the PR is super old and no feedback from the community on importance given.
Feel free to reopen for some enlightenment.

**Pull request closed without merging**
