### PR TITLE
Add resetScale method to BitmapFont

### PR DESCRIPTION
**Pull request by yuripourre**
I am using this method to reset the font to the original scale. I thought it might be useful.

When I call setScale(2) the scale is applied to the font and it gets bigger, then if I call setScale(1) the font font keeps the same size (2).

I just needed a method to get the original size back. Please let me know if there is a method to do this already, I couldn't find it.

### CODE REVIEW

**Comment by slebed** [comment]
Why not use setScale(.5) to reset the size when you double it with setScale(2)?

**Comment by Tom-Ski** [comment]
A setScale method should set the scale absolutely, which is apparently not what this method is doing currently?

**Comment by Lestat** [comment]
yeah and another method called .scale should do it like this one is doing it.

**Comment by obigu** [comment]
@yuripourre What libGDX version are you seeing this issue on? This should be fixed on 1.9.6.

**Comment by yuripourre** [comment]
Hi guys, thank you for the answers and sorry for the late.

@slebed: I am calling 1/2 = .5 that's what I want to do with this method (a general way to reset the scale).

@Tom-Ski: I was probably a bug from versions older than 1.9.6, pointed by @obigu 

@Lestat I tried this method but it is relative to the font's current scale (the same problem as I pointed)

@obigu You are right, I updated to 1.9.6 and now it works perfectly!

**Pull request closed without merging**
