### PR TITLE
Issue #3698: Fixed wrong Y property in case of Tile Object in TMX map

### PR DESCRIPTION
**Pull request by clebs**
This fixes issue 3698.

### CODE REVIEW

**Comment by MobiDevelop** [comment]
Can you please resolve the merge conflicts so we can merge this?

**Comment by clebs** [comment]
There you go :)

**Comment by MobiDevelop** [comment]
Thanks

**Comment by fobo66** [comment]
You forgot to close issue #3698, @MobiDevelop

**Pull request merged**
