### PR TITLE
Add GLES 3 support for GWT via WebGL2.

### PR DESCRIPTION
**Pull request by intrigus**
Currently still wip, but I'd appreciate some initial feedback :)

### CODE REVIEW

**Comment by EtK2000** [comment]
Looks good so far.
Good job!

**Comment by villelaitila** [comment]
Providing visualization of the change, this analysis can be done free of charge for all PR’s, just let me know and I’ll make it happen.

**Comment by villelaitila** [comment]
> Providing visualization of the change, this analysis can be done free of charge for all PR’s, just let me know and I’ll make it happen.

Just wanted to get some feedback, I appreciate that and we will try to improve stuff and get this more useful in your context.

**Comment by intrigus** [comment]
@villelaitila I don't need this.
Please remove your comments from this pull request.

**Comment by mgsx-dev** [comment]
@villelaitila please remove both your comments **and** bot comment from this PR.

**Comment by SimonIT** [comment]
Superseded by #7037

**Pull request closed without merging**
