### PR TITLE
Applying latest branding rule

### PR DESCRIPTION
**Pull request by payne911**
In the spirit of #6162.

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Is this really the only incidence of wrong capitalization in the repo?

**Review by MrStahlfelge — CHANGES_REQUESTED** [review]
I found a dozen other incidents of wrong capitalization. I think we should either change them all, or not.

**Comment by crykn** [comment]
I agree. @payne911 can you do all of them, except the mentions in the README (those are handled by #6142)?

**Comment by payne911** [comment]
> Is this really the only incidence of wrong capitalization in the repo?

Absolutely not: there are hundreds of instances.

I had started going through the whole code-base before giving up thinking random comments weren't all that important. But also because it's not just "replace all instances" because there are URLs, file-names and other logic-related Strings which misspelled ``libGDX``: potentially breaking the code for that didn't feel like it was worth it.

So in the end, I thought it'd be good to *at least* update the "legal" document's header.

**Comment by cypherdare** [comment]
IMO class and member names shouldn't change. It's standard for coding naming conventions to modify the capitalization of words, whether they are proper nouns or not. No one should expect these to match the branded name.

**Comment by MobiDevelop** [comment]
I personally don't think it is time we'll spent to go through the code and find places to change the capitalization. If you happen to be working in a file that should be updated, go for it.

**Comment by MrStahlfelge** [comment]
@MobiDevelop I think that's a good idea. So I suggest wie close this PR and change the capitalization in #6142 ?

**Comment by crykn** [comment]
Sounds reasonable not to change every instance of "libGDX" at once. But I still think we can merge this PR just to get those two documents (that won't be touched usually) up to date.

**Pull request merged**
