### PR TITLE
Pass in the correct file for LwjglNative extraction fixes #3578

### LINKED ISSUE #3578: Failing build - Unable to extract LWJGL natives
@NathanSweet Please see the comments on commit https://github.com/libgdx/libgdx/commit/e1aa0e56415f76df6de67aaafc4ce3bc2cc4f9c1. Several people have reported the same error, now on Windows, Mac, & Linux, from this change. Here's my stack trace on OS X Yosemite:

```
com.badlogic.gdx.utils.GdxRuntimeException: Unable to extract LWJGL natives.
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:67) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:76) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	at com.forerunnergames.peril.desktop.DesktopLauncher.main(DesktopLauncher.java:65) ~[main/:na]
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error extracting file: openal.dylib
To: /var/folders/9g/w7dzqgq94lj2q7kd_n7q7rth0000gn/T/libgdxAaron/f7649394
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFile(SharedLibraryLoader.java:265) ~[gdx-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFileTo(SharedLibraryLoader.java:171) ~[gdx-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:60) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	... 3 common frames omitted
Caused by: java.io.FileNotFoundException: /var/folders/9g/w7dzqgq94lj2q7kd_n7q7rth0000gn/T/libgdxAaron/f7649394 (Is a directory)
	at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_65]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[na:1.7.0_65]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171) ~[na:1.7.0_65]
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFile(SharedLibraryLoader.java:255) ~[gdx-1.7.2-SNAPSHOT.jar:na]
```

### PR DESCRIPTION
**Pull request by Tom-Ski**
Passes in the correct `File` to be extracted.  It's fairly ugly.

### CODE REVIEW

**Comment by saltares** [comment]
I am not too familiar with this module. However, could you not have two `?` operators in the same function call? Maybe have two variable declaration statements (using meaningful names) where you set both parameters in each case, then pass those parameters in the function calls.

That would make this a lot clearer.

**Comment by Tom-Ski** [comment]
Yup, just wanted to change as little as possible in the original commit. I've changed it now.

**Comment by firefly2442** [comment]
:+1: Confirm fix on Linux.

**Comment by davebaol** [comment]
Since snapshot is broken for everybody regardless of the operative system, can we merge this fix now?

**Comment by xoppa** [comment]
Confirmed fix on windows as well. Let's pull this in, although I'm not sure what the original issue was. Perhaps @NathanSweet can confirm.

**Comment by davebaol** [comment]
Great :+1:

**Pull request merged**
