### PR TITLE
Add list of apps that built with libgdx

### PR DESCRIPTION
**Pull request by vminc**
Add list of apps that built with libgdx

### CODE REVIEW

**Comment by MobiDevelop** [comment]
There's a gallery on the libgdx website and a section on the forum. I'm not sure we want to clutter the project readme with them as well.

**Comment by dvelovski** [comment]
This is just blatant self-promotion.

**Comment by vminc** [comment]
> This is just blatant self-promotion.

What is wrong? Anyone can add a reference not just us. This seems like a good way to help the community and build a stronger brand for the project. Popular open source projects like https://github.com/apache/incubator-superset have this list in their README page too.

If adding a reference to individual apps seem excessive, how about adding reference to company page?

**Comment by fabiitch** [comment]
I think of a list of best app build with gdx can be good for attractivity on readme.page
Not an full list, but just the best game/apps.

**Comment by vminc** [comment]
@fabiitch That's hard because you'll need a criteria for best game/apps that everyone agree on. Having an open list where developers can add to freely seem better.

**Comment by kn2718** [comment]
Agree with this idea. At least a link back to organization list would be helpful. The gallery page on the libgdx website is kind of useless as it's not well optimized for visibility and it's not well maintained.

**Comment by MrStahlfelge** [comment]
It's not to discuss any more if this is a good idea, @vminc spammed half the internet about his games yesterday. He opened a PR for such a list in at least 3 repos, [spammed various messages to reddit](https://www.reddit.com/user/vemotim2/), [edited ](https://github.com/libgdx/libgdx/wiki/Home/_compare/186d90b%5E...186d90b)the wiki. That's to much to count as good-intended behaviour.

**Comment by obigu** [comment]
The account @kn2718 belongs to the same spammer, he's doing the same shit on Reddit https://www.reddit.com/user/kn2718/.

**Comment by kn2718** [comment]
> The account @kn2718 belongs to the same spammer, he's doing the same shit on Reddit https://www.reddit.com/user/kn2718/.

Thank you for your investigation, Mr/Mrs Detective. Such a childish behavior. 
Yes, I am a colleague of @vminc. 
It is fine if this or other repos don't want this idea.

**Comment by vminc** [comment]
> The account @kn2718 belongs to the same spammer, he's doing the same shit on Reddit https://www.reddit.com/user/kn2718/.

Yes we should all protect our privacy when Internet Detective are all around :)

**Comment by vminc** [comment]
> It's not to discuss any more if this is a good idea, @vminc spammed half the internet about his games yesterday. He opened a PR for such a list in at least 3 repos, [spammed various messages to reddit](https://www.reddit.com/user/vemotim2/), [edited ](https://github.com/libgdx/libgdx/wiki/Home/_compare/186d90b%5E...186d90b)the wiki. That's to much to count as good-intended behaviour.

One should probably focus on the merit of this idea rather than what I did on the Internet.

**Comment by vminc** [comment]
> It's not to discuss any more if this is a good idea, @vminc spammed half the internet about his games yesterday. He opened a PR for such a list in at least 3 repos, [spammed various messages to reddit](https://www.reddit.com/user/vemotim2/), [edited ](https://github.com/libgdx/libgdx/wiki/Home/_compare/186d90b%5E...186d90b)the wiki. That's to much to count as good-intended behaviour.

Feel free to investigate more as this is what you're good at. What's my Twitter account? What's my Facebook account? Phone number? Street address?

**Comment by MobiDevelop** [comment]
There already exist places to list apps made with libgdx, let's use those or discuss in other community venues why they are not working for you.

**Pull request closed without merging**
