### PR TITLE
JniGen can have methods with Classes and Throwables

### PR DESCRIPTION
**Pull request by mdsimmo**
This pull request allows native code generated with JniGen to have parameters of type java.lang.Class or java.lang.Throwable. 

Previously, JniGen would crash when parameters included a Class or Throwable because the method declaration created by javah would not match the expectation from the JniGen code generator. (See this issue: #4157 )

The jni test code has not changed; I've merely reformatted it so it's valid C code and added a couple of arguments. 

Also, I wasn't really sure what I was doing with the Ant stuff in the test code, so someone might want to look closely at that part. I just modified it until it stopped giving errors :P

### CODE REVIEW

**Comment by NathanSweet** [comment]
Maybe we can get @badlogic to take a peek at his baby.

**Comment by NathanSweet** [comment]
Got conflicts now. If you fix that up I'll merge it.

**Comment by badlogic** [comment]
@mdsimmo will happily merge if you can resolve the conflicts.

**Comment by mdsimmo** [comment]
@badlogic @NathanSweet Conflicts are now resolved

**Comment by NathanSweet** [comment]
Cheers!

**Pull request merged**
