### PR TITLE
Update billboard particle batch v2

### PR DESCRIPTION
**Pull request by realitix**
I cleaned the code with the libgdx formatter and then I added the ability to customize blending and depth.

### CODE REVIEW

**Comment by MobiDevelop** [comment]
Thanks

**Comment by xpenatan** [comment]
Creating billboard particle with no parameters will crash with a null exception.

Maybe you just tested with blendingAttribute and  depthTestAttribute on constructor parameter.

Simple fix: BillboardParticleBatch.java -  change line 137-143 and add it before line 132 initRenderData();

**Comment by realitix** [comment]
Thanks to see that. I send a PR right now

**Comment by realitix** [comment]
the new pull request is here : https://github.com/libgdx/libgdx/pull/3184

**Pull request merged**
