### PR TITLE
Added adapter class for Net.HttpResponseListener

### PR DESCRIPTION
**Pull request by nrallakis**

### CODE REVIEW

**Comment by intrigus** [comment]
Could you present an use-case for your change?
I think that it's pretty uncommon to explicitly create a class that implements `HttpResponseListener` or extends your adapter.
Most people will probably just create an anonymous class.

**Comment by MobiDevelop** [comment]
Anonymous subclasses of interface adapters are a pretty common use-case when you only care to handle one interface method without cluttering you code with empty methods.

**Comment by nrallakis** [comment]
In my case, my app makes an http request to facebook, trying to retrieve a profile picture. However, it is not that important to succeed, because there is a default picture in place...

**Comment by badlogic** [comment]
I'd rather not include this as doing it in your own project is trivial enough.

**Pull request closed without merging**
