### PR TITLE
Shadow system 4 / 6

### PR DESCRIPTION
**Pull request by realitix**
Add RealisticShadowSystem.
Good luck for reviewing ! Here come struggle with shaders !

See #3347

### CODE REVIEW

**Comment by realitix** [comment]
Hi @xoppa. Don't forget this pull request ;-)

**Comment by xoppa** [comment]
Test this please

**Comment by Tom-Ski** [comment]
test this please

**Comment by xoppa** [comment]
Thanks! Sorry for the delay.

**Pull request merged**
