### PR TITLE
Udpated wrapper to 5.4.1

### PR DESCRIPTION
**Pull request by mr-gri3ves**
Updated gradle wrapper to 5.4.1
Now works with JDK-12.0.1
Updated source compatibility to 1.7

### CODE REVIEW

**Comment by PokeMMO** [comment]
Where did you get that gradle-wrapper.jar? It's checksum (50726ef76b6599d458dd37169a6b42d86d3790c83f6065a398e3e672448d18c6) does not match the 5.4.1 release checksum ([3dc39ad650d40f6c029bd8ff605c6d95865d657dbfdeacdb079db0ddfffedf9f](https://gradle.org/release-checksums/))

**Comment by mr-gri3ves** [comment]
I installed gradle on linux, sudo apt-get install gradle. Then followed the
instructions on how to update gradle wrapper
https://docs.gradle.org/current/userguide/gradle_wrapper.html.

gradle wrapper --gradle-version 5.4.1 --distribution-type all

**Comment by PokeMMO** [comment]
The gradle-wrapper.jar in the PR is ubuntu's custom built 4.4.1, not 5.4.1

**Comment by mr-gri3ves** [comment]
Oh ok, I'll handle that. Thx.

**Comment by mr-gri3ves** [comment]
Also wanted to mention that I've updated only gdx-setup's gradle wrapper.

**Pull request closed without merging**
