### PR TITLE
Added ETC2 conversion tool

### PR DESCRIPTION
**Pull request by devjn**
This makes possible to use KTXProcessor for generating ETC2 textures with a help of [etc2comp](https://github.com/google/etc2comp)

### CODE REVIEW

**Comment by intrigus** [comment]
Does this work with Mac OS X?

**Comment by devjn** [comment]
Nope, somebody needs to build a binary

**Comment by badlogic** [comment]
Where does the binary come from? What's the license?

**Comment by devjn** [comment]
https://github.com/google/etc2comp   Apache License 2.0

**Comment by devjn** [comment]
Updated with Mac OS binary 9f7624d, should now work probably

**Comment by Darkyenus** [comment]
macOS executables don't have extension .app, in fact, .app is something completely different, which makes this naming very confusing. macOS executables don't have any extension, I suggest renaming it to "etctool-mac" or something similar.

Same could be done with Linux.

**Comment by devjn** [comment]
Done 004e348.

**Comment by mgsx-dev** [comment]
not a good idea to include binaries in the repo, users can build them and stay up to date.

**Pull request closed without merging**
