### PR TITLE
Fixes Intersector.intersectRayTriangle failures #3147

### LINKED ISSUE #3147: Intersector.intersectRayTriangle failures (again)
I have found another issue with intersectRayTriangle. How to reproduce:

```java
Vector3 t1 = new Vector3(90.0f, -150.0f, 1077.0f);
Vector3 t2 = new Vector3(90.0f, -120.0f, 1109.0f);
Vector3 t3 = new Vector3(120.0f, -150.0f, 1076.0f);

Ray ray = new Ray(new Vector3(90.0f, -150.0f, 1077.1f), new Vector3(-0.0f, 0.99503726f, 0.099503726f));
System.out.println(Intersector.intersectRayTriangle(ray, t1, t2, t3, null); // error: print false
```

It's not obvious there is an intersection, but it is at: [90.0, -149.89658, 1077.1104]

Suggested fix (adapted from the [Möller-Trumbore algorithm](http://www.cs.virginia.edu/~gfx/Courses/2003/ImageSynthesis/papers/Acceleration/Fast%20MinimumStorage%20RayTriangle%20Intersection.pdf)):

```java
private static final float epsilon = 0.00001f;

public static boolean intersectRayTriangle (Ray ray, Vector3 t1, Vector3 t2, Vector3 t3, Vector3 intersection) {
	Vector3 edge1 = v0.set(t2).sub(t1);
	Vector3 edge2 = v1.set(t3).sub(t1);
	
	Vector3 pvec = v2.set(ray.direction).crs(edge2);
	float det = edge1.dot(pvec);
	if (det > -epsilon && det < epsilon) {
		p.set(t1, t2, t3);
		if (p.testPoint(ray.origin) == PlaneSide.OnPlane && isPointInTriangle(ray.origin, t1, t2, t3)) {
			if (intersection != null) intersection.set(ray.origin);
			return true;
		}
		return false;
	}
	
	det = 1.0f / det;

	Vector3 tvec = i.set(ray.origin).sub(t1);
	float u = tvec.dot(pvec) * det;
	if (u < 0.0f || u > 1.0f) return false;
	
	Vector3 qvec = tvec.crs(edge1);
	float v = ray.direction.dot(qvec) * det;
	if (v < 0.0f || u + v > 1.0f) return false;
	
	float t = edge2.dot(qvec) * det;
	if (t < 0) return false;
	
	if (intersection != null) {
		if (t < epsilon) {
			intersection.set(ray.origin);
		} else {
			ray.getEndPoint(intersection, t);
		}
	}
	
	return true;
}
```

The only difference with the original algorithm is that the method returns true when the ray origin is inside the triangle. It is clear this new code should be tested thoroughly to make sure it doesn't break existing applications.

Should I send a new pull request?

### PR DESCRIPTION
**Pull request by fwolff**

### CODE REVIEW

**Comment by xoppa** [comment]
Why the epsilon? We already have `MathUtils.FLOAT_ROUNDING_ERROR` as well as `MathUtils.isZero` and `MathUtils.isEqual`.

**Comment by fwolff** [comment]
Because I'm still new to libgdx and I didn't know about MathUtils...

Fell free to remove my epsilon and use your `MathUtils.isZero` instead.

**Comment by saltares** [comment]
Could you please update your PR to use the existing Libgdx API and then squash the commit? Thanks!

**Comment by fwolff** [comment]
Brand new PR (from a fresh fork): https://github.com/libgdx/libgdx/pull/3301

**Pull request closed without merging**
