### PR TITLE
Corrected array length test in Intersector.intersectRayTriangles

### PR DESCRIPTION
**Pull request by wytrem**
I just spotted a tiny mistake in the array length test.

(sorry for the invalid-email-address I forgot the configuration before commit...)

### CODE REVIEW

**Comment by mgsx-dev** [comment]
are you sure ? should be % 9 (3 vertex with the 3 XYZ components)

BTW the loop test `i < triangles.length - 6` could just be `i < triangles.length`

**Comment by mgsx-dev** [comment]
my advice would be to : 

* remove the unnecessary `- 6` in the for loop
* change the message in the exception according to the test (multiple of 9)
* finally squash all your commits in one with a proper comment like "Fixed array length test in Intersector.intersectRayTriangles" to keep a clean git history.

**Comment by wytrem** [comment]
Thanks for your advices, I'll apply this as soon as I can. Sorry for my noobness about PR, it's my first time doing it. 😊

**Comment by Tom-Ski** [comment]
This is an already correct length check, no? This change is to avoid the extra operation?

**Pull request closed without merging**
