### PR TITLE
Changed mp3 required to false

### PR DESCRIPTION
**Pull request by GrantOjanen**
My game was blocked from running on an older version of Chromium, because the browser didn't support mp3. Changing `required:!0` to `required:!1` for mp3 fixed my game and it runs now. The game uses ogg by the way.

When I say the game was blocked I mean the loading bar doesn't appear. I got this in the console.

SoundManager 2: No Flash detected. Trying HTML5-only mode.
SoundManager V2.97a.20150601 (AS3/Flash 9) + HTML5 audio
SoundManager 2: soundManager: Fatal error: Flash is needed to play some required formats, but is not available.
SoundManager 2 HTML5 support: mp3 = false (using flash), mp4 = false (using flash), ogg = true, opus = true, wav = true

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Take a look at #5659 and pull it in your project, that's probably more future-proof than fixing SoundManager.

**Comment by mgsx-dev** [comment]
@GrantOjanen i think you pushed some unwanted commits, maybe you made a PR on your master branch? :grimacing:

**Comment by GrantOjanen** [comment]
I'm a noob... I'm not sure what to do, but I need to take a little break.

**Comment by mgsx-dev** [comment]
@GrantOjanen don't worry, i suggest you to close your PR for now and join us on [Discord](https://libgdx.badlogicgames.com/community.html). We could help you out about your issue and how to propely make PRs :-)

**Pull request closed without merging**
