### PR TITLE
NativeBuild/Jnigen: add option to strip desktop binaries.

### PR DESCRIPTION
**Pull request by PokeMMO**
* Adding "-Drelease=true" will call "${compilerPrefix}strip --strip-unneeded ${libName}" after compilation.
* Default value for release is "false"
* Stripping has no influence on ram usage, symbol tables are not loaded into ram.
* OSX is not stripped as they appear pre-stripped (in 1.9.9 release) and OSX's gcc implementation lacks `--strip-unnecessary` as an option.

Would allow desktop builds which bundle all libs into a single jar to be ~2.5MB smaller.

```
16614038 1.9.9-unstripped.zip
14134108 1.9.9-stripped.zip
```

1.9.9 unstripped raw sizes:
```
   453284   gdx64.dll
   711442   gdx-box2d64.dll
   609229   gdx-box2d.dll
  8445098   gdx-bullet64.dll
  8089255   gdx-bullet.dll
  2665154   gdx-controllers-desktop64.dll
  2153195   gdx-controllers-desktop.dll
   390774   gdx.dll
   784149   gdx-freetype64.dll
   722171   gdx-freetype.dll
   246112   libgdx64.so
   400064   libgdx-box2d64.so
   393480   libgdx-box2d.so
  7062496   libgdx-bullet64.so
  7354840   libgdx-bullet.so
   178688   libgdx-controllers-desktop64.so
   163736   libgdx-controllers-desktop.so
   811616   libgdx-freetype64.so
   820888   libgdx-freetype.so
   260848   libgdx.so
```

1.9.9 stripped raw sizes
```
   281101   gdx64.dll
   347343   gdx-box2d64.dll
   329897   gdx-box2d.dll
  5154137   gdx-bullet64.dll
  5444343   gdx-bullet.dll
   995634   gdx-controllers-desktop64.dll
   970499   gdx-controllers-desktop.dll
   259021   gdx.dll
   608045   gdx-freetype64.dll
   571663   gdx-freetype.dll
   220416   libgdx64.so
   319752   libgdx-box2d64.so
   322120   libgdx-box2d.so
  5488608   libgdx-bullet64.so
  5896208   libgdx-bullet.so
   142920   libgdx-controllers-desktop64.so
   133248   libgdx-controllers-desktop.so
   728784   libgdx-freetype64.so
   743640   libgdx-freetype.so
   227324   libgdx.so
```

No generated files are included in this PR for readability sake. The following snippet may be used to generate all automatically.

```
cd gdx
mvn clean compile exec:java -Dexec.mainClass="com.badlogic.gdx.utils.GdxBuild"

cd ../extensions/gdx-controllers/gdx-controllers-desktop/
mvn clean compile exec:java -Dexec.mainClass="com.badlogic.gdx.controllers.desktop.DesktopControllersBuild"

cd ../../gdx-freetype/
mvn clean compile exec:java -Dexec.mainClass="com.badlogic.gdx.graphics.g2d.freetype.FreetypeBuild"

cd ../gdx-box2d/gdx-box2d
mvn clean compile exec:java -Dexec.mainClass="com.badlogic.gdx.physics.box2d.utils.Box2DBuild"

cd ../../gdx-bullet/
mvn clean compile exec:java -Dexec.mainClass="com.badlogic.gdx.physics.bullet.BulletBuild"
```

### CODE REVIEW

**Comment by NathanSweet** [comment]
Looks good, thanks! Let's default it to true though. Cheers!

**Comment by RUSshy** [comment]
To save even more disk space, there can be a flag to bundle only 32 or 64bits for native libraries, most linux distro don't provide 32bit builds anymore, and steam show us only 1.5% are using a 32bit OS on windows

**Comment by PokeMMO** [comment]
Sorry, it looks like I forgot to mention you have to run `mvn install` before running the generate snippet.

**Comment by NathanSweet** [comment]
@RUSshy People are welcome to choose what libs to include themselves, I don't think the build needs to do it.

@PokeMMO Gotcha, I ran it again. Making me do `mvn` stuff, so evil.

**Pull request merged**
