### PR TITLE
Add builder to lights.

### PR DESCRIPTION
**Pull request by realitix**
Allow to create lights more easily.

### CODE REVIEW

**Comment by xoppa** [comment]
Ow, that's not what I expected. What's the use-case? Why would you create another class just to pass some values? In that case you might as well use the copy constructor.

**Comment by xoppa** [comment]
To expand a bit; I thought that you wanted to add the builder methods to the lights them self. E.g. so you could do: `new SpotLight().setColor(Color.BLUE).setPosition(x, y, z).setDirection(Vector3.Z);` etc.

**Comment by warmwaffles** [comment]
:+1: @xoppa that would be nice

**Comment by realitix** [comment]
You are right ! I do it tomorrow

**Comment by realitix** [comment]
I was following strictly the builder pattern but in that case it's not necessary because none of the arguments are mandatory.

**Comment by xoppa** [comment]
Looks like the `setColor` method of PointLight and SpotLight isnt needed. Instead change the class to `BaseLight<T extends BaseLight<T>>`, `PointLight extends BaseLight<PointLight>`, etc. And make the `setColor` method return `T`

**Comment by realitix** [comment]
I followed your advice. You can take a look.

**Comment by xoppa** [comment]
Thanks!

**Pull request merged**
