### PR TITLE
I18NMessageTest needs to reset I18NBundle static state.

### PR DESCRIPTION
**Pull request by tommyettinger**
If you run I18NSimpleMessageTest and then I18NMessageTest without this PR, then the first test will have called I18NBundle.setSimpleFormatter(true), but the second test needs it to be set to false. That causes an Exception to be thrown:

```
[I18NMessageTest] Error
java.lang.IllegalArgumentException: Unexpected ',' while parsing argument index
	at com.badlogic.gdx.utils.TextFormatter.simpleFormat(TextFormatter.java:146)
	at com.badlogic.gdx.utils.TextFormatter.format(TextFormatter.java:64)
	at com.badlogic.gdx.utils.I18NBundle.format(I18NBundle.java:468)
	at com.badlogic.gdx.tests.I18NMessageTest.getParametricMessage(I18NMessageTest.java:92)
	at com.badlogic.gdx.tests.I18NMessageTest.create(I18NMessageTest.java:71)
	at com.badlogic.gdx.tests.utils.GdxTestWrapper.create(GdxTestWrapper.java:32)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.badlogic.gdx.tests.lwjgl3.Lwjgl3TestStarter.main(Lwjgl3TestStarter.java:83)
```

Because the tests are still perfectly usable if you run them on their own (or use LWJGL2, I think, because it might not share static state), this is not at all a priority to merge; it just makes running many tests in one session not throw an Exception.

### CODE REVIEW

**Comment by HydrolienF** [comment]
I would like to help by checking that it solve iton my computer to, but I don't find how to run a single test.
I have tried
```sh
./gradlew test --tests I18NSimpleMessageTest
```
and 
```sh
gradle -Dtest.single=I18NSimpleMessageTest test
```

**Comment by tommyettinger** [comment]
You'll want to run the `./gradlew libgdx:tests:gdx-tests-lwjgl3` task, since the tests are graphical and open up a GUI. Scroll down to I18NSimpleMessageTest (it's in alphabetical order), and click it to see what works and what doesn't. You can also (in the same run) try I18NMessageTest, since this mostly affects what happens when both tests are run. This doesn't affect behavior outside the tests (i.e. in user code that uses libGDX).

**Comment by HydrolienF** [comment]
gradle fail with `Project 'libgdx' not found in root project 'libgdx'. Some candidates are: 'gdx'.`
I have triied `./gradlew gdx:tests:gdx-tests-lwjgl3` and `./gradlew tests:gdx-tests-lwjgl3` without success.
Does it need Android SDK to be set ? Or does it fail with gradle wraper ?

**Comment by tommyettinger** [comment]
It's `gradlew :tests:gdx-tests-lwjgl3:launchTestsLwjgl3` , I usually run from IDEA, which doesn't show the exact name.

**Comment by HydrolienF** [comment]
OK !

I can confirm, this change solve it for me.

**Review by crykn — APPROVED** [review]

**Pull request merged**
