### PR TITLE
try fix quick pause/resume

### PR DESCRIPTION
**Pull request by zaijie1213**
in some case,It works

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Can you put in some information here on the problem you are trying to fix here?

**Comment by obigu** [comment]
May be related https://github.com/libgdx/libgdx/pull/4326

**Comment by Tom-Ski** [comment]
Yes it would be addressing those issues, but it doesn't explain the reasoning behind this code change, and the description isn't that comforting. Not mergable until @zaijie1213 provides more info.

**Comment by zaijie1213** [comment]
when Fragment resume and quickly paused, onDrawFrame method may  have No chance to execute,
then deadlock will happen.in this case, we can skip wait.

**Pull request closed without merging**
