### PR TITLE
Fixed some minor spelling and formatting issues.

### PR DESCRIPTION
**Pull request by bhamodi**
@badlogic

### CODE REVIEW

**Comment by Tom-Ski** [comment]
Can you consolidate these into one commit please.

**Comment by bhamodi** [comment]
@Tom-Ski - done!

**Comment by Tom-Ski** [comment]
Why is it now my commit?

**Comment by NathanSweet** [comment]
You touched it first!

Spelling fixes look good, not sure why some versions changed.

**Comment by bhamodi** [comment]
@Tom-Ski - I think I squashed my commits on top of your commit. :stuck_out_tongue_closed_eyes:

**Comment by bhamodi** [comment]
@NathanSweet - the versions changed are the ones from Tom's commit: https://github.com/libgdx/libgdx/commit/da807c12ca6ebef76c53cd582a2212c03018063e

**Comment by bhamodi** [comment]
Is this PR good to go? Or do you want me to remake it?

**Comment by nooone** [comment]
I find it very weird that you can commit in someone else's name :dancers:

**Pull request closed without merging**
