### PR TITLE
Fixed issue 4129

### PR DESCRIPTION
**Pull request by likeanowl**
Related to #4129 issue.
Added method getListeners() to Controller interface and implemented it in child classes.

### CODE REVIEW

**Comment by Tom-Ski** [comment]
Looks good, can you please use the LibGDX formatter on this.

**Comment by likeanowl** [comment]
@Tom-Ski Sorry, but what is LibGDX formatter? You probably meaning codestyle settings file, but I only found this file for eclipse, do you have the same for Intellij?

**Comment by Tom-Ski** [comment]
https://github.com/libgdx/libgdx/wiki/Contributing#eclipse-formatter

**Comment by likeanowl** [comment]
@Tom-Ski Apllied formatter, check pls.

**Comment by Tom-Ski** [comment]
Please only run the formatter on code that you have changed, it makes it hard to review when so many lines have changed due to formatting on the whole class.

**Comment by badlogic** [comment]
Implemented in 4b37a1eee154c21fa9dabce1eda84d0e31e0cc7a

**Pull request closed without merging**
