### PR TITLE
Added "contains" scaling mode.

### PR DESCRIPTION
**Pull request by Emperorlou**
Scaling.contain was missing from the scaling options. It basically functions like Scaling.fit if the image is too big to fit in the defined space, but will act like Scaling.none if it does fit. This means it will only scale the image down and never up. Useful for icons that are usually all the same size but also allowing you to use icons that are oversized without having to worry about the image spilling over into the rest of the UI.

### CODE REVIEW

**Comment by yuripourre** [comment]
@Emperorlou thank you for you contribution.

Before one can dig deeper into the code, can you fix the style? So it is easier to review?

**Comment by Emperorlou** [comment]
To be honest I don't know how. I even tried editing the file directly in
GitHub and pasting in only the changed lines and it still did this
nonsense. I assume it's a line ending issue..

**Comment by SimonIT** [comment]
I tried fixing them for you, but unfortunately you don't have _Allow edits and access to secrets by maintainers
_ enabled

**Comment by MrStahlfelge** [comment]
It is the old crlf problem, it is fine for me. You can set GH to ignore whitespaces to see the real changes. 

I like the addition, and it is missing. The only thing that could be improved is naming and JavaDoc. I know the JavaDoc goes conform with the other ones, but I always have to read twice to understand.
I checked, Android names the same scaling approach "centerInside" with the following doc:
> Scale the image uniformly (maintain the image's aspect ratio) so that both dimensions (width and height) of the image will be equal to or less than the corresponding dimension of the view (minus padding). The image is then centered in the view.

**Comment by Emperorlou** [comment]
Ah that's too bad about the naming convention because Android's variant
isn't as sussinct imo. Contain is used in CSS for the background-size
attribute, which also includes fit and cover iirc.

As for javadoc, I'm not sure where that lives.

**Review by MrStahlfelge — APPROVED** [review]
Tested this and works like a charme. My naming proposal `centerInside` is misleading if alignment is set to something different than center and this scaling is used, so we keep `contain`.
Our current Scaling.java file is CRLF formatted so this is fixed with this change, too.

**Pull request merged**
