### PR TITLE
Added the ability to add new animations to an existing ModelInstance

### PR DESCRIPTION
**Pull request by dpproduction**
I faced with problem when there are many files with animations and need to add them to existed ModelInstance. 
I described the problem in detail here:
https://stackoverflow.com/questions/47092776/libgdx-cant-play-the-animation-on-3d-model

### CODE REVIEW

**Comment by mgsx-dev** [comment]
I think your need is reasonable but your solution has some drawbacks, mainly because the modelInstance modify the shared model : 

* existing model instance won't be affected
* new model instances will be affected

I faced the same need but i solved it differently : I just copy animations from a model to some modelInstance as it's done in model instance creation code like this : 

```java
			ModelInstance mi; // a model instance with animations or not
			Model model; // a model with some other animations
			for(Animation anim : model.animations)
			{
				Animation newAnim = new Animation();
				newAnim.duration = anim.duration;
				newAnim.id = anim.id;
				for(NodeAnimation nodeAnim : anim.nodeAnimations)
				{
					NodeAnimation newNodeAnim = new NodeAnimation();
					newNodeAnim.node = mi.getNode(nodeAnim.node.id);
					newNodeAnim.translation = nodeAnim.translation;
					newNodeAnim.rotation = nodeAnim.rotation;
					newNodeAnim.scaling = nodeAnim.scaling;
					
					newAnim.nodeAnimations.add(newNodeAnim);
				}
				
				mi.animations.add(newAnim);
			}
```

Maybe this approach could be used in your addAnimation method.
What do you think ?

**Comment by dpproduction** [comment]
Yes, I agree with you. 
I made some changes, now it looks clear.

**Comment by xoppa** [comment]
Looks good. A few things though:

`addXXX` feels not good here, because the animations aren't added as-is, but copied instead. So modifications made to the animation after the method call wont affect the animation within the instance. Just making the `copyAnimations` method `public` seems more intuitive to me.

I'd expect that a common use-case would be to add one single animation, which is not possible with this change. So perhaps better split the method into a `copyAnimation` and `copyAnimations` method, where the latter just iterates over the animations and calls the `copyAnimation` method.

Also, because it's part of the public API, this needs javadocs.

**Comment by dpproduction** [comment]
Thank you for advice.
I made copyAnimation method public and split it to four methods, check the commit please.

**Comment by GemmaLamont** [comment]
This is exactly what I need for my project, will it be added in soon? :)

**Comment by catmanjan** [comment]
hey @mgsx-dev can you take a look at my issue #5643 and see what you think?

**Pull request merged**
