### PR TITLE
Fixed issue#3333 music and sound in classpath not load on Android.

### PR DESCRIPTION
**Pull request by AlphaDev-Fr**
I solve this issue : https://github.com/libgdx/libgdx/issues/3333

### CODE REVIEW

**Comment by MobiDevelop** [comment]
I'm not sure how I feel about this extracting to the cache directory every time a classpath audio is loaded business. Is there a reason you are not first checking for the existence of the file before copying it again?

**Comment by AlphaDev-Fr** [comment]
I delete the file after the MediaPlayer is prepare in order to avoid keeping useless files in caches.
If you load 2 times the same audio file it will caches 2 time because first file in cache was delete.
That why i don't check if the file is already in cache.

**Comment by MobiDevelop** [comment]
I think it is OK to leave the file in the cache.

**Comment by xoppa** [comment]
If i understand correctly, the issue is that Android mediaplayer isn't able to load classpath files and the solution is to copy the file to a temp file. What would be an actual valid use-case for this? Isn't it better to advise not to place assets on the classpath in the first place and to update the docs?

**Comment by MobiDevelop** [comment]
That's what I would favor, classpath assets should be used sparingly.

**Comment by AlphaDev-Fr** [comment]
If you want this solution, the load must throw a exception with a relevant message.
The docs already advise to not put assets on classpath.
But even if user should not put assets on classpath, i think libgdx could load file form there.
If you choose to not handle this use-case i can code the exception.
A use-case could be a audio file in a library you import.

**Comment by sarkanyi** [comment]
Isn't this unnecessary strain on the flash of the device? Who puts audio files in libraries anyway?

**Comment by badlogic** [comment]
No assets in the classpath on Android!

**Pull request closed without merging**
