### PR TITLE
Add version badges to readme

### PR DESCRIPTION
**Pull request by SimonIT**
see #5911

### CODE REVIEW

**Comment by mgsx-dev** [comment]
why not make badges as links, pointing to https://oss.sonatype.org/ ?

**Comment by SimonIT** [comment]
Is there a detail view for a dependency? Linking the start page is in my opinion useless

**Comment by mgsx-dev** [comment]
I don't think so, but it's better than linking to badge image (what i get whne i click badges). 
#5911 was about "I cannot find the sonatype nightly repo", i thought a link to sonatype oss repos could be hepful.

**Comment by SimonIT** [comment]
Okay, will add thaf

**Comment by Darkyenus** [comment]
The release badge can point to `https://search.maven.org/search?q=com.badlogicgames.gdx` or more specifically to `https://search.maven.org/search?q=g:com.badlogicgames.gdx+a:gdx`.
Maven.org has a nice ["artifact homepage"](https://search.maven.org/artifact/com.badlogicgames.gdx/gdx/1.9.10/jar), but it is specific for a version, which is not so nice.

The snapshot badge could point to `https://oss.sonatype.org/#nexus-search;gav~com.badlogicgames.gdx~gdx~~~~kw,versionexpand`. It is more useful than nothing, but it incorrectly lists 1.9.9-SNAPSHOT as the latest version and mixes in non-snapshot releases as well. I did not manage to find anything better yet, their UI is surprisingly terrible.

**Pull request merged**
