### PR TITLE
fix/improve WebGL 1.0 backend

### PR DESCRIPTION
**Pull request by mgsx-dev**
These changes was inspired by #5763. I prefer to split changes from original PR. More will come later.

Current GwtGL20 missing some buffer flips and ByteBuffer support for some methods.

### CODE REVIEW

**Comment by tommyettinger** [comment]
Huh, I hadn't noticed anything wrong with GWT's GL20 implementation. What does this change? Performance?

**Comment by mgsx-dev** [comment]
@tommyettinger nothing about performances, it fixes functionality:
* calling buffer.get(index) doesn't matter if buffer was flipped or not. That's how libgdx code access the result so that's why there are no noticeable issue.
* calling buffer.get() several times, buffer should be flipped in this case. User code may access the result  like this. Since other backends does flip the buffer, it wouldn't work for GWT backend.

**Comment by tommyettinger** [comment]
So there's a difference in behavior between other platforms and GWT? I am shocked to my very core 😱 . If this bit of extra code doesn't harm framerate on GWT (or affect it at all), then I see no problems merging.

**Review by MrStahlfelge — COMMENTED** [review]
Can't say I understand what's going on here completely, but I deeply trust the contributor and clicking through around 20 tests didn't bring up any problems.

**Pull request merged**
