### PR TITLE
Update BillboardParticleBatch

### PR DESCRIPTION
**Pull request by realitix**
Allow to customize blendingAttribute and depthTestAttribute in BillboardParticleBatch.
This commit does not change the API.

Lot of the modified lines are just my Eclipse cleaning code during save.

### CODE REVIEW

**Comment by Tom-Ski** [comment]
Please toggle that setting off if you are working on LibGDX source, it makes PRs difficult and time consuming to review.

**Comment by realitix** [comment]
OK i will do that for next pull requests !

**Comment by MobiDevelop** [comment]
Doesn't merge cleanly. Please rebase, and reformat using the libgdx formatter.

**Comment by realitix** [comment]
Ok I created a new pull request.
https://github.com/libgdx/libgdx/pull/3022

**Pull request closed without merging**
