### PR TITLE
Reduce number of instantiations within IntersectPolygons.

### PR DESCRIPTION
**Pull request by AldousP**
Removed unneeded List operations.

### CODE REVIEW

**Comment by xoppa** [comment]
Why are you using `ArrayList` instead of `Array`? (see https://github.com/libgdx/libgdx/wiki/Contributing)

**Comment by AldousP** [comment]
@xoppa fixed.

**Comment by xoppa** [comment]
Thanks! `Array<Float>` can be replaced with `FloatArray`, which avoids boxing. I guess this method is intended to be called frequently. In that case it is better to move all garbage out of the method, e.g. by making the array and vectors static. I think there are already static vectors in that class. Can you also remove the `Arrays.copyOf`, since that will create garbage as well.

**Comment by AldousP** [comment]
Went ahead and added some new static variables above the method for clarity.

**Comment by Tom-Ski** [comment]
Good stuff, could you squash your commits on this?

**Comment by AldousP** [comment]
@Tom-Ski Squashed.

**Comment by Tom-Ski** [comment]
This has merge conflicts unfortunately

**Comment by AldousP** [comment]
Ah, I bet it's because I squashed in the commit that was already merged with master in a different PR. I will take care of it later this evening.

**Comment by xoppa** [comment]
Could you change this line: `outputPoints = floatArray.toArray();` practically that creates a new `float[]` array for every vertex.

**Comment by AldousP** [comment]
@Tom-Ski corrected the merge.

**Comment by AldousP** [comment]
@Tom-Ski eliminated merge conflict.

**Comment by AldousP** [comment]
@xoppa removed array copy that was occurring each frame.

**Comment by xoppa** [comment]
Thanks!

**Comment by NathanSweet** [comment]
Probably don't need to call `getTransformedVertices` so many times.

**Pull request merged**
