### PR TITLE
BaseTmxMapLoader refactoring Mk2

### PR DESCRIPTION
**Pull request by TCreutzenberg**
This is a replacement pull request for https://github.com/libgdx/libgdx/pull/5495

Refactored BaseTmxMapLoader, TmxMapLoader and AtlasTmxMapLoader.

Shared functionality was moved to BaseTmxMapLoader, duplicate and incomplete code was removed.

Basic load/loadAsync functionality remains the same and all TmxMapLoader-tests run normally.

The old codebase had a lot of duplicate code. This is fixed now but required a lot of methods to be changed completely.

Now TmxMapLoader and AtlasTmxMapLoader work the same way, and they are capable of the same things (this was not the case before).
New features can now be implemented and both TmxMapLoader and AtlasTmxMapLoader will automatically receive the benefits.

@MobiDevelop @mgsx-dev @Ktar5 This is a proper refactor. Please have a look at this pull request if you have the time, thank you!

PS: TiledMapGroupLayerTest was changed because the .tmx was missing from the repository so I just reused the test as it was not working anyway. Please check TiledMapGroupLayerTest  for groups and nested groups.

### CODE REVIEW

**Comment by TCreutzenberg** [comment]
At the moment there are StaticTiledMapTiles created for each tile in the map.
Later it is checked if there should be an AnimatedTiledMapTile at that position, which then gets created and which replaces the StaticTiledMapTiles at this position.
Check BaseTmxMapLoader line 662, this was already done this way before the refactor.

I did not dind a reason why a StaticTiledMapTile should be created there at all then.
Does anybody know the reason or is this just a the way it was done?

**Comment by TCreutzenberg** [comment]
Hey guys, it would be really great if somebody could have a look at this pull request. Thank you very much i advance!

**Comment by NathanSweet** [comment]
I'm not sure who our map person is. Hopefully they will be along shortly!

**Comment by mgsx-dev** [comment]
It's on my TODO list. I'll try to test and review it when i have time to do so because of the amount of code. It looks promising though :-)

**Comment by MobiDevelop** [comment]
I've done a quick review and looks okay from that, I'd still like to pull and test it.

**Comment by MobiDevelop** [comment]
Had a play with this and it looks good to me. Might be a little more duplication that be reduced but I'll probably merge this and follow-up if needed.

**Pull request merged**
