### PR TITLE
Remove duplicate javadoc in Intersector

### PR DESCRIPTION
**Pull request by Darkyenus**

### CODE REVIEW

**Comment by antag99** [comment]
Why not remove the main method as well while you're at it?

**Comment by Darkyenus** [comment]
That main looked like a test, so it probably isn't wise to just remove it. It could be made into unit test later.

**Comment by davebaol** [comment]
That's why I've just comment it out after merging you PR ;)

**Comment by antag99** [comment]
Why are there no JUnit tests? :(

**Pull request merged**
