### PR TITLE
update gdx-bullet extensions to bullet 2.86.1

### PR DESCRIPTION
**Pull request by nicolaichuk**
update to bullet 2.86.1 https://github.com/bulletphysics/bullet3/releases/tag/2.86.1

fix all swig warnings
update jni header files
add BulletInverseDynamics
add Vehicle

For issue: https://github.com/libgdx/libgdx/issues/4614

### CODE REVIEW

**Comment by nicolaichuk** [comment]
@badlogic, @Tom-Ski, @Xoppa, @jsjolund, @floralvikings, @NathanSweet, @nooone, @badlogic, @alex55i, @jrenner: 

Please review and merge to main branch.

**Comment by intrigus** [comment]
This is not going to work.
The build files are automatically generated and should not be modified manually.
Also, why did you update all those jni headers? Don't fix things if the aren't broken.

**Comment by nicolaichuk** [comment]
@intrigus:

> This is not going to work.

Ok. And what will work?

> The build files are automatically generated and should not be modified manually.

What kind of my change are you talking about?

> Also, why did you update all those jni headers? Don't fix things that aren't broken.

I did it at the same time. I can revert change in jni header files. This change is not important for me.

**Comment by nicolaichuk** [comment]
ping...

please review.

**Comment by Tom-Ski** [comment]
@nicolaichuk what platforms did you test this on?

**Comment by nicolaichuk** [comment]
@Tom-Ski 
> what platforms did you test this on?

windows 7 64bit

**Comment by Tom-Ski** [comment]
@nicolaichuk thanks very much for the PR. I've not been able to build your PR on all platforms and in VS so it was hard to review and was taking up too mucch time. I've started fresh and added the minimal changes to update to 2.86.1, using your swig files for the minimal changes so some of your additions present in this PR will be missing. 

These can be added in a follow up PR if you wish to add them as that will be a lot easier to review than a full update _and_ also lots of changes unrelated to simply updating the version. This version is in the latest snapshots, and you can fetch the natives if you are building from source.

**Comment by nicolaichuk** [comment]
@Tom-Ski, thanks.

Please code review https://github.com/libgdx/libgdx/pull/4961

**Pull request closed without merging**
