### PR TITLE
Add Poolable#onObtain and Poolable#onFree

### PR DESCRIPTION
**Pull request by Ktar5**
Created default methods onObtain() and onFree() within the Poolable interface so that they may be used for state changes that a user may want. For example, the use case that gave me this idea was trying to check if an object was in active or in a pool and there was currently no plain & simple way to do it.

It's been implemented into Pool#freeAll() , Pool#free() , and Pool#obtain() and will work with this implementation due to the nature of Pools' methods using the Pool#free/all/obtain methods as opposed to their own implementation.

Any comments, concerns, suggestions, etcetera would be appreciated if there is anything keeping this from being accepted.

### CODE REVIEW

**Comment by Ktar5** [comment]
Why are we building JDK 6 if minimum requirements (https://libgdx.badlogicgames.com/documentation/gettingstarted/Setting%20Up.html) are JDK 7

**Comment by intrigus** [comment]
You can't use java 8 in the libgdx core

**Comment by Darkyenus** [comment]
This seems to be a relatively big change for the `Pool` and I am worried about it's performance implications, but it could be added as an `Pool` subclass, to be used only when needed (this could also eliminate `instanceof` checks, as the new `PoolableWithOnObtainAndOnFree` interface (working name) could be required by the generic constraint).

**Comment by Ktar5** [comment]
@Darkyenus I think I'll do what you said and work on a new Pool/able implementation where it doesn't use generic Object and instead uses an implements DescriptivePoolable or something of that sort.

**Pull request closed without merging**
