### PR TITLE
Remove maven/ant build

### PR DESCRIPTION
**Pull request by PokeMMO**

### CODE REVIEW

**Comment by Frosty-J** [comment]
Why? The instructions on the website use `ant`, so we'll need an alternative.

https://libgdx.com/dev/natives/

**Comment by PokeMMO** [comment]
Rebased to fix conflicts, should be ready to merge.

**Review by tommyettinger — APPROVED** [review]
Looks like pure removal, fine by me. I think the libgdx.com docs about working from source may need to be updated, though. I could be thinking of an older version, but I remember Ant being mentioned at one point in official docs.

**Comment by PokeMMO** [comment]
@crykn already handled the website changes before I even had a chance.

https://github.com/libgdx/libgdx.github.io/commit/78b338203bf36a9251b71b78f2d27f78f3bb5703
https://github.com/libgdx/libgdx.github.io/commit/94ce5e7ed141cae9ac708ee6b1b8880563a6dbee

**Comment by PokeMMO** [comment]
Rebased to resolve conflicts. Will merge once CI finishes.

**Pull request merged**
