### PR TITLE
Rename identifer _ -> _Constants

### PR DESCRIPTION
**Pull request by 15characterlimi**
"_" as an identifier is deprecated. It produces a warning during
compilation in Java 8, and an error in Java 9.

See:
  https://bugs.openjdk.java.net/browse/JDK-8061549

### CODE REVIEW

**Comment by 15characterlimi** [comment]
@xoppa Mario says that this code/identifier is likely generated. Can you help?

**Comment by xoppa** [comment]
It is indeed, to quote the header of the files you've modified:
```
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
```

**Comment by 15characterlimi** [comment]
@xoppa okay, I think I've changed the correct source files now from which swig generates those files (see first commit). However, when I regenerate the code using swig 3.0.10 (which is ancient BTW), a bunch more stuff changes other than just the identifiers that I've renamed; some types are changing, too.

Shall I just manually rename those Java identifiers again without doing the whole swig run?

**Comment by 15characterlimi** [comment]
Ping?

**Comment by nicolaichuk** [comment]
@xoppa, please review related PR https://github.com/libgdx/libgdx/pull/4636


@15characterlimi, what you want can do only with SWIG without change bullet source

something like this:

```
%rename(EnumFlagType) btSoftBody::eAeroModel::_;
%rename(EnumFlagType) btSoftBody::eVSolver::_;
%rename(EnumFlagType) btSoftBody::ePSolver::_;
%rename(EnumFlagType) btSoftBody::eSolverPresets::_;
%rename(EnumFlagType) btSoftBody::eFeature::_;
%rename(EnumFlagType) btSoftBody::fCollision::_;
%rename(EnumFlagType) btSoftBody::fMaterial::_;
%rename(EnumFlagType) btSoftBody::Joint::eType::_;

%rename(getSolverV) btSoftBody::getSolver(btSoftBody::eVSolver::_);
%rename(getSolverP) btSoftBody::getSolver(btSoftBody::ePSolver::_);

%rename(EnumFlagType) fDrawFlags::_;
```

**Pull request closed without merging**
