### PR TITLE
I wanted to improve the loading process of an HTML5 game with libGDX.…

### PR DESCRIPTION
**Pull request by MonsterOfCookie**
… As currently the process is.
1. Load index.html
2. Synchronously load the javascript files
3. Preload assets, get them cached in the browser (This is currently, where a player would see the libGDX logo and a progress bar).
4. (optional) Loading assets into memory with a custom loading screen via an AssetManager

In smaller games this is can be acceptable loads times. However as a game grows I have generally found that whilst the code size (The JS files are around 1-3MB) the art (Artists demanding HD level quality) the process of getting a player into the game becomes longer and drawn out and offputting. I have also been involved in projects where a HTML5 gaming platform would require a single loading experience for all binary and asset loading, providing their own loading screen etc.

I have a working example of a game where the JS is split and a boot strap occurs first then the main game JS is loaded separately. Then any assets are then loaded on demand, e.g. the AssetManager wishes to load a texture, this request is intercepted and the browser instructed to download the asset, then the loading into memory can occur.

Before I unleash this all on the world I wanted to see if I could clean up a couple of things in the GWT backend to make what I did simplier and cleaner looking. So this commit is more about setting the stage ready for the next phase of the loading.

When going through the code, I discovered that the canvasId that can be specified in the configuration is never used. Thus never letting you create and specify your own canvas, this commit fixes that.
1. I moved the preloading code into separate classes and I created an interface to allow other people to create their own preloaders and reuse the existing download code.
2. I have removed the config.root property as it was no longer needed, the code now only checks for the presence of the canvasId field.
3. If the canvasId does exist, the default preloader will still create the progress bar and libGDX logo except upon completion it no longers creates the canvas

This is backwards compatible and I have tested it the project created via the project setup tool.

I hope this makes sense to people, if I have done something I shouldn't have please let me know and I will fix it.

### CODE REVIEW

**Comment by barkholt** [comment]
Haven't looked at the code, but I 100% support the idea of refactoring/modernizing the preloading process on GWT. I understand the need for preloading in order to support the synchronous file API, but if we are only loading asynchronously, we should not have to force the users to wait for the preload (and potentially exhaust browser memory in process).

**Comment by roseroser** [comment]
I have the same issue, can any one solve this problem?

**Comment by CodeMason** [comment]
I've been waiting for this for a while -- any idea when this will be merged?

**Comment by MonsterOfCookie** [comment]
I feel this might be pretty out of date now as I made more changes etc. I think what might happen is this could become an extension.

**Comment by SimonIT** [comment]
I can't run `tests:gdx-tests-gwt:superDev` with your changes.

At first, I get this error:
```
libgdx\tests\gdx-tests-gwt\src\com\badlogic\gdx\tests\gwt\client\GwtTestStarter.java:24: error: GwtTestStarter is not abstract and does not override abstract method getApplicationLogger() in Application
public class GwtTestStarter extends GwtApplication {
```
After I implemented the methods from GwtApplication, I run into this error:
```
Compiling module com.badlogic.gdx.tests.gwt.GdxTestsGwt
   [ERROR] Errors in 'libgdx\tests\gdx-tests-gwt\build\gwt\gen\com\badlogic\gwtref\client\IReflectionCacheGenerated.java'
      [WARN] Line 21566: Referencing field 'com.badlogic.gdx.graphics.g2d.SpriteBatch.defaultVertexDataType': field 'com.badlogic.gdx.graphics.g2d.SpriteBatch.defaultVertexDataType' is deprecated
      [WARN] Line 21567: Referencing field 'com.badlogic.gdx.graphics.g2d.SpriteBatch.defaultVertexDataType': field 'com.badlogic.gdx.graphics.g2d.SpriteBatch.defaultVertexDataType' is deprecated
      [WARN] Line 23165: Referencing field 'com.badlogic.gdx.math.Matrix4.tmp': field 'com.badlogic.gdx.math.Matrix4.tmp' is deprecated
      [WARN] Line 29404: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActor': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActor(Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29405: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAt': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAt(ILcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29406: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorBefore': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorBefore(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29407: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAfter': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAfter(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29746: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.setWidget': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.setWidget(Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29747: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.getWidget': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.getWidget()' is deprecated
      [WARN] Line 29748: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActor': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActor(Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29749: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAt': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAt(ILcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29750: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorBefore': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorBefore(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 29751: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAfter': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAfter(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 31049: Referencing method 'com.badlogic.gdx.utils.JsonValue.size': method 'com.badlogic.gdx.utils.JsonValue.size()' is deprecated
      [ERROR] Line 13766: No source code is available for type javax.annotation.Nonnull; did you forget to inherit a required module?
      [ERROR] Line 13766: No source code is available for type javax.annotation.meta.When; did you forget to inherit a required module?
   Tracing compile failure path for type 'com.badlogic.gwtref.client.IReflectionCacheGenerated'
      [ERROR] Errors in 'libgdx\tests\gdx-tests-gwt\build\gwt\gen\com\badlogic\gwtref\client\IReflectionCacheGenerated.java'
         [ERROR] Line 13766: No source code is available for type javax.annotation.Nonnull; did you forget to inherit a required module?
         [ERROR] Line 13766: No source code is available for type javax.annotation.meta.When; did you forget to inherit a required module?
   [ERROR] Hint: Check that the type name 'com.badlogic.gwtref.client.IReflectionCacheGenerated' is really what you meant
   [ERROR] Hint: Check that your classpath includes all required source roots
   [ERROR] Errors in 'com/badlogic/gwtref/client/ReflectionCache.java'
      [ERROR] Line 24: Rebind result 'com.badlogic.gwtref.client.IReflectionCacheGenerated' could not be found
```
Please fix this so we can run the tests.

Is it needed to improve the loading process to change from SoundManager2 to your WebAudioAPIManager implementation? If not, maybe splitting the PR increases the chance to get this merged.

Some formatting tips to increase the merge chance:
- don't change the line ending (like you did for example in GwtApplicationConfiguration.java)
- some of your created files use 4 spaces as indentation. libgdx uses tabs (for example OnDemandAssetLoader.java)

**Comment by MonsterOfCookie** [comment]
> Please fix this so we can run the tests.

It's open source, feel free to do this yourself.

**Comment by MrStahlfelge** [comment]
I took your base idea and it is added now to the GWT backend with #5677 
@MonsterOfCookie we miss you on the Discord, would be great to see you again.

**Pull request closed without merging**
