### PR TITLE
Fix PixmapBlendingTest

### PR DESCRIPTION
**Pull request by yuripourre**
If I try to run the test for LWJGL3 as-is it gives me an error saying that cannot find test3.png or test4.png files.

### CODE REVIEW

**Review by tommyettinger — COMMENTED** [review]
I don't think this changes anything on LWJGL 2 or 3; if you go to the implementation of files.getFileHandle() for those platforms, it is the same code as would be called with files.internal(). Is this meant more for Android, iOS, or something else? The other clean-up is nice, though.

**Comment by tommyettinger** [comment]
I should also say, I have just run the test without this PR on LWJGL 2 and 3 right now, so unless something changed in the latest code for Lwjgl(3)Files, I don't know if this is needed. It is cleaner, though.

**Comment by yuripourre** [comment]
@tommyettinger I tried to run in Lwjgl3 and for some weird reason it couldn't find the files I mentioned. After this change, the test also worked on GWT. Would you mind trying to run this test on GWT? It is currently disabled.

**Comment by tommyettinger** [comment]
I'm wondering if something changed after the commit I have checked out, since the test works without needing this PR (for me).
Working test screenshot

Thinking about it, though, this PR does just in general improve the code style, so **consider this an approval**. I'm just trying to figure out why it could be needed at all to run, since the code paths look identical for internal() and getFileHandle().

**Comment by yuripourre** [comment]
Thank you for taking the time for testing. @tommyettinger I was not using the latest master indeed, maybe it was fixed at some point. I had some trouble loading files as bytes (it simply doesn't load) using GWT but I have no idea if it's related somehow.
I will start from a clean repository and try again later.

Thanks again!

**Comment by tommyettinger** [comment]
Pixmap on GWT simply doesn't have a constructor that takes a `byte[]`. This is only visible if you look at the super-sourced code for Pixmap used on GWT, https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java . I'm not totally sure why this is, since there's a setPixels() that takes a ByteBuffer, but it calls into JSNI code.

Even though it might no longer be a "fix," I think this still makes PixmapBlendingTest more readable and more like the rest of libGDX's code. I won't close this unless you think the file should stay as-is.

**Comment by yuripourre** [comment]
@tommyettinger agreed, let's merge this.

**Pull request merged**
