### PR TITLE
Defer content view resolve for KeyboardHeightProvider to allow for late setContentView

### PR DESCRIPTION
**Pull request by Berstanio**
Fixes https://github.com/libgdx/libgdx/issues/7537

### CODE REVIEW

**Review by obigu — APPROVED** [review]

**Comment by anhduyqh123** [comment]
NullPointerException on AndroidXKeyboardHeightProvider.close on version 1.13.1

**Comment by Berstanio** [comment]
> NullPointerException on AndroidXKeyboardHeightProvider.close on version 1.13.1

Do you have a stacktrace? Is the crash common?

**Comment by tommyettinger** [comment]
Looks an awful lot like a near-copy of the text for the PR (for 1.13.0) directly above it, @Berstanio . I'm thinking spam or other non-standard-human behavior. So I don't think it's real.

**Comment by Berstanio** [comment]
> Looks an awful lot like a near-copy of the text for the PR (for 1.13.0) directly above it, @Berstanio . I'm thinking spam or other non-standard-human behavior. So I don't think it's real.

Yeah, not sure. The thing is, it is technically possible to NPE, if `onDestroy` is called before/without `onResume`, but not sure whether this can actually happen in the android lifecycle.

**Comment by obigu** [comment]
> Yeah, not sure. The thing is, it is technically possible to NPE, if `onDestroy` is called before/without `onResume`, but not sure whether this can actually happen in the android lifecycle.

I think if the Activity forcibly finishes on `onCreate()` or `onStart()`, `onResume()` won't be called. Not a very usual scenario but probably worth adding a null check condition in `onDestroy()`.

**Comment by anhduyqh123** [comment]
Screenshot 2025-01-18 170742
When I updated from version 1.13.0->1.13.1 I encountered a problem as shown in the attached image.

**Pull request merged**
