### PR TITLE
Deleted Redundant codes

### PR DESCRIPTION
**Pull request by elifnurcevik**
I committed two commits

Deleted Unnecessary Conversion to String
Deleted redundant semicolon

This commitment supports to open source community for **Hacktoberfest**.

### CODE REVIEW

**Comment by elifnurcevik** [comment]
Hi @mgsx-dev, why did you mark as invalid this pull-request?

**Comment by crykn** [comment]
Hey @elifnurcevik, if you take a look at the Hacktoberfest site, there is a section about "Quality standards":
> In line with Hacktoberfest value no. 2 (Quantity is fun, quality is key), we have provided examples of pull requests that we consider to be low-quality contributions (which we discourage).
> - Pull requests that are automated (e.g. scripted opening pull requests to remove whitespace/fix typos/optimize images).
> - Pull requests that are disruptive (e.g. taking someone else's branch/commits and making a pull request).
> - Pull requests that are regarded by a project maintainer as a hindrance vs. helping.
> - Something that's clearly an attempt to simply +1 your pull request count for October.

We very much like to encourage people to collaborate on libGDX (and we think that hacktoberfest is a pretty cool event!), but we don't like to see a lot of low-effort PRs, i.e. spelling, javadoc, or formatting fixes (basically anything that does not even need a dev env set up for libGDX) just to up one's pull request count. You have to bear with us: we all do this in our spare time and have a vested interest in not being overwhelmed with too many "spammy" PRs that take up our time and prevent us from doing some real work.

**Comment by elifnurcevik** [comment]
> Hey @elifnurcevik, if you take a look at the Hacktoberfest site, there is a section about "Quality standards":
> 
> > In line with Hacktoberfest value no. 2 (Quantity is fun, quality is key), we have provided examples of pull requests that we consider to be low-quality contributions (which we discourage).
> > 
> > * Pull requests that are automated (e.g. scripted opening pull requests to remove whitespace/fix typos/optimize images).
> > * Pull requests that are disruptive (e.g. taking someone else's branch/commits and making a pull request).
> > * Pull requests that are regarded by a project maintainer as a hindrance vs. helping.
> > * Something that's clearly an attempt to simply +1 your pull request count for October.
> 
> We very much like to encourage people to collaborate on libGDX (and we think that hacktoberfest is a pretty cool event!), but we don't like to see a lot of low-effort PRs, i.e. spelling, javadoc, or formatting fixes (basically anything that does not even need a dev env set up for libGDX) just to up one's pull request count. You have to bear with us: we all do this in our spare time and have a vested interest in not being overwhelmed with too many "spammy" PRs that take up our time and prevent us from doing some real work.

I don't agree with you because this is not spam. Not everyone is an expert. You should not discourage those who are new to programming like me from open source. Even if the contribution is small, it is a contribution.

**Comment by crykn** [comment]
Looking at your past "contributions" for other repos, I don't think I'm alone with my assessment: https://github.com/Darkhax-Minecraft/Dark-Utilities/pull/231, https://github.com/Javacord/Javacord/pull/648, https://github.com/FasterXML/jackson-dataformats-binary/pull/223.

**Comment by payne911** [comment]
May I ask if this PR would be merged if it wasn't surrounded by the context of **Hacktoberfest** ?

**Comment by Tom-Ski** [comment]
No

**Pull request closed without merging**
