### PR TITLE
adds horizontal text alignment feature for textfields

### PR DESCRIPTION
**Pull request by AlbertoCejas**
Textfields offered the possibility of left and right aligned text but not centered. I kept [setRightAligned](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/ui/TextField.html#setRightAligned-boolean-) as deprecated and added setTextAlignment which makes use of Align class, ensuring only left, center and right options are allowed.

Tested on UITest

(Don't know why commit diff doesn't show properly even using your libgdx eclipse-formatter, utf-8 encoding and Unix line ending)

### CODE REVIEW

**Comment by nooone** [comment]
I'm still wondering why TextField isn't a Table. I thought everything is a Table. Mind blown.

**Comment by siondream** [comment]
@AlbertoCejas could you please:

1. Add the API changes to the [`CHANGES`](https://github.com/libgdx/libgdx/blob/master/CHANGES) file
2. Pull from `master`
3. Merge the conflicts
4. Resubmit

Then I'll just merge the PR.

**Comment by NathanSweet** [comment]
I would prefer to remove `setRightAligned` since it's an easy fix and who knows when someone would actually get to removing it if deprecated.

**Comment by AlbertoCejas** [comment]
I mess this PR up. I will close it and create a new clean one.

**Pull request closed without merging**
