### PR TITLE
#5858 Ray normalise origin vector after set methods

### PR DESCRIPTION
**Pull request by fabiitch**
issue #5858

### CODE REVIEW

**Comment by mgsx-dev** [comment]
Since direction field is public, wouldn't be better to let user code ensure providing unit vector and avoid normalization instead?

Javadoc could be improved in that way.

**Comment by fabiitch** [comment]
My java developer part said "if constructor normalise direction vector why set methods dont".

But you are right, if you use set method for re-use same object. its dump to add calcul with nor.

i change commit , i remove nor() on public Ray set (Vector3 origin, Vector3 direction) and precise in javadocs.
I remove it on public Ray set (Ray ray) too cause it was dumb , if you got a Ray object, direction vector is already normalised.

I keep on methods public Ray set (float x, float y, float z, float dx, float dy, float dz) cause i think its necessary with 3 float param.

Your opinion ?

**Comment by fabiitch** [comment]
i push force on my fork and i close this pr.
i reopen new at https://github.com/libgdx/libgdx/pull/5860

sry for miss

**Comment by mgsx-dev** [comment]
there was no need to create a new PR, force push on your branch automatically update this PR.

**Pull request closed without merging**
