### PR TITLE
Make Xbox Controller linux friendly

### PR DESCRIPTION
**Pull request by Desmaster**
- Added key mappings for linux
- Added 2 new buttons to Xbox: L3 and R3
- Made Xbox#isXboxController() match more variants
- Added test called XboxControllerTest

Wanted to add controller support and working on linux, found out that the Xbox class didn't have the keys mapped for linux. Also improved it at some points.

I tested this on Linux Mint 17.3. 

Few questions:
- Do we need to be a bit more careful, because of the wide variety of linux distros?
- Do I need to add the changes to the `CHANGES` doc?

This fixes a part of https://github.com/libgdx/libgdx/issues/3879

### CODE REVIEW

**Comment by Desmaster** [comment]
Can someone test for osx?
Linux output here: [debugtest.txt](https://github.com/libgdx/libgdx/files/192491/debugtest.txt)
If you don't see the first 3 errors in your log, let's consider it as an environmental output.

**Comment by np511** [comment]
The first three lines are related to your sound setup - I'm assuming that the [GNU/Linux](http://www.gnu.org/gnu/linux-and-gnu.html) natives check all sound systems - ALSA, PulseAudio, JACK, and any others - to see if they can be used.

_I put the link in because I get annoyed when I see people call the system Linux. Linux is_ not _an OS, GNU/Linux is. Linux is the kernel - a_ part _of the OS._

**Comment by saltares** [comment]
Looks good to me!

* Can you update `CHANGES` and squash commits into 1 after?
* What part of #3879 would be left after we merge this?
* Can you sign the [contributor agreement](https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#contributor-license-agreement)?

**Comment by Desmaster** [comment]
@saltares 
Will look into it tonight, squash is fine, there's gonna be a second commit anyway.
I'll let you know :).

**Comment by Desmaster** [comment]
I force pushed a squash commit, now everything went to shit, lol.. It even included MobiDevelop's commit.. 

Suggestions?

**Comment by np511** [comment]
From what I can tell, you mistyped the package. com.badlog.gdx.backends.jflgw.utils is what it should be IIRC. I haven't worked with that backend so I'll look in the backend source later to confirm.

**Comment by Tom-Ski** [comment]
Easiest solution if you aren't a wizard with git would be to reset your head and just add the test and the mapping in again.

Do you have a full log for controller input on linux?  Otherwise we can't test to see if we get the same values for all the axis controls.

**Comment by badlogic** [comment]
No activity in a while, closing this out.

**Comment by CreamyCookie** [comment]
@Desmaster Any chance you will create a new pull request with these changes?

**Comment by Desmaster** [comment]
@CreamyCookie I've discussed this with @Tom-Ski.

We have concluded back then the whole controller system needs to be rewritten. That's because it's really difficult to get all the key mapping "right" for lwjgl2/lwjgl3 and win/osx/linux. There's also a wide variety of controllers, even the Xbox 360 controller keys aren't consistent(I've done some research on multiple Xbox controllers).

For the linux support, I can send you a custom class that I ended making to get this to work in my current project. Interested?

**Comment by CreamyCookie** [comment]
@Desmaster Yeah, that makes a lot of sense. I just tried my Steam Controller which emulates an Xbox controller. And on Linux the DPAD of the Xbox controller consists of two axes (6 for horizontal, 7 for vertical) not 4 buttons..

> Interested?

Yes, absolutely!

**Comment by CreamyCookie** [comment]
@Desmaster Yeah, that makes sense. I've tested with my Steam Controller which emulates an Xbox controller. There are a lot of inconsistencies. On Linux the DPAD of the Xbox controller is represented as two axes (6 for horizontal, 7 for vertical) instead of 4 buttons.. This is only worked with lwjgl3. With lwjgl2 the DPAD didn't trigger anything except pov events with `PovDirection.center`.

> For the linux support, I can send you a custom class that I ended making to get this to work in my current project. Interested?

Yes, definitely! (If you want to send me this via email, tell me and I'll send you my address.)

**Comment by Desmaster** [comment]
@CreamyCookie Sorry for the late response. Hope it could still be helpful: https://gist.github.com/Desmaster/43e478f73c0cdd86788ebc90ec0bf94e

**Comment by CreamyCookie** [comment]
@Desmaster It's still useful. Thank you!

**Pull request closed without merging**
