### PR TITLE
Make instantiation of Files overridable

### PR DESCRIPTION
**Pull request by MrStahlfelge**
In reaction to #6345, this makes the instantiation of Files implementation overridable on Android. GWT is done, too, because overriding it is useful in projects often to change the handling of local files. Discussing with @obigu, we never had the need to change Files on desktop or iOS, so this is not changed here.

Testing discovered that `FilesTest` was broken on non-GWT platforms by #6188 and is fixed hereby.

Entry suggestion for CHANGES file:
```
* API Change: AndroidFiles and GwtFiles instantiation can be overriden by own classes. NoExternalAndroidFiles implementation can be used to avoid unnecessary write to external files dir if not needed (see #6345)
```

### CODE REVIEW

**Comment by obigu** [comment]
I think that even if we have never had the need to change them, we should follow the same approach on all backends (same as `Audio` and `Input`.

**Comment by MrStahlfelge** [comment]
Apart from that, what's your opinion on this change?

**Comment by obigu** [comment]
I like giving the option of extendibility, I think it's a good change. Regarding the details of the Android implementation I would probably just pass a `boolean` to the `DefaulAndroidFiles` constructor to indicate if it requires "external" and initialize accordingly and avoid the protected `initExternalFilesPath` method and alternative `NoExternalAndroidFiles` that is a bit too complex IMO.

**Comment by MrStahlfelge** [comment]
Good idea with the param and get rid of NoExternalAndroidFiles. I would like to keep the initExternalFilesPath though. It is possible to override it to use another path.

**Comment by MobiDevelop** [comment]
I agree on ditching the `NoExternalAndroidFiles` subclass.

**Comment by MrStahlfelge** [comment]
Changes done

**Comment by crykn** [comment]
I think you should add `@Override` annotations to make it consistent with `createInput()` and `createAudio()`. And for the same reason: maybe make the method public as well? Apart from that, it looks good to me.

**Comment by MrStahlfelge** [comment]
Thanks for looking at this. 

Just adding an `Override` annotation would break the compile because the new methods don't override anyhting, they are meant to be overriden. :) 

I don't know why the two other factory methods were added to the super interface and were made public. I don't see any use case to call them from outside to instantiate a second or third audio or files handler. Maybe @obigu can tell us his intention behind this.

**Pull request merged**
