### PR TITLE
Update moe version to 1.3.2

### PR DESCRIPTION
**Pull request by rolandvigh**

### CODE REVIEW

**Comment by Zomby2D** [comment]
The latest release is 1.3.0

Version 1.3.2 was a naming error and it got replaced by the right version a few days later as you can see in the [releases](https://github.com/multi-os-engine/moe-tools-common/releases).

**Comment by Tom-Ski** [comment]
Looks like a mistag on github. All the binaries are 1.3.2 latest in the maven repositories.

**Comment by MobiDevelop** [comment]
Well, if they accidentally released somehting as 1.3.2 then it would be the latest number (you can't delete that version). According to their blog release announcement, it should be 1.3.0.

https://multi-os-engine.org/blog/2017-03-16-moe-1.3.0-released/

**Comment by Tom-Ski** [comment]
Their tooling has also been bumped to target 1.3.2 SDK.  

@rolandvigh can you confirm this is the correct version?

**Comment by Zomby2D** [comment]
Sorry about that then... in the future I will not base judgement on the Github release tags and blog announcements.

**Comment by MobiDevelop** [comment]
Might make it easier if people associated with MOE had that association listed on their profiles - I'd not question the version number if I knew that it was a MOE team member that submitted the PR.

**Comment by code-disaster** [comment]
This PR modifies CHANGES in the 1.9.6 section, is this intended? :)

**Pull request merged**
