### PR TITLE
Lwjgl3 backend's OpenAL audio on a dedicated thread

### PR DESCRIPTION
**Pull request by voidburn**
- Synchronized access for the music add/remove/update methods
- Moved dispose method in the dedicated thread (The MockAudio won't use natives that require disposal anyway)
- Testers welcome!

### CODE REVIEW

**Comment by voidburn** [comment]
There is currently an issue with Music.setPosition(), looking into it, help appreviated :)

**Comment by intrigus** [comment]
I'm pretty sure, that this is not properly synchronized. You would probably have to synchronize *all* methods.

**Comment by voidburn** [comment]
Tested with AudioDeviceTest and MusicTest, seems to be working. Sadly I don't have a complex sound usage in my engine yet, would definitely like some feedback from someone that hits it hard :)

**Comment by code-disaster** [comment]
I'm worried that we ask for trouble in the long run by doing synchronization like this. It would be a lot cleaner to let the public API write into some postMessage() style queue, and let the audio update thread take care of the execution.

**Comment by voidburn** [comment]
@code-disaster If the multi-threaded render loop happens I'll implement your suggestion on top of that, unless Mario tackles it while looking into it (actually rendering and audio updates could just share the same thread, making this useless).

Anyway, I agree completely, that's how I'm handling Gdx.graphics.setCursor() calls from the APIs in my multi-threaded renderer implementation right now, far cleaner.

**Comment by ollipekka** [comment]
+1 @code-disaster 

I would advise against merging this. This looks like potential source of problems and adds complexity when it could be simple. If you need multi-threaded audio support you could fork the libgdx audio API and roll your own.

**Comment by sreich** [comment]
Silly question here, but when is multithreaded audio needed or desirable?

**Comment by code-disaster** [comment]
@sreich it's one approach to avoid blocking audio updates in case the main thread blocks, e.g. what happens when you try to resize or move the application window (see #4419), or for example during screen transitions when you may have some heavy I/O work to do.

**Comment by voidburn** [comment]
I'm definitely going to close this, since in the end it was not even the correct approach (though I tested it heavily with a LRU cache backing the sound and music banks, and I had zero problems even when the audio backend was concurrently fed multiple playbacks from multiple threads.

Anyway, this was all born from the necessity of having the winproc thread not interfere with the rest of the threads during window drag operations (on windows, and possibly on OSx under some circumstances, the winproc thread is completely frozen during the window drag and until you release it).

I started with the audio backend, then moved to the renderer (in the process losing multi-window rendering btw, just couldn't make it work), I made this pull request thinking it was a good stand-alone feature, and in part because someone left the "FIX THIS: MOVE TO SEPARATE THREAD" comment in the audio loop - or something like that-.

In the end I **haven't used this**, because I moved both the audio AND the renderer together in their own thread, effectively decoupling everything else from the winproc thread, using what I found in #4419 as implementation hint.

The reason I haven't posted that PR is because I ended up further customizing my backend (I don't use gradle for my project) to be able to switch arbitrary versions of LWJGL and plug LWJGL modules as I see fit, while wrapping them in handy Gdx.app.whatevermodule method calls.

Closing this PR, if you ever feel like you need something like this, consider instead using @code-disaster suggestion and provide a thread safe queue to push requests, while having the audio update loop (in whatever thread it lives) peek&poll it.

**Pull request closed without merging**
