### PR TITLE
Add method to calculate intersection point between three planes

### LINKED ISSUE #6214: [Enhancement] Intersection between three planes
This one can be assigned to me. It would be extremely helpful to allow visualization of some methods in Intersector (since it can be used to render frustum as a mesh)

Example algorithm from [MonoGame](https://github.com/MonoGame/MonoGame/blob/master/MonoGame.Framework/BoundingFrustum.cs#L529) (MIT License)

```
Vector3 IntersectionPoint(ref Plane a, ref Plane b, ref Plane c)
{
    // Formula used
    //                d1 ( N2 * N3 ) + d2 ( N3 * N1 ) + d3 ( N1 * N2 )
    //P =   ---------------------------------------------------------------------
    //                             N1 . ( N2 * N3 )
    //
    // Note: N refers to the normal, d refers to the displacement. '.' means dot product. '*' means cross product

    Vector3 v1, v2, v3;
    float f = -Vector3.Dot(a.Normal, Vector3.Cross(b.Normal, c.Normal));

    v1 = (a.D * (Vector3.Cross(b.Normal, c.Normal)));
    v2 = (b.D * (Vector3.Cross(c.Normal, a.Normal)));
    v3 = (c.D * (Vector3.Cross(a.Normal, b.Normal)));

    Vector3 vec = new Vector3(v1.X + v2.X + v3.X, v1.Y + v2.Y + v3.Y, v1.Z + v2.Z + v3.Z);
    return vec / f;
}
```

Reference: https://stackoverflow.com/a/28995460

### PR DESCRIPTION
**Pull request by yuripourre**
This PR simply adds a method to calculate the intersection point between three planes.

Returns false if there is no intersection or the intersection is not a point.
Returns true if there is an intersection point.

This post might help to illustrate the math behind it: http://geomalgorithms.com/a05-_intersect-1.html

I need this code (among other reasons) to prove with images that the PR #6086 is not breaking anything and is doing the same calculation as before.

**Tags**
- Non breaking changes
- Math

Closes #6214

### CODE REVIEW

**Comment by yuripourre** [comment]
@NathanSweet @mgsx-dev
Hey, if you have some time, can you please review?

**Comment by mgsx-dev** [comment]
@yuripourre no need to mention MonoGame in the code since it's now based on the article you linked here (no need to put article link in the code neither ;-) )
Except that, it looks good to me.

**Comment by yuripourre** [comment]
@mgsx-dev thanks for reviewing it, I just removed references to MonoGame

**Review by mgsx-dev — APPROVED** [review]
Nice! it looks good to me.

**Comment by yuripourre** [comment]
@NathanSweet thanks!!

**Pull request merged**
