### PR TITLE
Fix Mp3 Music setPosition works wrong #6628

### PR DESCRIPTION
**Pull request by HydrolienF**
setPosition for MP3 musics wasn't setting time position at the rigth place.

**How to test this fix ?**
You can see that this fix work by running `.\gradlew launchTestsLwjgl3` then choose MusicTest, play the mp3 file go to aproximatly 3:00. File is 3:03 min long, so it should stop at 3:03, but currently it continue over 3:10. (This fix make it stop at 3:03)
You can play file with a music player at libgdx/tests/gdx-tests-lwjgl3/build/resources/main/data/8.12.mp3 at 3:00 music fall down then stop at 3:03

**How does it fix it ?**
My guess is that mp3 reader don't fill buffer as wav & ogg do.
So to calculate how much of the file have been read we need to use the return of read(int) instead of bufferSize. Otherwise we think that 40960 have been read when only 40200. So wrong offset increase over time.

### CODE REVIEW

**Comment by HydrolienF** [comment]
Can I do someting else to help this merge request being merge ?

**Comment by Frosty-J** [comment]
Probably not. I see no issues with this but I don't have the required permissions to do anything that'll get it merged faster. Even small pull requests (such as this one) can easily take months in these parts. If you need this fix for a project of your own, best build it against your own fork for the time being.

**Comment by HydrolienF** [comment]
Great idea, I will use my own libgdx patched version for now.

**Review by SimonIT — DISMISSED** [review]
Works (from what I've tested)

**Review by crykn — CHANGES_REQUESTED** [review]
Could you add the same change to the `OpenALMusic` class in the old LWJGL backend as well?

**Comment by HydrolienF** [comment]
@crykn same fix apply for LWJGL.

**Review by crykn — DISMISSED** [review]

**Pull request merged**
