### PR TITLE
Fix json validity and missing section in the uiskin.json

### PR DESCRIPTION
**Pull request by ncareau**
I edited both uiskin.json present in the repo to be valid JSON. Double quotes everywhere and remove trailing comma.  

You can see that even github had trouble parsing it : https://github.com/libgdx/libgdx/blob/055b9f762e90303d3d5367b2e974bbaf595a7c64/extensions/gdx-tools/assets/uiskin.json

Also added the tooltip section to the gdx-tools/assets/uiskin.json file.

### CODE REVIEW

**Comment by Darkyenus** [comment]
libGDX uses custom lightweight JSON-like format so it is not wrong as it is. If we want to use the standard format is a different question though and depends on the original reason to use the current, simplified, format.

**Comment by ncareau** [comment]
I understand, Is there somewhere i could read up on the format used ?

However, wouldn't it be better if the format was JSON valid ? Both IDE and custom script could be used to read and modify the file. (ex, i could use custom python or whatever else to generate a new file).

**Comment by Darkyenus** [comment]
> [The Json class can write and read both JSON and a couple JSON-like formats. It supports "JavaScript", where the object property names are only quoted when needed. It also supports a "minimal" format (the default), where both object property names and values are only quoted when needed.](https://github.com/libgdx/libgdx/wiki/Reading-%26-writing-JSON)

I agree that the minimal format may not be necessary, but it is already widely used. In any case, only core contributors can correctly decide this, as I am not familiar with all reasons for introducing this format in the first place.

**Comment by ncareau** [comment]
Thanks for the comment. 

I will just add that for me (and probably a lot of new libgdx users) having a valid JSON from the libgdx repo would be easier to pickup the scene2d UI stuff. A non valid JSON is prone to errors since the IDE cannot check for validity and no code completion is available. 
Just my 2c.

**Comment by obigu** [comment]
Same as @ncareau I also find this a bit confusing as my IDE also highlights syntax errors on uiskin.json. 

I can see the potential benefit of using a lightweight custom serialization format but if it's not valid JSON  then it's not JSON (even if it's similar) and it should probably not have the .json extension.

**Comment by Scellow** [comment]
I agree with everyone the current JSON format used makes it impossible to correctly manipulate it from an IDE, or JSON editor/linter

The skin file is only loaded once, i wonder why the team decided to use a non standard format..

**Comment by MobiDevelop** [comment]
You are, of course, welcome to format your own skin files any way you like. If proper json is your desire, by all means use it. The test uiskin is a test asset, for some reason people think of it as a "default" skin.

**Comment by ncareau** [comment]
> Skin files from the libgdx tests can be used as a starting point. 
From the Wiki/Skin page. And google points to these files when I search for "default skin.json".

Would a possible solution be that we add a default skin in the library or wiki ?

**Comment by cypherdare** [comment]
@Tom-Ski I'm pretty sure this can be closed, as there is no bug, and LibGDX accepts valid JSON if you want to use the IDE's JSON review.

**Pull request closed without merging**
