### PR TITLE
Replace unmaintained support libraries with new androidx

### LINKED ISSUE #5393: AndroidFragmentApplication.java with AndroidX Not compatible
This class [AndroidFragmentApplication](
        libgdx/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
      ) use android support library internally but now google forcing us to build your application to target API  **28** , so we have to use AndroidX for this.

AndroidFragmentApplication.java is not compatible with AndroidX.

Please update AndroidFragmentApplication.java to work with AndroidX or I would generate a Pull request.

Thank you

### PR DESCRIPTION
**Pull request by SimonIT**
This PR replaces the old unmaintained android support libraries with the new androidx replacement. This is also a split up of my big PR #5846. It fixes #5393.

I added these many jar files, because libgdx gets deployed via maven and the aar dependencies of android aren't compatible. So I had to extract the jar files of them.

### CODE REVIEW

**Comment by lastpeony** [comment]
how do i use this right now in my android application ? i install libgdx right now from gradle with implementation ....

**Comment by noblemaster** [comment]
This looks good! Makes sense to upgrade to AndroidX. Unless there are objections, let's merge?

**Comment by noblemaster** [comment]
@SimonIT If this is ready, would you mind updating the CHANGES file also and we get this added? - Thanks!

**Comment by SimonIT** [comment]
I hope the text is fine

**Comment by noblemaster** [comment]
Great, Thanks! :)

**Pull request merged**
