### PR TITLE
Include dependencies count when reporting asset manager progress.

### PR DESCRIPTION
**Pull request by lnr0626**
This makes it so that when an asset has dependencies, the getProgress() call reflects the actual process for loading the assets. 

I'm not sure if it was created this way intentionally, but in my mind this gives a more accurate indication of the load progress than how it currently is. This can however make the percent completion go backwards at times (which I guess could be why it is the way that it currently is...). If this is an issue for including this change, I'll look into fixing it.

### CODE REVIEW

**Comment by NathanSweet** [comment]
See here:
https://github.com/libgdx/libgdx/issues/2714#issuecomment-68799514

**Comment by lnr0626** [comment]
Thanks for the quick response. I'll see if I can come up with anything for getting around that.

**Comment by NathanSweet** [comment]
Unless you know all the assets up front, I don't think there is much we can do. Some assets need to do loading just to know what other assets they depend on (eg, a texture atlas has to parse the atlas file to know what images it needs). As the developer, likely you know what assets you need, so you can just add them all to the asset manager.

Probably the easiest solution is to run you app and note the number from `getLoadedAssets`. If that value is `x`, you can use `getLoadedAssets() / x` to get a percentage that considers all assets that will be loaded.

**Comment by lnr0626** [comment]
There is not a way to accurately give a progress percentage without knowing the number of assets up front, however there should be a way to take into account the number of dependencies loaded using the tasks stack. I've been playing around and have gotten something that works doing this - just pushed it.

**Comment by NathanSweet** [comment]
What is this doing exactly?

**Comment by lnr0626** [comment]
```
int tasksLength = tasks.size();
float completedProgress = loaded / (float) toLoad;
```
`completedProgress` is the percent of requested assets which have been fully loaded - it's what is currently being returned.

The next bit is the estimation for the progress of the asset which is currently being loaded. If the length of the stack named `tasks` is greater than 1, it means that the dependencies for this task are currently being loaded (or at least that was what I was able to determine). If that's the case, then the progress is estimated as .9 / the number of tasks (which is roughly the number of dependencies to load + 1). 

If the tasksLength is equal to 1, then that could that either the asset task has not yet attempted to inject the dependencies for that asset, or that all of the dependencies have been loaded. To determine which one is the case, I had to add a dependenciesInjected variable. This defaults to false and is set to true once the dependencies for that asset have been injected into the AssetManager.

If the dependencies have already been injected, and the size of `tasks` == 1, that means that all of the dependencies have been loaded, so we use .9 as the progress estimation for the current asset. if the dependencies have not yet been injected, then the progress is estimated as 0.

The progress for the current asset is divided by the number of assets to load to calculate how much to add to `completedProgress` to estimate the actual current progress.
```
float progressForCurrentAsset = 0;
if(tasksLength > 1) {
	progressForCurrentAsset = 0.9f / (tasksLength * toLoad);
} else if(tasksLength == 1) {
	AssetLoadingTask task = tasks.peek();
	if(task.dependenciesLoaded || task.dependenciesInjected) {
		progressForCurrentAsset = 0.9f / toLoad;
	}
}
return Math.min(1, completedProgress + progressForCurrentAsset);
```

**Comment by NathanSweet** [comment]
It's not clear to me how this affects the progress bar and I don't have a setup to test it. I expect it will still go backwards?

If we want to loading dependencies to be reflected in the progress, we could have the "tasks" increase `toLoad` and `loaded`. However, doing that means the progress goes backward:

```
2 assets queued to load
loading 1 0%
loaded 1 50%
loading 2 50%
adds 1 dependency 33% <- backward!
loading dependency 33%
loaded dependency 66%
loaded 2 100%
```

Going backward is suboptimal for a progress bar, in that case you might as well display an indeterminate progress animation. I still contend the best solution is to know how many assets will be loaded beforehand.

**Comment by lnr0626** [comment]
It doesn't go backwards. Given:
 assets (A, B, and C), A has 0 dependences, B has 2

It would look like:
```
2 assets queued to load
loading A 0%
loaded A 50%
loading B 50%
adds 2 dependencies
loading dependency 65%
loaded dependency 80%
loading dependency 80%
loaded dependency 95%
loaded B 100%
```

I'm not sure if the numbers are exactly correct, but that is the general trend that you would see. I can get some actual numbers for you later today if you would like that.

**Comment by badlogic** [comment]
Closing this as it fizzled out and is an application level issue really.

**Pull request closed without merging**
