### PR TITLE
AnimatedMapTile - Getter and Setter fot animationIntervals

### PR DESCRIPTION
**Pull request by JoEschner**
to change the animation speed in runtime

### CODE REVIEW

**Comment by MobiDevelop** [comment]
Thanks

**Comment by JoEschner** [comment]
Nice! Thanks for merging. Will be very useful for me.

**Comment by MobiDevelop** [comment]
Whoops... Your change didn't compile, the new methods shouldn't have had override annotations. I've removed the annotations and started another build.

**Comment by JoEschner** [comment]
Oh.. yeah makes sense. Should have seen this.

**Pull request merged**
