### PR TITLE
ShapeRenderer check () method as protected visibility 

### PR DESCRIPTION
**Pull request by fabiitch**
void check (ShapeType preferred, ShapeType other, int newVertices)

### CODE REVIEW

**Comment by mgsx-dev** [comment]
What's the use case? i can't see a reason why some may want to override it. Also, most of fields used in this method are private.

**Comment by fabiitch** [comment]
hey, its for extends ShapeRenderer. My use case is to draw Filled triangles.

I need to call check() method before use Renderer. 
like 
`public void triangle(Triangle triangle){
super.check(ShapeType.Line, ShapeType.Filled, 6);
//draw
`

**Comment by mgsx-dev** [comment]
Ah yes, my bad, it's totally legit. Could you please make it `final` as well, because there is no reason to override it.

**Comment by fabiitch** [comment]
Sure, thx for your feedback

**Comment by MobiDevelop** [comment]
Feels like the doc in that method needs improvement if it is going to become API.

**Comment by crykn** [comment]
I agree, maybe add a small comment like: `Checks whether the correct ShapeType was set. If not and autoShapeType is enabled, it flushes the batch and changes the shape type. The batch is also flushed, when the matrix has been changed or not enough vertices remain.`

**Comment by fabiitch** [comment]
hey , i do it soon !

**Review by MobiDevelop — APPROVED** [review]

**Pull request merged**
