### PR TITLE
fix wrong firstgid when load external tileset

### PR DESCRIPTION
**Pull request by bachtrong43**
#5710 didn't really fix the issue #5709 if map uses external tsx tileset. In this case the tileset element in tmx file only has two attributes firstgid and the source to the tsx. All tileset attributes like name,tilewidth,tileheight,... are defined in tsx file.

### CODE REVIEW

**Comment by TCreutzenberg** [comment]
Thank you very much!

**Comment by bachtrong43** [comment]
> There are some formatting issues. Please use tabs instead of spaces.

done!

**Comment by Darkyenus** [comment]
@bachtrong43 Just a heads up - it looks like you have accidentally pushed unrelated commit onto this branch. Usually you want to create a new branch for each new pull request.

**Comment by bachtrong43** [comment]
That's my fault, I will delete last commit

**Comment by kdenzel** [comment]
One Question, i tried to get this fix via https://jitpack.io/#bachtrong43/libgdx. When trying to get the newest snapshot. 

Get the following Error https://jitpack.io/com/github/bachtrong43/libgdx/master-gdx-parent-1.9.10-g9887192-8/build.log . How can i get this fix into my Project?

**Pull request merged**
