### PR TITLE
Add support for selecting extensions through command line

### PR DESCRIPTION
**Pull request by Fr0sk**
Together with my last pull request, this would help integrate LibGDX with other tools or game engines even further. If no extension is provided then it would have the default behaviour, so wouldn't break existing setups.

### CODE REVIEW

**Comment by Fr0sk** [comment]
About this change and also the last one I made, #3849, when should I (or anyone for that matter) make the changes to the [Wiki page](https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle)?

**Comment by MobiDevelop** [comment]
Generally speaking, once a change is merged that warrants an update to the wiki, the person who made that change should go update the wiki soon after.

**Comment by Fr0sk** [comment]
Even if the changes are not available for the user? I mean, the updated setup is not available to download yet. If so, I would make the changes right away

**Comment by MobiDevelop** [comment]
The updated setup is immediately available to users.

**Comment by Fr0sk** [comment]
I may be doing something wrong, but I downloaded the gdx-setup.jar and it has not the new arguments implemented.

**Comment by MobiDevelop** [comment]
Looks like the build has been hanging for a day or two.

**Comment by Fr0sk** [comment]
Ok, I'll wait until the build comes out and make the changes to the wiki page. Thank you for your time and help :)

**Comment by Tom-Ski** [comment]
Thanks!

**Pull request merged**
