### PR TITLE
Add handling of <objectgroup> in <tile> in the com.badlogic.gdx.maps.tiled package

### PR DESCRIPTION
**Pull request by TheoKah**
Since version 0.10 of Tiled, _objectgroup_ blocks can be found in _tile_ blocks.

http://doc.mapeditor.org/reference/tmx-changelog/
http://doc.mapeditor.org/reference/tmx-map-format/

This is where custom collision shapes are stored on tiles. The libgdx implementation just ignored those blocks.

This commit ads a _getObjects()_ method on _TiledMapTile_ interface.

I had to change the _BaseTmxMapLoader_'s _loadObject_ signature in order to avoid code duplication and reuse the existing object parser.

### CODE REVIEW

**Comment by badlogic** [comment]
This looks good to me, @MobiDevelop what do you say?

**Comment by TheoKah** [comment]
I found a little 'bug':

The `loadObject` method translates **y** coordonate from tiled to gdx:

BaseTmxMapLoader line 177:
> float y = (flipY ? (mapHeightInPixels - element.getFloatAttribute("y", 0)) : element.getFloatAttribute("y", 0)) * scaleY;

In order not to mess up the code logic, i'll switch back this function signature to only handle *MapLayer*'s `<objectgroup>` and create an other one for within the `<tile>`

The new one will be simpler as it does not need to handle as much things as the *MapLayer*'s one (there won't be `<tile>` in there for instance)

commit incomming

**Comment by TheoKah** [comment]
Good news everyone !
Didn't had to duplicate code.

**Comment by gammons** [comment]
Adding a +1 here for support of this.  Tiled 0.10 was released September 2014.  Currently libgdx (as far as I know) does not support collision maps at the tile level.  It only supports it at the layer level.  

It has caused developers to abandon using tiled to set collisions at the tile editor, instead [writing their own](http://stackoverflow.com/questions/18039781/collision-detection-tmx-maps-using-libgdx-java) collision handling.  

I personally ran against this and was surprised to see that libgdx does not support this.  This PR looks like it will do the job!

**Comment by xSke** [comment]
+1.

Any update on this? Would be really useful.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://andrea-mayerhofer.com/supply.php?hpqx>

 

loogie@basicelementdesign.com

**Comment by intrigus** [comment]
Looks good to me, could you please add a note to the CHANGES file?
A little test that shows the new functionality would also be nice :)

**Comment by TheoKah** [comment]
It's been more than 4 month since I forked.
Should I update my repository to current version or just add a line on top of the CHANGES file and you moves it when you merge ?

**Comment by intrigus** [comment]
I'd update the repository to the current version :)

**Comment by TheoKah** [comment]
Done.

I don't have time to make a test showing it right now.
I'll do it asap. If this PR is not merged when I'm done, i'll push the test here. Otherwise, i'll make a new PR for the tests.

**Comment by j-hiden** [comment]
I know this PR its been around for while now but it would be really useful to have in place. Any upadtes on the status of this? #4247 would also be handy :)

**Comment by KenRud** [comment]
Can we get this merged in? It's been sitting here unnecessarily for some time now. If no one has the time then I will gladly clone the changes and send a PR myself.

**Comment by phunni** [comment]
Is this merged in? I'd love to see this functionality added to libgdx.

**Comment by nanodeath** [comment]
👍 This would be a great feature to get merged in. Anything we onlookers can do to help?

**Pull request merged**
