### PR TITLE
Add wrapper class for btActionInterface

### PR DESCRIPTION
**Pull request by floralvikings**
See #4022 

The first commit contains the non-generated files; `CustomActionInterface.h` wraps the btActionInterface C++ class and the changes to `dynamics.i` include this new class and specify it as a director class.

The second commit is the regeneration of the swig source files; swig 3.0.8 was used, most of the changes are just updates to the version number in the leading comment.

### CODE REVIEW

**Comment by xoppa** [comment]
Can you remove (`%ignore` iirc) the old signature and debug drawer method from swig, so it never has to create those objects?

This change doesnt allow to customize `btKinematicCharacterController` though, which was the initial use-case you provided. Can you provide a new use-case or perhaps include one in the tests so others can see how to use it?

**Comment by floralvikings** [comment]
I've added `%ignore` directives for those two methods.

The basic use case for overriding this class is to hook into the `stepSimulation` method of a `btCollisionWorld`, after collision checks have been made but before the motion states have been synchronized.  I'm using it to add listeners to respond to a few specific collisions, but basically anything that would benefit from hooking into that part of the world simulation.

As far as customizing `btKinematicCharacterController`: my initial thought here was to write my own implementation tailored more closely to my project, so customizing it wasn't really the idea so much as reimplementing.  If you think that would be a useful addition, though, I can add swig directives for it and make it extensible as well

**Comment by xoppa** [comment]
Looks like the `debugDraw` is still included. Better implement it to prevent a pure virtual function as well. Perhaps you can do the same thing for that method as well, so that it meets the API as much as possible. Thus, make it call a new `virtual void debugDraw() {}` method (without any arguments, with default empty implementation). Let's not include directors unless there's at least one use-case, so no need to add one for `btKinematicCharacterController` as well.

**Comment by floralvikings** [comment]
Done.  Thanks a lot for helping get this together, by the way, I really appreciate it 😄

**Comment by floralvikings** [comment]
@xoppa does this still need some work?  Just let me know if it needs more tweaking.

**Comment by xoppa** [comment]
Thanks!

**Pull request merged**
