### PR TITLE
Nullability annotations for base scene2d classes

### PR DESCRIPTION
**Pull request by maltaisn**
I added `@NotNull` and `@Nullable` annotations to base scene2d classes as discussed in #5599. I chose `org.jetbrains:annotations` but it can easily be changed. 

Parameters that I wasn't sure about have a `/* FIXME not sure */` comment next to them.

This pull request is for review, don't merge it.

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Did you check GWT compatiblity?

**Comment by Darkyenus** [comment]
These annotations are source only, so unless GWT has a really bad parser, it should work.

**Comment by MrStahlfelge** [comment]
The GWT parser needs to see the sources. I can't see that you added the sources, and I can't see that you added the GWT inherits flag. In my experiences, this is often needed for such changes and I had problems with GWT myself when I added Nullability annotations in my projects. 

So I am not sure if you checked the compatiblity but just guessed that there should be no problems.

**Comment by maltaisn** [comment]
I just added `compile 'org.jetbrains:annotations:16.0.2'` to base gradle script (and forgot to commit it). Do I also need to add the annotation classes to [gdx.gwt.xml](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx.gwt.xml)? I didn't manage to run the gwt test suite on IntelliJ so I couldn't check.

**Comment by SimonIT** [comment]
For my surprise run the tests without any additional addition in gwt

**Comment by maltaisn** [comment]
Does that mean it works with GWT? Should I continue adding the annotations?

**Comment by SimonIT** [comment]
Yes, it works (if I did nothing wrong)

**Comment by maltaisn** [comment]
I finished adding nullability annotations for `gdx.scenes.scene2d` package. 
I think Scene2d was probably the hardest part to add annotations for, the rest should
be pretty straightforward. Some notes:

- Late initialized fields were not annotated as nullable. 
  
  For example, `Actor.setStage`, `Event.setTarget`, `Action.setTarget` are
  not annotated. In the same way, style classes fields set by reflection are not nullable
  if they are required: `LabelStyle.font` is not annotated because it's required,
  but `LabelStyle.fontColor` is nullable.
  
  These fields are null when uninitialized but most of the time they aren't,
  so being nullable would only be a nuisance.
  
- All non-final and non-null fields were annotated as not null. Final fields
  initialized outside the constructor were not annotated since their nullibility is obvious.
  
- Private, package private and public methods were all annotated the same.
  
- When possible, fields were annotated. For example:
  ```java
  @NotNull private Touchable touchable = Touchable.enabled;
  ```
  Since the field is initialized directly and not in constructor, it can
  be marked as not null without creating a warning "`@NotNull` fields must be initialized".
  However:
  ```java
  private LabelStyle style;
  ```
  Cannot be annotated without creating a warning, since it's initialized in constructor.
  Getters and setters are still annotated as usual since field is really not null.
   
- Methods returning `this` were never annotated as `@NotNull` since it's obvious.

- `assert variable != null` was used at some places to prevent warnings.

- Null checks were always kept, since `@NotNull` does no runtime checking.

- To prevent some warnings, methods like `Table.requireCell` 
  or `ArraySelection.requireSelected` could be added to throw an exception 
  if result is null. (which is never supposed to happen) This is how Android does it.

I found some code issues on my way:
- Some return values and method parameters had a "May be null" message
  in javadoc, although they weren't. For example primitive values or
  values for which a null value would immediately cause a NPE. (fixed)
- `ListStyle`, `TextTooltipStyle` and `TreeStyle` 
  copy constructors don't copy all fields. (not fixed)
- Unnecessary instanceof in `Slider.setStyle`, `Skin.newDrawable` and
  `TextTooltip.setStyle`. (not fixed)
- Very inconsistent use of `@Override`, not sure if this is intended or not. (not fixed)
- Some toString methods can return null, like `BaseDrawable.toString`. (not fixed)

**Comment by maltaisn** [comment]
@NathanSweet Any update on this?

**Comment by RUSshy** [comment]
On top of that, i think adding ``@Override`` attribute everywhere method is overwritten will help too, blind overwritting is bad, it is even more bad for public APIs

**Comment by NathanSweet** [comment]
@maltaisn Sorry for not being able to look at your PR sooner.

I'm not excited about adding an new dependency. Is it possible to host our own @NotNull and still have IDE integration?

I would still like to apply the annotations to a personal project before deciding on scene2d. I haven't gotten to do that yet. From only looking at your PR, I don't hate `@Nullable`.

I think that fields that are assigned in constructors should have the annotation. If that causes a warning, just turn the warning off. The annotation is a tool for application code, we can assume library code works correctly.

What was `@NotNull` added? Everything should be considered as not being null unless it has `@Nullable`.

`Skin.newDrawable` and `BaseDrawable.toString` look OK. The other items have been fixed, thanks!

@RUSshy This has been discussed before, and to death. PRs to add `@Override` won't be merged. It makes sense for application code. It isn't required for library code, where it just adds noise and the benefits for refactoring are insignificant.

**Comment by Darkyenus** [comment]
> What was @NotNull added? Everything should be considered as not being null unless it has @Nullable.

IIRC that can be done by annotating the whole class as `@NotNull`, which would be a nice compromise, since otherwise IntelliJ would consider those fields as "unknown nullability" and not provide any warnings on e.g. unnecessary null checks.

**Comment by NathanSweet** [comment]
`@NotNull` seems nasty. Annotations make sense for something that is abnormal. I would not want extraneous annotations all over the place for the common case where things are not null.

**Comment by maltaisn** [comment]
> I'm not excited about adding an new dependency. Is it possible to host our own @NotNull and still have IDE integration?

Yes this is possible with both Eclipse and IntelliJ, although I recommend sticking with the `org.jetbrains.annotations` dependency since they are set by default in IntelliJ which I believe is what most people use. It's a compile time only dependency so there shouldn't be any problem.

> I think that fields that are assigned in constructors should have the annotation. If that causes a warning, just turn the warning off. The annotation is a tool for application code, we can assume library code works correctly.

Sure that makes sense, I can make the changes.

> What was `@NotNull` added? Everything should be considered as not being null unless it has `@Nullable`.

> `@NotNull` seems nasty. Annotations make sense for something that is abnormal. I would not want extraneous annotations all over the place for the common case where things are not null.

Each annotation is as useful as the other and each provide their own warnings. Without the `@NotNull` annotation, you don't get any warning when passing a null or a nullable value to an argument that shouldn't be null.

Yes, it does make the code more verbose. But it's also more maintainable, eg: you won't have to look all over the place every time you wonder if a value is nullable or not. The same goes with `@Override`, but that's not the question here.

**Comment by NathanSweet** [comment]
> this is possible with both Eclipse and IntelliJ, although I recommend sticking with the org.jetbrains.annotations dependency since they are set by default in IntelliJ which I believe is what most people use.

I could go either way. FWIW, I don't use IntelliJ.

> Each annotation is as useful as the other and each provide their own warnings. Without the @NotNull annotation, you don't get any warning when passing a null or a nullable value to an argument that shouldn't be null.

Is there no IDE setting to assume not null when there is no annotation? If not, why? I could see it causing a lot of warnings where @NotNull has not been fully embraced, but otherwise would be better.

> Yes, it does make the code more verbose. But it's also more maintainable, eg: you won't have to look all over the place every time you wonder if a value is nullable or not. The same goes with @Override, but that's not the question here.

There is no wondering: if something has `@Nullable` then it can be null, if it doesn't then it can't be null. The most common case is not null. Using an annotation for the most common case would add a lot of clutter.

**Comment by maltaisn** [comment]
See #5812 for the updated pull-request.

**Pull request closed without merging**
