### PR TITLE
Added Consistency.

### PR DESCRIPTION
**Pull request by tsteinholz**
You can see the changes I made in the request, i personally think that the method should not be called "scl" but I don't want to be repsonsible for a refactor like that. Anyways, just fixed some O.C.D things in the GitHub editor. I didn't actually change any functionality so no worries there.

### CODE REVIEW

**Comment by NathanSweet** [comment]
I don't see how these changes are useful.

**Comment by badlogic** [comment]
Agreed. Also, we don't merge changes made via the web editor.

**Comment by tsteinholz** [comment]
How come? @badlogic 
And @NathanSweet as I stated it does not change any functionality, only adds coding consistency which is a better practice.

**Comment by MobiDevelop** [comment]
Merging changes made in the web editor generally breaks the build, so as a general rule we try to avoid them.

**Comment by badlogic** [comment]
Thomas, appreciate the thought, but we are closing this out now.

**Comment by tsteinholz** [comment]
Alright @MobiDevelop , I will try this again in IntelliJ. I was just trying to be lazy w/ the editor.

**Comment by badlogic** [comment]
Please don't bother redoing this in IDEA, we'll not merge it.

**Comment by NathanSweet** [comment]
`this.` is only needed to remove ambiguity between a field and local. `x vs `scalarX` doesn't tell me anything more about `x`. `Vector2 v`, while a single letter is usually not a great name, is not improved by calling it `Vector2 vector2`.

Submitting PRs are great, but these changes are not useful. They only serve to waste time for us to review.

**Pull request closed without merging**
