### PR TITLE
Fix Intersector#overlapConvexPolygons

### PR DESCRIPTION
**Pull request by schosin**
In some rare cases it's possible that Intersector#overlapConvexPolygons calculates an incorrect MTV. Currently the direction of the MTV is negated depending on the number of points on either side of the checked edge. 

The correct way is to negate the direction of the MTV depending on the direction of the centers of both polygons.

### CODE REVIEW

**Comment by obigu** [comment]
I think your fix doesn't work for other cases. Imagine a right triangle (1 angle is 90º) with 2 equal sides resting on one cathetus (short side). The center point of that triangle will be in the middle of the hypotenuse. Imagine now a small rectangle with the same center than the triangle. If I understand your fix correctly in that case MTV will resolve to 0. Now, imagine we move the rectangle diagonally up-right or down-left the MTV will invert but it actually should keep being positive x and y. I think it's a complex geometry problem with complex corner cases.

**Comment by kdenzel** [comment]
So i had also issues with the function `overlapConvexPolygons` and i decided to understand the SAT Algorithm and how to handle the minimum translation Vector. I am making a game and completely did a rewrite on this function. If anyone is interested in seeing it [here is the link](https://github.com/kdenzel/BloodHunger/blob/master/core/src/de/kswmd/bloodhunger/math/Intersector.java). If you want, you can clone the repository and play with the Testclasses i made. Try changing my custom Intersector class with this of libgdx and you will see the issues with it. I made a Testclass where you can drag 2 triangles to overlap each other and when they collide, the minimum translation vector did return wrong results because the orientation of the x and y coordinates returned by the direction vector were wrong.

**Comment by obigu** [comment]
> So i had also issues with the function `overlapConvexPolygons` and i decided to understand the SAT Algorithm and how to handle the minimum translation Vector. I am making a game and completely did a rewrite on this function. If anyone is interested in seeing it [here is the link](https://github.com/kdenzel/BloodHunger/blob/master/core/src/de/kswmd/bloodhunger/math/Intersector.java). If you want, you can clone the repository and play with the Testclasses i made. Try changing my custom Intersector class with this of libgdx and you will see the issues with it. I made a Testclass where you can drag 2 triangles to overlap each other and when they collide, the minimum translation vector did return wrong results because the orientation of the x and y coordinates returned by the direction vector were wrong.

On a first look it looks a good. I think we  can use your SAT algorithm implementation as a base to replace the current buggy implementation. I think there's a some room for improvement (such as using `Vector2` for some operations) but I'd rather discuss them on a PR. Would you like to create a PR with your implementation including some non visual/interactive tests that also cover corner cases (such as containment)?

**Comment by MrStahlfelge** [comment]
Now that we have #5048, can we close this one?

**Comment by obigu** [comment]
It will get closed when the PR is merged and closed.

**Pull request closed without merging**
