### PR TITLE
Added contains to Shape2D.

### PR DESCRIPTION
**Pull request by nooone**
This is the PR for https://github.com/libgdx/libgdx/issues/2880.

Polyline is no Shape2D anymore and `Shape2D` now has two methods `contains(float x, float y)` and `contains(Vector2 point)`.

### CODE REVIEW

**Comment by MobiDevelop** [comment]
I personally consider Polyline a shape, just not an enclosed shape.

**Comment by nooone** [comment]
That means the next logical OOP step is to introduce `EnclosedShape`?

**Comment by MobiDevelop** [comment]
Or, more simply, let Polyline return false from the contains method if it
can't contain a point.

**Comment by nooone** [comment]
To keep it simple, I did it like that.

**Comment by cypherdare** [comment]
Any reason Polygon can't extend Polyline? Looks to me like it simply enforces one more vertex, and there's a lot of copy-pasted code between the two.

**Comment by xoppa** [comment]
Thanks @nooone! I think the shape discussion goes beyond the `contains` method. But until someone is going to pick that up, I guess it doesn't harm to move the `contains` method to an interface. Although it might be better when it's moved to its own interface, I don't think that's worth it. So, unless someone is against it, I'd say let's merge it and move on.

**Comment by nooone** [comment]
I don't think that the guy who wanted this change still needs it, since it's 7 months ago by now.

Merge or close?

**Pull request merged**
