### PR TITLE
Add useful method

### PR DESCRIPTION
**Pull request by VinceAngel**
Useful method to manage quote replacement in paths

### CODE REVIEW

**Comment by jsjolund** [comment]
Maybe you could provide a use case for the method? Also, your code is not correctly formatted:
https://github.com/libgdx/libgdx/wiki/Contributing#eclipse-formatter

**Comment by VinceAngel** [comment]
This method is missing since it's in the jdk but not in gwt backend.

**Comment by MobiDevelop** [comment]
Looks ok to me, one small optimization you could do is initialize the StringBuilder with a capacity at least the size of the string being passed in.

**Comment by VinceAngel** [comment]
Found this, I forget it for a while... still ready to be merged :)

**Pull request merged**
