### PR TITLE
Gradle 5.4.1

### PR DESCRIPTION
**Pull request by mr-gri3ves**
Gradle 5.4.1 update.

### CODE REVIEW

**Comment by SimonIT** [comment]
You don't have to close every PR, if you want to add new commits. Commits will be added automatically to the PR.

**Comment by mr-gri3ves** [comment]
Thanks for the hint, actually I am new to github)

**Comment by Tom-Ski** [comment]
Please update PR description with the platform and IDE combinations you have tried this on.

We need to make sure every backend works on every major IDE we support, which is at very least, Intellij and eclipse. Minimum is that all backends work on command line.

**Comment by dargonforce** [comment]
@mr-gri3ves are you still working on this?

**Comment by mr-gri3ves** [comment]
@dargonforce Hey, unfortunately I am very busy at the moment, I'll be freed from 2 weeks, and of course, I'll work on this issue.

**Comment by Tom-Ski** [comment]
see https://github.com/libgdx/libgdx/pull/5700

**Comment by Tom-Ski** [comment]
Thanks for your efforts @mr-gri3ves . I have updated master myself.

**Pull request closed without merging**
