### PR TITLE
Create Pixmap from video element on gwt

### PR DESCRIPTION
**Pull request by SimonIT**
You guys can surely guess why it's needed :)

### CODE REVIEW

**Comment by SimonIT** [comment]
Here a video that this change is working https://cdn.discordapp.com/attachments/348229413785305089/751348815910666260/LibGDX_application_-_Google_Chrome_2020-09-04_09-50-28.mp4

**Comment by mgsx-dev** [comment]
for reference, https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL

@SimonIT could you please format only your changes? i understand files wasn't properly formatted before but it'll mess with history. If we really want to fix formatting for some files, i think it should be done in a separated PR.

Other than that it looks good to me. Thank you for your work on gdx-video :-)

**Review by mgsx-dev — CHANGES_REQUESTED** [review]
please fix formatting :-)

**Review by MrStahlfelge — APPROVED** [review]
LGTM

**Pull request merged**
