### PR TITLE
Upgrade source compatibility to Java 7

### PR DESCRIPTION
**Pull request by obigu**
It should be safe now to upgrade source compatibility to Java 7 

Related https://github.com/libgdx/libgdx/issues/3244

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
It is safe. Should get merged.

**Comment by MobiDevelop** [comment]
It's only safe if minSdkVersion >= 19. Prior to 19, only language features are safe (as opposed to APIs).

**Comment by obigu** [comment]
> It's only safe if minSdkVersion >= 19. Prior to 19, only language features are safe (as opposed to APIs).

@MobiDevelop Could you please be specific about which APIs are not safe to use that require minSDK >= 19 using latest Android build tools?

**Comment by MobiDevelop** [comment]
@obigu Any classes or methods that were added in Java 7 are not safe. Only language features (e.g. diamond operators, string switch cases, multi-catch, and, more recently, try-with-resources) on Android versions lower than 4.4 (API 19).

That said, I think we may be nearing a time where we should stop supporting those old versions.

**Comment by obigu** [comment]
@MobiDevelop Oh, I see what you mean, yes, but I don't think that's an issue, not the whole Java APIs are supported anyway, not even from Java 5 :). IDEs (at least IntelliJ and AS) also help avoiding their usage with nice warnings.

To be honest, I think that's not a reason not to merge this, those APIs may never be implemented on Android.

I do agree with increasing the minSDK of libGDX, API 15 would already help us avoid some of the current "hacks".

**Comment by MrStahlfelge** [comment]
> That said, I think we may be nearing a time where we should stop supporting those old versions.

We should go to 15 or 16, as [Play Store is discontinuing support for older versions](https://android-developers.googleblog.com/2018/12/google-play-services-discontinuing.html). If you really have a game with a massive user base with older versions (tbh, I doubt that), than there is nothing wrong to just stay with an older libGDX version.

**Comment by obigu** [comment]
> > That said, I think we may be nearing a time where we should stop supporting those old versions.
> 
> We should go to 15 or 16, as [Play Store is discontinuing support for older versions](https://android-developers.googleblog.com/2018/12/google-play-services-discontinuing.html). If you really have a game with a massive user base with older versions (tbh, I doubt that), than there is nothing wrong to just stay with an older libGDX version.

I'd say 16 would be the right choice (if we are taking the decision to upgrade it makes sense to go in line with Google (the API 15 userbase is tiny and as you say it's always an option to use libGDX 1.9.9 that supports down to API 9).

**Comment by obigu** [comment]
Fixed in https://github.com/libgdx/libgdx/commit/1e82c12a4b5e2cfa552f5e806ed21eda56ff2243

**Pull request closed without merging**
