### PR TITLE
Gradle update project generator to version 5.4.1

### LINKED ISSUE #5238: Assets folder does not appear as source folder eclipse
#### Issue details
As the Gradle files stand, the assets folder is not automatically set as a source folder for the project. This can be fixed by adding it to the build path in eclipse however a gradle refresh puts the problem back.

#### Reproduction steps/code
jre version 9.0.4

Open gdx-setup.jar
untick android, ios and html
tick freetype
advanced ---> tick eclipse
generate

---- In Eclipse ----
Import ---> gradle ---> Existing gradle project
Finish
Run desktop as java application

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Stacktrace
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: badlogic.jpg
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:149)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:88)
	at net.thechubbypanda.larrysadventure.Game.create(Game.java:16)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: badlogic.jpg (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:146)
	... 7 more

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

### PR DESCRIPTION
**Pull request by Tom-Ski**
To be merged after release of 1.9.10.

Remove IDEA and eclipse plugins
Disable IOS-MOE

Auto hook up asset path for desktop distribution and eclipse assets.

Upgrade MobiVM to 2.3.7
Upgrade gwt plugin to 1.0.9
Update android gradle plugin to 3.4.1

Fixes #5238, #5491, #5523, #5566, #5664

### CODE REVIEW

**Comment by Tom-Ski** [comment]
We can sneak https://github.com/libgdx/libgdx/issues/4955 into this perhaps, as far as I can tell there is no way to run any native plugins for the IDE for android support, unless its some frankenstein build.  The only reason why #4955 was not possible was due to eclipse users and ADT, so if no one is using this anymore, its good to merge.

**Comment by lili2300** [comment]
I. Supposed to been training mode???? I ha e no idea what or where or why but I'm jumping in trying to learn what u guys are discussing because I have sales nailed just no clue what this stuff is which to me the gits the inward workings and or fixes of so.e sorts lol IDK but wanting and willing to learn thanks Lisa

**Comment by mgsx-dev** [comment]
@Tom-Ski eclipse project renaming was necessary in order to import multiple libgdx projects in the same workspace without conflicts which is pretty common for eclipse users. If you don't mind, it would be better to revert this part (eg. `eclipse.project.name = appName + "-core"` ).

**Comment by mustii82** [comment]
What about a Release?

**Comment by mustii82** [comment]
Why did we remove the MOE possibility?

**Comment by Tom-Ski** [comment]
As I mentioned on the forum:

Official MOE support has pretty much stopped as far as I can tell, our backend will continue to be released until it completely stops working, which is probably true for a lot of the core bindings already. The official plugin is already broken on the latest versions of IDE and updates for the repositories have gone completely stale.

MobiVM on the other hand is actively maintained and managed by us, and is the recommended way for deploying on iOS as we can actually provide direct support for it. If the community picks up MOE, then we can put it back in, but for now official support no new projects wont be there for MOE.

**Comment by MaanooAk** [comment]
> @Tom-Ski eclipse project renaming was necessary in order to import multiple libgdx projects in the same workspace without conflicts which is pretty common for eclipse users. If you don't mind, it would be better to revert this part (eg. `eclipse.project.name = appName + "-core"` ).

+1. After the merge we have to edit the build in order to make it possible to work in eclipse

**Pull request merged**
