### PR TITLE
gdx-lwjgl3-glfw-awt-macos extensions to add support for mixing GLFW and AWT on macOS

### PR DESCRIPTION
**Pull request by badlogic**
# What and why
GLFW and AWT both compete for the AppKit run loop. LWJGL3 apps on macOS thus need to specify the -XstartOnFirstThread JVM option. This prevents AWT (and by proxy Swing, ImageIO, etc.) from working together with LWJGL3 on macOS.

This commit injects a modified libglfw.dylib (see https://github.com/badlogic/glfw). The GLFW fork is modified such that all calls into AppKit APIs are expected to be performed on a thread != main thread. This way, AWT can take over the run loop, while GLFW (and libGDX LWJGL3) apps can live on a separate thread.

# Usage
To use this, add `gdx-lwjgl3-glfw-awt-macos` as a dependency to your libGDX desktop project. You can now use both libGDX and AWT/Swing/ImageIO on macOS.

Remove the `-XstartOnFirstThread` JVM option from your run configurations/packr'ed apps/bash scripts.

# Caveats
* This extensions does NOT allow rendering your libGDX content to an AWT/Swing window.
* This extension requires LWJGL 3.3.0-SNAPSHOT
* This PR builds on top of this PR https://github.com/libgdx/libgdx/pull/6672

### CODE REVIEW

**Comment by tommyettinger** [comment]
Hooray, no more `-XstartOnFirstThread`! Will this allow gdx-tools to move to LWJGL3? Last I heard, the only thing stopping gdx-tools from moving that way was its AWT and/or Swing usage.

**Comment by badlogic** [comment]
@tommyettinger no, I don't think this will help with all gdx-tools. I.e. Hiero is Swing based, rendering libGDX stuff directly into a JFrame. This extension does not allow that. But you can now use texturepacker in your LWJGL3 app on macOS. It would previously not work, as texturepacker uses ImageIO, which itself requires AWT, which deadlocks the run loop when used with vanilla GLFW.

**Comment by tommyettinger** [comment]
Well, it's still a lot better than deadlocking! I'm looking forward to LWJGL 3.3.0, it should make all of these changes feasible to use in a release.

**Comment by fgnm** [comment]
Hey @badlogic maybe I'm saying a stupid thing, but why TexturePacker cannot be used with current LWJGL3 and GLFW implementation on macOS?

I'm using many AWT classes (including TexturePacker and TextureUnpacker) without any issue on HyperLap2D, which is a 100% libGDX app running on current LWJGL3 backend... The only thing I've add is run AWT in headless mode (https://github.com/rednblackgames/HyperLap2D/blob/4a8214e1d44cf816745cec05b06346ceb90b9458/src/main/java/games/rednblack/editor/Main.java#L125)

This flag doesn't allow to render into a JPanel, but all utility classes I've used until now worked without problems 🤔

**Comment by siauderman** [comment]
Does not work. This is what I got
```
2021-12-30 17:37:12.925 java[1845:57615] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4c026f3b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff73383942 objc_exception_throw + 48
	2   AppKit                              0x00007fff49cc5297 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4167
	3   libosxapp.dylib                     0x000000010f075699 -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	4   libglfw.dylib                       0x00000001145d68cf libglfw.dylib + 100559
	5   ???                                 0x000005a9596bddf7 0x0 + 6224907853303
)
libc++abi.dylib: terminating with uncaught exception
```

**Comment by badlogic** [comment]
That's not enough information. Please tell me your macOS version, your hardware specs, what the app you wrote does, preferaboy sharing code that lets me reproduce the issue, and what steps you took (window resize/move, clicks, key press, etc.) so this happened.

**Comment by siauderman** [comment]
Running on High Sierra, MacBook Pro (quite old)
Basically crashes on start. Relevant code is here:
```
public class Lwjgl3Launcher {
	public static boolean maximized=true;
	public static void main(String[] args) {
		createApplication();
	}

	private static Lwjgl3Application createApplication() {
		TuxFight tuxFight=new TuxFight();
		tuxFight.loaderUtils=new JarUtils();
		return new Lwjgl3Application(tuxFight, getDefaultConfiguration());
	}

	private static Lwjgl3ApplicationConfiguration getDefaultConfiguration() {
		Lwjgl3ApplicationConfiguration configuration = new Lwjgl3ApplicationConfiguration();
		configuration.setTitle("TuxFight");
		configuration.setMaximized(true);
		configuration.setWindowIcon("resources/images/icon_desktop_128.png");
		configuration.setWindowListener(new Lwjgl3WindowAdapter(){
			@Override
			public void maximized(boolean isMaximized){
				maximized=isMaximized;
			}
		});
		return configuration;
	}
}
```
I tried rebuilding from this repo as a source repo in gradle and it has failed because of missing glfwGetPlatform.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwSetErrorCallback(GLFW.java:1255)
	at org.lwjgl.glfw.GLFW.glfwSetErrorCallback(GLFW.java:1288)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:87)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:136)
	at com.customautosys.tuxfight.desktop.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:26)
	at com.customautosys.tuxfight.desktop.Lwjgl3Launcher.main(Lwjgl3Launcher.java:20)
Caused by: java.lang.NullPointerException: A required function is missing: glfwGetPlatform
Caused by: java.lang.NullPointerException: A required function is missing: glfwGetPlatform

	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:129)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:122)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:47)
	... 6 more
```
Indeed, this function is missing when I run nm -gU libglfw.dylib:
```
00000000000070e0 T _glfwCreateCursor
0000000000007250 T _glfwCreateStandardCursor
000000000000a190 T _glfwCreateWindow
0000000000009df0 T _glfwCreateWindowSurface
000000000000a500 T _glfwDefaultWindowHints
0000000000007170 T _glfwDestroyCursor
000000000000a460 T _glfwDestroyWindow
00000000000041b0 T _glfwExtensionSupported
000000000000af40 T _glfwFocusWindow
0000000000008760 T _glfwGetClipboardString
000000000000f0a0 T _glfwGetCocoaMonitor
00000000000146a0 T _glfwGetCocoaWindow
00000000000043d0 T _glfwGetCurrentContext
0000000000006f90 T _glfwGetCursorPos
0000000000016420 T _glfwGetEGLContext
00000000000163e0 T _glfwGetEGLDisplay
0000000000016470 T _glfwGetEGLSurface
00000000000051f0 T _glfwGetError
000000000000ac90 T _glfwGetFramebufferSize
0000000000007fc0 T _glfwGetGamepadName
0000000000008060 T _glfwGetGamepadState
0000000000009720 T _glfwGetGammaRamp
00000000000066c0 T _glfwGetInputMode
0000000000009cf0 T _glfwGetInstanceProcAddress
00000000000075c0 T _glfwGetJoystickAxes
0000000000007690 T _glfwGetJoystickButtons
00000000000078f0 T _glfwGetJoystickGUID
0000000000007770 T _glfwGetJoystickHats
0000000000007840 T _glfwGetJoystickName
00000000000079e0 T _glfwGetJoystickUserPointer
0000000000006eb0 T _glfwGetKey
0000000000006df0 T _glfwGetKeyName
0000000000006e50 T _glfwGetKeyScancode
0000000000009300 T _glfwGetMonitorContentScale
0000000000009340 T _glfwGetMonitorName
00000000000092a0 T _glfwGetMonitorPhysicalSize
0000000000009200 T _glfwGetMonitorPos
00000000000093b0 T _glfwGetMonitorUserPointer
0000000000009240 T _glfwGetMonitorWorkarea
0000000000009160 T _glfwGetMonitors
0000000000006f20 T _glfwGetMouseButton
0000000000015020 T _glfwGetNSGLContext
0000000000016a50 T _glfwGetOSMesaColorBuffer
0000000000016bb0 T _glfwGetOSMesaContext
0000000000016b00 T _glfwGetOSMesaDepthBuffer
0000000000009d70 T _glfwGetPhysicalDevicePresentationSupport
00000000000091b0 T _glfwGetPrimaryMonitor
00000000000044c0 T _glfwGetProcAddress
0000000000009c80 T _glfwGetRequiredInstanceExtensions
0000000000008790 T _glfwGetTime
0000000000008950 T _glfwGetTimerFrequency
0000000000008920 T _glfwGetTimerValue
00000000000051b0 T _glfwGetVersion
00000000000051e0 T _glfwGetVersionString
00000000000094e0 T _glfwGetVideoMode
0000000000009430 T _glfwGetVideoModes
000000000000af70 T _glfwGetWindowAttrib
000000000000ad30 T _glfwGetWindowContentScale
000000000000acd0 T _glfwGetWindowFrameSize
000000000000b210 T _glfwGetWindowMonitor
000000000000ad70 T _glfwGetWindowOpacity
000000000000aa90 T _glfwGetWindowPos
000000000000ab00 T _glfwGetWindowSize
000000000000b300 T _glfwGetWindowUserPointer
000000000000af10 T _glfwHideWindow
000000000000adf0 T _glfwIconifyWindow
0000000000004d70 T _glfwInit
0000000000005120 T _glfwInitAllocator
00000000000050a0 T _glfwInitHint
0000000000007f00 T _glfwJoystickIsGamepad
0000000000007520 T _glfwJoystickPresent
0000000000004110 T _glfwMakeContextCurrent
000000000000ae50 T _glfwMaximizeWindow
000000000000b580 T _glfwPollEvents
000000000000b630 T _glfwPostEmptyEvent
0000000000006dc0 T _glfwRawMouseMotionSupported
000000000000aee0 T _glfwRequestWindowAttention
000000000000ae20 T _glfwRestoreWindow
0000000000007360 T _glfwSetCharCallback
00000000000073a0 T _glfwSetCharModsCallback
0000000000008730 T _glfwSetClipboardString
00000000000072f0 T _glfwSetCursor
0000000000007460 T _glfwSetCursorEnterCallback
0000000000007000 T _glfwSetCursorPos
0000000000007420 T _glfwSetCursorPosCallback
00000000000074e0 T _glfwSetDropCallback
0000000000005260 T _glfwSetErrorCallback
000000000000b500 T _glfwSetFramebufferSizeCallback
0000000000009520 T _glfwSetGamma
00000000000097c0 T _glfwSetGammaRamp
0000000000006760 T _glfwSetInputMode
0000000000007a30 T _glfwSetJoystickCallback
00000000000079a0 T _glfwSetJoystickUserPointer
0000000000007320 T _glfwSetKeyCallback
00000000000093f0 T _glfwSetMonitorCallback
0000000000009380 T _glfwSetMonitorUserPointer
00000000000073e0 T _glfwSetMouseButtonCallback
00000000000074a0 T _glfwSetScrollCallback
0000000000008830 T _glfwSetTime
000000000000ac20 T _glfwSetWindowAspectRatio
000000000000b140 T _glfwSetWindowAttrib
000000000000b3c0 T _glfwSetWindowCloseCallback
000000000000b540 T _glfwSetWindowContentScaleCallback
000000000000b440 T _glfwSetWindowFocusCallback
000000000000aa60 T _glfwSetWindowIcon
000000000000b480 T _glfwSetWindowIconifyCallback
000000000000b4c0 T _glfwSetWindowMaximizeCallback
000000000000b250 T _glfwSetWindowMonitor
000000000000ada0 T _glfwSetWindowOpacity
000000000000aad0 T _glfwSetWindowPos
000000000000b340 T _glfwSetWindowPosCallback
000000000000b400 T _glfwSetWindowRefreshCallback
000000000000aa00 T _glfwSetWindowShouldClose
000000000000ab40 T _glfwSetWindowSize
000000000000b380 T _glfwSetWindowSizeCallback
000000000000ab70 T _glfwSetWindowSizeLimits
000000000000aa30 T _glfwSetWindowTitle
000000000000b2d0 T _glfwSetWindowUserPointer
000000000000ae80 T _glfwShowWindow
0000000000004410 T _glfwSwapBuffers
0000000000004460 T _glfwSwapInterval
0000000000005080 T _glfwTerminate
0000000000007aa0 T _glfwUpdateGamepadMappings
0000000000009c50 T _glfwVulkanSupported
000000000000b5b0 T _glfwWaitEvents
000000000000b5e0 T _glfwWaitEventsTimeout
000000000000a610 T _glfwWindowHint
000000000000a930 T _glfwWindowHintString
000000000000a9d0 T _glfwWindowShouldClose
```

**Comment by badlogic** [comment]
That must be a recent addition to GLFW that the latest LWJGL relies on in their 3.3.1 release. I'll update my GLFW repo.

**Comment by badlogic** [comment]
I'm a big old dumdum. Closed in favor of this PR. https://github.com/libgdx/libgdx/pull/6772

**Pull request closed without merging**
