### PR TITLE
Convenience methods for Align

### PR DESCRIPTION
**Pull request by TCreutzenberg**
- isHorizontalLeft(int align)
- isHorizontalCenter(int align)
- isHorizontalRight(int align)
- isVerticalTop(int align)
- isVerticalCenter(int align)
- isVerticalBottom(int align)

### CODE REVIEW

**Comment by NathanSweet** [comment]
I'm OK with this, but I'd like to drop `Horizontal` and `Vertical` from the method names.

**Comment by PokeMMO** [comment]
I would suggest to use bit operation checks for left/right/top/bottom. It doesn't quite work for center, since it's the assumed position if left/right or top/bottom are not set.

`
static public final boolean isLeft(int align) {
    return (align & left) != 0;
}`

**Comment by TCreutzenberg** [comment]
Never did that before ;)

Tests (copy into Align and run):

public static void main(String[] args) {
		System.out.println("isLeft: topLeft     " + isLeft(topLeft));
		System.out.println("isLeft: top         " + isLeft(top));
		System.out.println("isLeft: topRight    " + isLeft(topRight));
		System.out.println("isLeft: left        " + isLeft(left));
		System.out.println("isLeft: center      " + isLeft(center));
		System.out.println("isLeft: right       " + isLeft(right));
		System.out.println("isLeft: bottomLeft  " + isLeft(bottomLeft));
		System.out.println("isLeft: bottom      " + isLeft(bottom));
		System.out.println("isLeft: bottomRight " + isLeft(bottomRight));
		System.out.println(" ");
		System.out.println("isCenterHorizontal: topLeft     " + isCenterHorizontal(topLeft));
		System.out.println("isCenterHorizontal: top         " + isCenterHorizontal(top));
		System.out.println("isCenterHorizontal: topRight    " + isCenterHorizontal(topRight));
		System.out.println("isCenterHorizontal: left        " + isCenterHorizontal(left));
		System.out.println("isCenterHorizontal: center      " + isCenterHorizontal(center));
		System.out.println("isCenterHorizontal: right       " + isCenterHorizontal(right));
		System.out.println("isCenterHorizontal: bottomLeft  " + isCenterHorizontal(bottomLeft));
		System.out.println("isCenterHorizontal: bottom      " + isCenterHorizontal(bottom));
		System.out.println("isCenterHorizontal: bottomRight " + isCenterHorizontal(bottomRight));
		System.out.println(" ");
		System.out.println("isRight: topLeft     " + isRight(topLeft));
		System.out.println("isRight: top         " + isRight(top));
		System.out.println("isRight: topRight    " + isRight(topRight));
		System.out.println("isRight: left        " + isRight(left));
		System.out.println("isRight: center      " + isRight(center));
		System.out.println("isRight: right       " + isRight(right));
		System.out.println("isRight: bottomLeft  " + isRight(bottomLeft));
		System.out.println("isRight: bottom      " + isRight(bottom));
		System.out.println("isRight: bottomRight " + isRight(bottomRight));
		System.out.println(" ");
		System.out.println("isTop: topLeft     " + isTop(topLeft));
		System.out.println("isTop: top         " + isTop(top));
		System.out.println("isTop: topRight    " + isTop(topRight));
		System.out.println("isTop: left        " + isTop(left));
		System.out.println("isTop: center      " + isTop(center));
		System.out.println("isTop: right       " + isTop(right));
		System.out.println("isTop: bottomLeft  " + isTop(bottomLeft));
		System.out.println("isTop: bottom      " + isTop(bottom));
		System.out.println("isTop: bottomRight " + isTop(bottomRight));
		System.out.println(" ");
		System.out.println("isCenterVertical: topLeft     " + isCenterVertical(topLeft));
		System.out.println("isCenterVertical: top         " + isCenterVertical(top));
		System.out.println("isCenterVertical: topRight    " + isCenterVertical(topRight));
		System.out.println("isCenterVertical: left        " + isCenterVertical(left));
		System.out.println("isCenterVertical: center      " + isCenterVertical(center));
		System.out.println("isCenterVertical: right       " + isCenterVertical(right));
		System.out.println("isCenterVertical: bottomLeft  " + isCenterVertical(bottomLeft));
		System.out.println("isCenterVertical: bottom      " + isCenterVertical(bottom));
		System.out.println("isCenterVertical: bottomRight " + isCenterVertical(bottomRight));
		System.out.println(" ");
		System.out.println("isBottom: topLeft     " + isBottom(topLeft));
		System.out.println("isBottom: top         " + isBottom(top));
		System.out.println("isBottom: topRight    " + isBottom(topRight));
		System.out.println("isBottom: left        " + isBottom(left));
		System.out.println("isBottom: center      " + isBottom(center));
		System.out.println("isBottom: right       " + isBottom(right));
		System.out.println("isBottom: bottomLeft  " + isBottom(bottomLeft));
		System.out.println("isBottom: bottom      " + isBottom(bottom));
		System.out.println("isBottom: bottomRight " + isBottom(bottomRight));
	}

**Comment by NathanSweet** [comment]
I committed the changes. A method to do the checking is not necessary.

**Pull request closed without merging**
