### PR TITLE
Add mappings for more numpad buttons, fixes #2524

### LINKED ISSUE #2524: LwjglInput numeric keyboard keycode mismatches
Current implementation has one serious flaw: while it allows to easily recognize numpad 0-9, and + \* keys, as well as NumLock (named Num in Keys class for some reason), it makes it completely impossible to distinguish numpad Enter, slash, minus and period from regular one - and this distinction is quite important in many games. It wouldn't be a problem for KeyTyped, but it certainly is bad for KeyDown, as it breaks the "one key, one keycode" principle - I know it's not the case in 100%, but at least POLA requires to try to stick to it, and it _does_ work for every other key on my keyboard, with exception of those unlucky two.

LWJGL offers this possibility natively, and since desktop is IMO actually the only platform that should get this correction, I reckon it shouldn't break any compatibility whatsoever. The outline of my proposal is as follows:

_com.badlogic.gdx.Input.java_, _Keys_ class

``` java
        public static final int NUMPAD_9 = 153;
```

changed to 

``` java
        public static final int NUMPAD_9 = 153;

        public static final int NUMPAD_DIVIDE = 154;
        public static final int NUMPAD_MULTIPLY = 155;
        public static final int NUMPAD_SUBTRACT= 156;
        public static final int NUMPAD_ADD = 157;
        public static final int NUMPAD_DOT = 158;
        public static final int NUMPAD_COMMA= 159;
        public static final int NUMPAD_ENTER = 160;

        public static final int NUMLOCK = NUM; // to keep the backward compatibility but offer a more "regular" name, as per http://en.wikipedia.org/wiki/Num_lock
```

and to _com.badlogic.gdx.backends.lwjgl.LwjglInput.java_
in _getGdxKeyCode()_

``` java
case Keyboard.KEY_NUMLOCK:
return Input.Keys.NUMLOCK;
case Keyboard.KEY_DECIMAL:
return Input.Keys.NUMPAD_DOT;
case Keyboard.KEY_DIVIDE:
return Input.Keys.SLASH;
case Keyboard.KEY_LMETA:
return Input.Keys.SYM;
case Keyboard.KEY_RMETA:
return Input.Keys.SYM;
case Keyboard.KEY_NUMPADEQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_AT:
return Input.Keys.AT;
case Keyboard.KEY_EQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_NUMPADCOMMA:
return Input.Keys.COMMA;
case Keyboard.KEY_NUMPADENTER:
return Input.Keys.ENTER;
```

to

``` java
case Keyboard.KEY_NUMLOCK:
return Input.Keys.NUMLOCK;
case Keyboard.KEY_DECIMAL:
return Input.Keys.NUMPAD_DOT;
case Keyboard.KEY_DIVIDE:
return Input.Keys.SLASH;
case Keyboard.KEY_LMETA:
return Input.Keys.SYM;
case Keyboard.KEY_RMETA:
return Input.Keys.SYM;
case Keyboard.KEY_NUMPADEQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_AT:
return Input.Keys.AT;
case Keyboard.KEY_EQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_NUMPADCOMMA:
return Input.Keys.NUMPAD_COMMA;
case Keyboard.KEY_NUMPADENTER:
return Input.Keys.NUMPAD_ENTER;
```

and (in _getLwjglKeyCode()_)

``` java
case Input.Keys.NUMPAD_9:
return Keyboard.KEY_NUMPAD9;
```

to

``` java
case Input.Keys.NUMPAD_9:
return Keyboard.KEY_NUMPAD9;
case Input.Keys.NUMPAD_ENTER:
return Keyboard.KEY_NUMPADENTER;
case Input.Keys.NUMPAD_DOT:
return Keyboard.KEY_DECIMAL;
case Input.Keys.NUMPAD_COMMA:
return Keyboard.KEY_NUMPADCOMMA;
```

and so on for other numpad keys (/ and, possibly, + - *)

PS. Is changing current case-based key matching to map-based one sensible? AFAIK Java does that internally for big switch/case blocks in newest versions, but counting on that for Java 6 is a bit far-fetched IMO (and I don't know if Delvik is doing that at all); I use LwjglInput changed to map-based keycode translation myself, so if you consider this change sensible I'll gladly contribute the code. It shortens the keycode translation code in half, BTW.

### PR DESCRIPTION
**Pull request by yousiftouma**
This PR will map some of the unmapped numpad buttons so you can use them on desktop games.
If we have missed anything, please let us know and point us in the right direction.

Should fix #2524 

The following (unmerged) commits were used as references on how this should be done:

https://github.com/libgdx/libgdx/pull/2542/commits/d8c32b64790a664abe7e2e1411cb0005a10a6570
https://github.com/libgdx/libgdx/pull/2542/commits/f7fe73242cf70b4e1f73a561f9624fbc45780897

Done together with @GeorgeYildiz

### CODE REVIEW

**Comment by yousiftouma** [comment]
Can anyone help us figure out what went wrong with the travis build?

**Comment by Tom-Ski** [comment]
It is an issue with the build itself, not this PR.

**Comment by yousiftouma** [comment]
Ok, how should we proceed then?

**Comment by NathanSweet** [comment]
Do we need changes for the other backends?

**Comment by FyiurAmron** [comment]
FWIW, you're still missing:

+			case NUM_LOCK:
+			case SYSRQ:
+			case SCROLL_LOCK:
+			case BREAK:
+			case CAPS_LOCK:

and there's still the backspace/del Android mixup there.

**Review by MrStahlfelge — CHANGES_REQUESTED** [review]
While this fixes some issues, it also introduces some new keycodes to the platform-agnostic keys. These new keycodes are only implemented on Lwjgl backend and are therefore not really useable in core. Please add mappings for Android, Lwjgl3, GWT (if possible) and iOS for the new keycodes.

EDIT: As these are Android keycodes, Android mapping is implicitely defined.

**Comment by MrStahlfelge** [comment]
I've taken over and will note process so far here. 

According to https://github.com/libgdx/libgdx/wiki/Adding-new-Keycodes

- [X] Add the keycodes to Input.Keys (don't forget to define Input.Keys.toString() for the new codes.

- [ ] Android: If they exist for Android, use same codes as in Android's KeyEvent class. If not existent for Android, define a keycode non-clashing with Android's codes and document it as a comment. Due to Android's key code being same than libgdx, no change is needed in Android's backend.

- [ ] GWT: Changes needed in DefaultGwtInput.keyForCode(). GWT's KeyCode.java is incomplete. Check with all browsers and OS at hand (might be slightly different) at https://keycode.info/

- [ ] RoboVM: Changes needed in DefaultIOSInput.getGdxKeyCode(). Check UIKeyboardHIDUsage enum (yes, you can do that on any OS).

- [X] Lwjgl: Use Keyboard constants in DefaultLwjglInput.getGdxKeyCode() and getLwjglKeyCode(), 
- [ ] Lwjgl3 is similar. 
- [ ] Don't forget LwjglAwtInput

- [ ] CHANGES: Document newly added keycodes and if they are completely new (unmapped before) or changing a mapping existing before:
Added: NUMPAD_DIVIDE, NUMPAD_MULTIPLY, NUMPAD_SUBTRACT, NUMPAD_ADD, NUMPAD_DOT, NUMPAD_COMMA, NUMPAD_ENTER, NUMPAD_EQUALS, NUMPAD_LEFT_PAREN, NUMPAD_RIGHT_PAREN, NUM_LOCK
Following changes might be done depending on platform: Keys.STAR to Keys.NUMPAD_MULTIPLY, Keys.SLASH to Keys.NUMPAD_DIVIDE, Keys.NUM to Keys.NUM_LOCK, Keys.COMMA to Keys.NUMPAD_COMMA, Keys.PERIOD to Keys.NUMPAD_DOT, Keys.COMMA to Keys.NUMPAD_COMMA, Keys.ENTER to Keys.NUMPAD_ENTER, Keys.PLUS to Keys.NUMPAD_ADD, Keys.MINUS to Keys.NUMPAD_SUBTRACT

**Comment by MrStahlfelge** [comment]
Okay people, I think I am done here. I requested a few fellow contributors to check and test on their prefered platforms as this concerns every platform. 

These key mappings is really fiddly without the opportunity to earn glory, but I think the change is good and we should do it.

**Comment by FyiurAmron** [comment]
@MrStahlfelge what about other 4 of those: https://github.com/libgdx/libgdx/pull/5207#issuecomment-386766337 ? While https://github.com/libgdx/libgdx/issues/5389 is IMVHO of a very low priority (F13-F24 are seldom found in the wild), e.g. CapsLock is (IMO) a quite common key. Any chance of mappings for it appearing in this PR?

**Comment by MrStahlfelge** [comment]
I am aware of the F13 up request and the other keys. I will take care of it after this is merged to keep the number of changes to review low. You can help by testing the platforms you use and state here if everything works as expected, thanks. :)

**Review by MrStahlfelge — APPROVED** [review]

**Review by SimonIT — APPROVED** [review]
Tested on Desktop (LWJGL & LWJGL3 on Windows), GWT (Chrome) and Android (11)

**Pull request merged**
