### PR TITLE
Feature/container interface

### PR DESCRIPTION
**Pull request by Hogusong**
created a common interface container class with size and clear functions
implemented the container class in appropriate classes
for issue #4506

### CODE REVIEW

**Comment by badlogic** [comment]
Could you give me a use case for this?

**Comment by Hogusong** [comment]
I created this for issue #4506
@danijelz is there a specific use case you had in mind for this issue.

**Comment by NathanSweet** [comment]
I haven't needed this, but I'm not against it. The Eclipse source code formatter should be run on classes changed. I'm not sure about the name `Container`. At least, libgdx already has a class called `Container` in scene2d. `Collection`? java.util.Collection is very rarely used in app code.

**Comment by cypherdare** [comment]
Not sure what the point of creating this interface is if the only method it has is `size()`. With that single method, there's nothing you can do to the collection after you've checked its size. About the only other method you could add without generics is `clear()`. I can't think of any use case with just those two methods, but generics would make the primitive-based collections messy. 

If you add enough methods for this to have some use, it becomes clumsy to support both maps and lists/sets with the same interface.

**Comment by Tom-Ski** [comment]
Don't see clear use case, or support for this, so closing it out. If the situation changes we can reopen.

**Pull request closed without merging**
