### PR TITLE
Bind server socket to a specific hostname or ip address

### PR DESCRIPTION
**Pull request by btd-f-lago**
I thought this might be useful for gdx-based applications that runs as a server on multi-domain platforms (i.e. game servers).
Added an optional argument "hostname" to method Net.newServerSocket to allow specific domain / ip address binding, it maps 1:1 to Java.net binding interface.

### CODE REVIEW

**Comment by nooone** [comment]
Looks fine to me.

It's weird though that there's a `PingPongSocketExample` in the Tests. If it should be added to the tests, it should be renamed.

Furthermore: Merge conflicts...

**Comment by btd-f-lago** [comment]
I rebased/solved all the conflicts and removed the PingPongSocketExample from the Test (it probably doesn't really need a test).
Should be able to auto-merge now.

**Comment by MobiDevelop** [comment]
You've got some of Nate's commits in here. Please rebase so that only your commit is included.

**Comment by btd-f-lago** [comment]
I'm sorry, I completely messed up with my fork, so I opened a brand new PR at #3142

**Pull request closed without merging**
