### PR TITLE
[LWJGL3] Negative monitor coords

### PR DESCRIPTION
**Pull request by EtK2000**
Support positioning on monitors with negative relative coordinates.

Tested it on my Windows machine with a monitor who's coords are negative (top left corner is to left of/above primary monitor).

### CODE REVIEW

**Comment by crykn** [comment]
Hey @EtK2000! The `Math.max(0, ...)` stuff was added with #6649 to fix borderless fullscreen mode. Have you tested whether that still works with your PR?

**Comment by EtK2000** [comment]
I tested it with the following:
```
Gdx.graphics.setResizable(false);
Gdx.graphics.setUndecorated(true);
Gdx.graphics.setWindowedMode(screenSizeX, screenSizeY);
```

As well as:
```
Gdx.graphics.setResizable(true);
Gdx.graphics.setUndecorated(false);
Gdx.graphics.setWindowedMode(windowedSizeX, windowedSizeY);
```

Both work for me as intended moving to the desired monitor and positioning correctly in the center (windowed) or spanning the whole monitor (borderless).

**Comment by crykn** [comment]
Okay, I just tested the changes on Windows 10 and everything works as expected. If someone could confirm whether the same is true for macOS (and maybe Linux), then I'd be willing to approve the PR.

**Comment by EtK2000** [comment]
Just tested it in Mac and it's working.
I can try to test it on Ubuntu later, and I'll report the results.

**Review by crykn — APPROVED** [review]

**Comment by EtK2000** [comment]
Confirmed to be working correctly on Ubuntu with KDE

**Pull request merged**
