### PR TITLE
Add SpriteCache.getCustomShader() and SpriteCache.isDrawing()

### PR DESCRIPTION
**Pull request by dlon**

### CODE REVIEW

**Comment by EtK2000** [comment]
Might I suggest renaming to "getCustomShader" as it returns null if using the default.

**Comment by dlon** [comment]
Or would it be better to return the default shader in that case, like SpriteBatch does? (I find this less useful.)

**Comment by MobiDevelop** [comment]
I'd call it getCustomShader of it will only return the custom shader, otherwise I think it should return the default if there is no custom

**Comment by RUSshy** [comment]
setShader() 
getShader()

Seems like it follow what was used for the setter, maybe should rename this one too to avoid confusion ?

**Pull request merged**
