### PR TITLE
TileAnimator

### PR DESCRIPTION
**Pull request by TCreutzenberg**
The goal of this PR is to create a possibility to influence the animation speed of the AnimatedTiledMapTile.

Previous discussions can be seen here: https://github.com/libgdx/libgdx/pull/5275

@MobiDevelop : This is the way you want this, right?

### CODE REVIEW

**Comment by TCreutzenberg** [comment]
Can somebody help me find out why the tests are failing? It runs like a charm on my local machine, and the  errors are about not having the source code for a class which is included in this PR...

Error: ERROR] Errors in 'file:/home/runner/work/libgdx/libgdx/gdx/src/com/badlogic/gdx/maps/tiled/renderers/BatchTiledMapRenderer.java'
Error:   [ERROR] Line 63: No source code is available for type com.badlogic.gdx.maps.tiled.TileAnimator; did you forget to inherit a required module?
Error:   [ERROR] Line 97: No source code is available for type com.badlogic.gdx.maps.tiled.DefaultTileAnimator; did you forget to inherit a required module?
   Tracing compile failure path for type 'com.badlogic.gdx.tests.TiledMapObjectLoadingTest'
Error: ERROR] Errors in 'file:/home/runner/work/libgdx/libgdx/tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapObjectLoadingTest.java'
Error:   [ERROR] Line 60: No source code is available for type com.badlogic.gdx.maps.tiled.TileAnimator; did you forget to inherit a required module?
Error:   [ERROR] Line 78: No source code is available for type com.badlogic.gdx.maps.tiled.DefaultTileAnimator; did you forget to inherit a required module?
   Tracing compile failure path for type 'com.badlogic.gdx.tests.TiledMapAnimationLoadingTest'
Error: ERROR] Errors in 'file:/home/runner/work/libgdx/libgdx/tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapAnimationLoadingTest.java'
Error:   [ERROR] Line 46: No source code is available for type com.badlogic.gdx.maps.tiled.TileAnimator; did you forget to inherit a required module?
Error:   [ERROR] Line 63: No source code is available for type com.badlogic.gdx.maps.tiled.DefaultTileAnimator; did you forget to inherit a required module?
Error: OR] Aborting compile due to errors in some input files

**Comment by mgsx-dev** [comment]
yes you have to include new classes in https://github.com/libgdx/libgdx/blob/master/gdx/res/com/badlogic/gdx.gwt.xml file.

Also, i think updating time in renderer code was not a good idea at the first place. IMO, this TileAnimator should be moved to AnimatedTiledMapTile and called once before render loop.

**Comment by TCreutzenberg** [comment]
@mgsx-dev Can you please help me find the correct spot to call the TileAnimator? I can't find a spot outside the render flow where this would be called automatically... Does everybody need to manually do this? Did I understand you correctly?

**Comment by TCreutzenberg** [comment]
@mgsx-dev Any updates on this one?

**Comment by mgsx-dev** [comment]
Sorry for the delay @TCreutzenberg (i forgot this one), what i meant is that updating in renderer could be a problem if you want to render several times, with one or several renderers, etc... the classic reason why separating update from rendering is important. That said i don't know what's the best move, i let you guys decide.

**Comment by TCreutzenberg** [comment]
After thinking about this for some time and the breaking changes it would create for everybody to do this nice and properly, I guess I will just find a different solution in my project.

**Pull request closed without merging**
