### PR TITLE
Gyro implementation for Android

### PR DESCRIPTION
**Pull request by snovak**
This is a continuation of a former pull request, https://github.com/libgdx/libgdx/pull/3361.  I've been procrastinating on finishing this up as I'm unfamiliar with the rebase command and needed some schooling, which I acquired here, http://stackoverflow.com/questions/33829117/git-squash-rebase-master-history-concerns

### CODE REVIEW

**Comment by davebaol** [comment]
If I got it right this PR replaces #3361. If so, please close it.

**Comment by snovak** [comment]
@davebaol Okay, I've closed https://github.com/libgdx/libgdx/pull/3361 .

**Comment by badlogic** [comment]
Looks good, merged!

**Comment by snovak** [comment]
@badlogic , Awesome!

**Comment by intrigus** [comment]
@snovak Would be nice if you could update the wiki page I created: https://github.com/libgdx/libgdx/wiki/Gyroscope

**Comment by snovak** [comment]
@intrigus I am gunning for this.  I just have to get a few more things out of the way until I can get to it.  Thanks for putting that together!

**Pull request merged**
