### PR TITLE
Add a LongQueue variant

### PR DESCRIPTION
**Pull request by WickedShell**
This adds a LongQueue that works much the same way as the existing Queue class but is specialized to the primitive type. This was done by copying and editing down from the existing Queue class and test.

### CODE REVIEW

**Comment by intrigus** [comment]
Did you try this with GWT?

**Comment by SimonIT** [comment]
The travis build doesn't fail, so it should work with gwt

**Comment by WickedShell** [comment]
I haven't tried it with GWT as I've never done anything with GWT. I did actually provide a test (which definetly works when I run the build task in gradle, but I'm not sure if CI runs those tests within GWT at all.

**Comment by SimonIT** [comment]
The CI runs your test and compiles the test project. The test project contains the libgdx core (obviously), so if there would be a problem with gwt, it would fail

**Comment by Tom-Ski** [comment]
Was just missing cache entry

**Comment by WickedShell** [comment]
@Tom-Ski Thanks! For my future reference what is the point of that xml you added it to, and what should go in?

**Comment by Tom-Ski** [comment]
It defines the classes that are available to gwt for the core libgdx module. Every class that you want to be able to use in gwt backend needs to be put there, or excluded if its not gwt compatible.

**Pull request merged**
