### PR TITLE
Polygon sprite with repeating TextureRegion by triangulating to a uniform grid

### PR DESCRIPTION
**Pull request by azakhary**
**Problem**
I wanted to make a class, that will render a custom shaped polygon that is filled with repeating TextureRegion. This was possible to do with PolygonSprite class if "Texture" is used. But most use case require using TextureRegion instead. As a temporary solution, previously I was using PolygonSprite and a custom shader to which I was passing u/v data in order to render this. But this was bad too because it causes additional render call for each polygon, which sucks.

**Solution**
I propose using this class instead. In short it triangulates a polygon to a "grid" so that we can easily specify all u/v coordinates and pass this directly to PolygonSpriteBatch.

schmatic2

In order to avoid being murdered by @xoppa , a density variable is passed to specify the "grid" density, thus eliminating any connection to actual pixel size of texture region.

I did some testing and it seems to work fine, but at this stage it is not yet ready to merge, I would be happy if you guys can:
a) decide if you need this at all in libgdx - maybe many reasons why you do not
b) see if initial idea looks well implemented, test and so on

I will do some additional fixes/additions/pushes during the weekend.

### CODE REVIEW

**Comment by azakhary** [comment]
Also while writing his noticed 2 issues in Intersector class, which probably need separate fixing:
1) It sometimes returns duplicate points
2) If not intersection is found it throws exception while trying to create a polygon with 0 vertices.

**Comment by xoppa** [comment]
This looks like it could be if great added value (thinking of those bike on terrain riding games). Haven't looked at the implementation in depth yet though. At first glance I wonder why you didn't use the primitive arrays (IntArray and such), which avoid boxing and why `density` can't be set along with the polygon?

**Comment by azakhary** [comment]
I was thinking to use FloatArray, but because I was not familiar with it, I thought I initially do things with stuff I know. I'll take a better look at it, and see if it can be changed. As for right now, I am not familiar with what the exact benefit of using them is. 

As for density, agreed, no particular reason it should be in constructor, it makes sense to move it into setPolygon method.

Other thing that is missing is there is no transformations, rotation and such (not sure if that should be there) Also had to do some dirty hacks, due to issues with Intersector, as mentioned above.

**Comment by azakhary** [comment]
@NathanSweet What you think? On a side note, same thing can be also done to create a repeatable border/fill 9patch item, this is pretty good for UI elements. Just not sure if it should change in existing NinePatch class or be another one.

**Comment by intrigus** [comment]
Could you create issues for the issues you had with intersector, so they can also be fixed?

**Comment by azakhary** [comment]
Sure, will do.

**Comment by azakhary** [comment]
done, it's #3804, and #3805

**Comment by azakhary** [comment]
I tested this some more, it seems to be working as expected, and fast. Still not seing big point in changing float[] to FloatArray for now. I think this can be merged as is, taking into account that this can't break anything else. Worst case scenario this will sometimes do something not as expected, and if so people can file issues, and I'll take a look. But. Yeah would be cool to merge it as is, so others can use it. I am sure this is a handy thing to have. + We'll add it to overlap2d, as it was a very requested thing.

**Comment by azakhary** [comment]
If there will be news on #3804, and #3805 I'll make a PR to make changes.

**Comment by xoppa** [comment]
Why would you change `float[]` to `FloatArray` if you don't need to?

**Comment by azakhary** [comment]
That's what I am saying, there is no point in changing.

**Comment by xoppa** [comment]
Then why are you saying that?

**Comment by azakhary** [comment]
I thought that was what you suggested in one of your previous posts.

>  At first glance I wonder why you didn't use the primitive arrays (IntArray and such),

Maybe I misunderstood something, sorry :)

**Comment by xoppa** [comment]
I said that "you didn't use the primitive arrays (IntArray and such), which avoid boxing". E.g. your code contains the line: `private Array<Integer> gridPosMap = new Array<Integer>();`.

That is in no way related to changing `float[]` to `FloatArray`, which has nothing to do with boxing. See https://github.com/libgdx/libgdx/wiki/Collections.

**Comment by azakhary** [comment]
Aw, my bad, I got it backwards. Array<Integer> can be changed. You think it's worth it, in this case?

**Comment by xoppa** [comment]
Ofcourse, otherwise it wouldn't be outlined in the [guideline](https://github.com/libgdx/libgdx/wiki/Contributing#performance-considerations). Why would you think it is worth it to bloat using boxing in the first place?

Note that was just what I noticed at first glance, I haven't had the chance to look at the code in depth.

**Comment by azakhary** [comment]
Agreed. we'll see if I can give it a change tomorrow.

**Comment by azakhary** [comment]
@xoppa I removed the array instead of substituting with IntArray, turned out it could be avoided.

**Comment by NathanSweet** [comment]
Seems like it could be useful functionality. I don't see anything wrong with the implementation after a brief look.

**Comment by xoppa** [comment]
Okay nice. @azakhary can you add the GWT necessities and verfiy it works? See: https://github.com/libgdx/libgdx/wiki/Contributing#cross-platform-compatibility

**Comment by azakhary** [comment]
Sure, will do. I also need to reflect changes of  #3804, and #3805 that apparently been fixed lately, and squash commits at the end. That'll take some time, I'll try to do that tomorrow if all goes well.

**Comment by AldousP** [comment]
`float regionAspectRatio = region.getRegionHeight() / region.getRegionWidth();`

should probably become

`float regionAspectRatio = (float) region.getRegionHeight() / (float) region.getRegionWidth();`

So as to avoid the aspect ratio being incorrectly set as 0 since it is performing integer division.

**Comment by azakhary** [comment]
@xoppa there seems to be nothing wrong on GWT side nothing used that can break it, am I missing something?

**Comment by azakhary** [comment]
Also... a stupid question, I was trying to squash my prev 6 commits into one, but git rebase brings up around 1000 commits, reason is I did git pull upstream to make sure I have last sources, and merged that, so rebase now shows all of them.. Any idea on how to handle this?

**Comment by azakhary** [comment]
As for #3804, and #3805 sources are now updated to reflect that.

**Comment by xoppa** [comment]
> If you add any new classes, determine if they are compatible with GWT and add either include or exclude elements to the GWT module.

Please don't assume it will work on GWT, but instead verify it.

Github can squash the commits while merging nowadays, so I don't think it is needed for you to squash them manually anymore, not sure though. I'm afraid I can't say much about fixing your git. Usually when that happens to me, I copy the files to a new branch.

**Comment by azakhary** [comment]
Here you go.
screen shot 2016-04-09 at 6 41 52 pm

**Comment by azakhary** [comment]
If no need to squash then my work is done, if there is, let me know, I'll do the branching voodoo :)

**Comment by xoppa** [comment]
Could you please "include elements to the GWT module."
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx.gwt.xml

**Comment by azakhary** [comment]
yup, done

**Comment by AldousP** [comment]
I've noticed some smearing of the texture when using repeating sprite with an octagonal shape and a radius of 1300 or more. 1200 doesn't seem to cause it. The texture itself is png with about 50% opacity.

Example

**Comment by azakhary** [comment]
my feeling is it may be related to snapToGrid and float precision or something similar. Any suggestions are much appreciated on this one.

**Comment by AldousP** [comment]
I can take a look later. It appears to only happen in vertical stretches, I'm curious if the logic is stretching it to fit a length instead of beginning another loop. Has there been much testing done for larger polygons (with or without opacity)? Are you are aware of a recommended upper limit for the repeating sprite size?

**Comment by AldousP** [comment]
Also, this might not be correct, but it seems like the repeating sprite is modifying the passed in array, therefore it's potentially modifying an original Polygon object that might have yielded the float[] verts in the first place. 

I noticed that in creating a Polygon, passing it's vertices into the repeating sprite, and then reinspecting, the Polygon contains different values, even though no direct modification has occured.

**Comment by azakhary** [comment]
There should be no logic to stretch it, most probably stretching is related to u/v value issues inside a tile. And opacity has nothing to do with it. It happens for some rare values, and my suspicion is on snapToGrid logic. I was able to reproduce, and it's totally related to u/v's. As for upper limit, I don't think there should be any, the only limit is resulting triangles count. 

As for modified vertices.
it does call offset method which "Offsets polygon to 0 coordinate for ease of calculations, later offset is put back on final render" and instead of cloning original array it modifies it yes. Probably a better idea to arraycopy it.

**Comment by AldousP** [comment]
For what it's worth, here's the disparity between calling `getVertices` and `getTransformedVertices` on a Polygon and passing the results directly to a shape renderer. If the Polygon is never used in the repeating background sprite, the Green polygon aligns with the blue.

**Comment by azakhary** [comment]
that should be an easy fix with arraycopy, I'll do that today probably. But it's not related to weirdly stretched parts sometimes.

**Comment by NathanSweet** [comment]
Looks like it's OK to go in. Sorry we aren't always fast at getting to things! Thanks for contributing!

**Comment by NathanElmi** [comment]
Hi. I was wondering if somebody could make a small test example for this class. I have managed to recreate something similar to azakhary's first pic. However, I'd like to have a custom grass mesh (to go on top of my repeating dirt terrain), similar to hill climber game. The texture does not seem to rotate when my mesh has a steeper incline. Do I need to edit the U,V coordinates for this? Any help is much appreciated.

**Comment by azakhary** [comment]
this thing does not support rotation. I was thinking to jump from this to a custom terrain generator with curves and all, but never actually got time for that.

**Comment by azakhary** [comment]
That being said, you can probably change it to rotate, by transforming entire final vertex array, but, that'll be some custom coding.

**Comment by NathanElmi** [comment]
Thanks for the quick reply. I don't mind custom coding, but still pretty new to Libgdx. I'll have a go:)

**Comment by narnwork** [comment]
Hey, thanks for working on this. It seems to be the answer to all my polygon needs. I have come so close to renderering my polygon with tiles but I'm running into some weirdness with the texturing. I get some parts of the polygon looking like this:

**Comment by narnwork** [comment]
Hey, thanks for working on this. It seems to be the answer to all my polygon needs. I have come so close to rendering my polygon with tiles but I'm running into some weirdness with the texturing. I get some parts of the polygon looking like this:

http://imgur.com/a/FcipQ

I have a test libGDX project if anyone wants to try it out. You can use any tile but I was using this one:

http://imgur.com/a/1wkhv

Code is linked here if anyone wants to try: 

[dest.txt](https://github.com/libgdx/libgdx/files/782135/dest.txt)

**Comment by Kablion** [comment]
Hey if anyone is still looking for this, A while ago I made a class that has all you need (based on azakhary's code). Maybe It could also be added to LibGDX, but I don't know how I can do it and If it's not structured properly. If someone wants to edit it and submit it, you have my permission. 

It works fine, and you won't have the bug narnwork mentioned.

[RepeatablePolygonSprite.txt](https://github.com/libgdx/libgdx/files/2293792/RepeatablePolygonSprite.txt)

`package de.kablion.utils;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.PolygonSpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.EarClippingTriangulator;
import com.badlogic.gdx.math.Intersector;
import com.badlogic.gdx.math.MathUtils;
import com.badlogic.gdx.math.Polygon;
import com.badlogic.gdx.math.Rectangle;
import com.badlogic.gdx.math.Vector2;
import com.badlogic.gdx.utils.Array;
import com.badlogic.gdx.utils.Disposable;
import com.badlogic.gdx.utils.ShortArray;

/**
 * Renders polygon filled with a repeating TextureRegion with specified density
 * Without causing an additional flush or render call
 *
 * @author Avetis Zakharyan (concept and first version)
 * @author Kablion (rewrite)
 */
public class RepeatablePolygonSprite implements Disposable {

    public enum WrapType {
        STRETCH,REPEAT,REPEAT_MIRRORED
    }

    private WrapType wrapTypeX = WrapType.REPEAT;
    private WrapType wrapTypeY = WrapType.REPEAT;

    private final Color color = new Color(Color.WHITE);

    private TextureRegion textureRegion;
    private TextureRegion whiteTextureRegion;

    private Vector2 textureOffset = new Vector2();
    private float textureWidth = 0;
    private float textureHeight = 0;

    private float textureDebugX = 0;
    private float textureDebugY = 0;

    private boolean dirtyGrid = true;
    private boolean dirtyAttributes = true;

    private Array<float[]> parts = new Array<float[]>();

    private Array<float[]> vertices = new Array<float[]>();
    private Array<short[]> indices = new Array<short[]>();

    private int rows;
    private Vector2 gridOffset = new Vector2();
    private float gridWidth, gridHeight;
    private Vector2 buildOffset = new Vector2();

    private Polygon polygon = new Polygon();
    private Rectangle boundingRect = new Rectangle();

    public RepeatablePolygonSprite() {
        Pixmap pixmap = new Pixmap(1, 1, Pixmap.Format.RGBA8888);
        pixmap.setColor(Color.WHITE);
        pixmap.fill();
        this.whiteTextureRegion = new TextureRegion(new Texture(pixmap));
        pixmap.dispose();
    }

    /**
     * calculates the grid and the parts in relation to the texture Origin
     */
    private void prepareVertices() {
        parts.clear();
        if (polygon.getVertices().length == 0) return;
        float[] vertices = polygon.getVertices().clone();

        Polygon polygon = new Polygon(vertices);
        Polygon tmpPoly = new Polygon();
        Polygon intersectionPoly = new Polygon();
        EarClippingTriangulator triangulator = new EarClippingTriangulator();

        int idx;

        Rectangle bounds = polygon.getBoundingRectangle();


        if (wrapTypeX == WrapType.STRETCH || textureRegion == null) {
            gridWidth = bounds.getWidth();
        } else {
            gridWidth = textureWidth;
        }
        if (wrapTypeY == WrapType.STRETCH || textureRegion == null) {
            gridHeight = bounds.getHeight();
        } else {
            gridHeight = textureHeight;
        }

        polygon.setVertices(offset(vertices));

        bounds = polygon.getBoundingRectangle();

        int cols = (int) (Math.ceil(bounds.getWidth() / gridWidth));
        if (bounds.getX() + bounds.getWidth() > (cols + gridOffset.x) * gridWidth) cols++;
        rows = (int) Math.ceil(bounds.getHeight() / gridHeight);
        if (bounds.getY() + bounds.getHeight() > (rows + gridOffset.y) * gridHeight) rows++;

        for (int col = 0; col < cols; col++) {
            for (int row = 0; row < rows; row++) {
                float[] verts = new float[8];
                idx = 0;
                int offsettedCol = col + (int) gridOffset.x;
                int offsettedRow = row + (int) gridOffset.y;

                verts[idx++] = offsettedCol * gridWidth;
                verts[idx++] = offsettedRow * gridHeight;

                verts[idx++] = (offsettedCol) * gridWidth;
                verts[idx++] = (offsettedRow + 1) * gridHeight;

                verts[idx++] = (offsettedCol + 1) * gridWidth;
                verts[idx++] = (offsettedRow + 1) * gridHeight;

                verts[idx++] = (offsettedCol + 1) * gridWidth;
                verts[idx] = (offsettedRow) * gridHeight;

                tmpPoly.setVertices(verts);

                Intersector.intersectPolygons(polygon, tmpPoly, intersectionPoly);
                verts = intersectionPoly.getVertices();
                if (verts.length > 0) {
                    parts.add(snapToGrid(verts, offsettedRow, offsettedCol));
                    ShortArray arr = triangulator.computeTriangles(verts);
                    indices.add(arr.toArray());
                } else {
                    // adding null for key consistancy, needed to get col/row from key
                    // the other alternative is to make parts - IntMap<FloatArray>
                    parts.add(null);
                }
            }
        }
        dirtyGrid = false;
        dirtyAttributes = true;
    }

    /**
     * Builds final vertices with vertex attributes like coordinates, color and region u/v
     */
    private void buildVertices() {
        vertices.clear();
        if (polygon.getVertices().length == 0) return;
        for (int i = 0; i < parts.size; i++) {
            float verts[] = parts.get(i);
            if (verts == null) continue;

            float[] fullVerts = new float[5 * verts.length / 2];
            int idx = 0;

            int col = i / rows;
            int row = i % rows;
            int offsettedCol = col + (int) gridOffset.x;
            int offsettedRow = row + (int) gridOffset.y;

            for (int j = 0; j < verts.length; j += 2) {
                float x = (verts[j] + buildOffset.x + textureOffset.x) - getOriginX();
                x *= getScaleX();
                float y = (verts[j + 1] + buildOffset.y + textureOffset.y) - getOriginY();
                y *= getScaleY();
                if (getRotation() != 0) {
                    float tempX = x;
                    float tempY = y;
                    float rotationInRads = getRotation() * MathUtils.degreesToRadians;
                    x = tempX * (float) Math.cos(rotationInRads) - tempY * (float) Math.sin(rotationInRads);
                    y = tempY * (float) Math.cos(rotationInRads) + tempX * (float) Math.sin(rotationInRads);
                }
                x += getX() + getOriginX();
                y += getY() + getOriginY();
                fullVerts[idx++] = x;
                fullVerts[idx++] = y;

                fullVerts[idx++] = color.toFloatBits();

                float inGridX = verts[j] - offsettedCol * gridWidth;
                float inGridY = verts[j + 1] - offsettedRow * gridHeight;
                float u = inGridX / gridWidth;
                float v = inGridY / gridHeight;
                if (u > 1.0f) u = 1.0f;
                if (v > 1.0f) v = 1.0f;
                if (u < 0.0f) u = 0.0f;
                if (v < 0.0f) v = 0.0f;
                // (col & 1 == 0) == true : col is even
                if (wrapTypeX == WrapType.REPEAT_MIRRORED & (col & 1) != 0) u = 1 - u;
                if (wrapTypeY == WrapType.REPEAT_MIRRORED & (row & 1) == 0) v = 1 - v;

                if (textureRegion != null) {
                    u = textureRegion.getU() + (textureRegion.getU2() - textureRegion.getU()) * u;
                    v = textureRegion.getV() + (textureRegion.getV2() - textureRegion.getV()) * v;
                } else {
                    u = whiteTextureRegion.getU() + (whiteTextureRegion.getU2() - whiteTextureRegion.getU()) * u;
                    v = whiteTextureRegion.getV() + (whiteTextureRegion.getV2() - whiteTextureRegion.getV()) * v;
                }
                fullVerts[idx++] = u;
                fullVerts[idx++] = v;
            }
            vertices.add(fullVerts);
        }

        this.textureDebugX = (buildOffset.x + textureOffset.x) * getScaleX();
        this.textureDebugY = (buildOffset.y + textureOffset.y) * getScaleY();
        if (getRotation() != 0) {
            float tempX = this.textureDebugX;
            float tempY = this.textureDebugY;
            float rotationInRads = getRotation() * MathUtils.degreesToRadians;
            this.textureDebugX = tempX * (float) Math.cos(rotationInRads) - tempY * (float) Math.sin(rotationInRads);
            this.textureDebugY = tempY * (float) Math.cos(rotationInRads) + tempX * (float) Math.sin(rotationInRads);
        }
        this.textureDebugX += getX();
        this.textureDebugY += getY();

        this.boundingRect = this.polygon.getBoundingRectangle();

        dirtyAttributes = false;
    }

    /**
     * This is a garbage, due to Intersector returning values slightly different then the grid values
     * Snapping exactly to grid is important, so that during bulidVertices method, it can be figured out
     * if points are on the wall of it's own grid box or not, to set u/v properly.
     * Any other implementations are welcome
     */
    private float[] snapToGrid(float[] vertices, int row, int col) {
        float[] resultVerts = vertices.clone();
        for (int i = 0; i < resultVerts.length; i += 2) {
            float inGridX = resultVerts[i] - col * gridWidth;
            float inGridY = resultVerts[i + 1] - row * gridHeight;
            float inGridXFraction = inGridX / gridWidth;
            float inGridYFraction = inGridY / gridHeight;
            if (inGridXFraction != 1 & inGridXFraction > 0.9999f) {
                resultVerts[i] = (col + 1) * gridWidth;
            } else if (inGridXFraction != 0 & inGridXFraction < 0.0001f) {
                resultVerts[i] = col * gridWidth;
            }
            if (inGridYFraction != 1 & inGridYFraction > 0.9999f) {
                resultVerts[i + 1] = (row + 1) * gridHeight;
            } else if (inGridYFraction != 0 & inGridYFraction < 0.0001f) {
                resultVerts[i + 1] = row * gridHeight;
            }
        }

        return resultVerts;
    }

    /**
     * Offsets polygon to 0 - textureOffset coordinate for ease of calculations, later this is put back on final render
     *
     * @param vertices vertices to offset
     * @return offsetted vertices
     */
    private float[] offset(float[] vertices) {
        float[] result = vertices.clone();

        Polygon polygon = new Polygon(result);
        Rectangle bounds = polygon.getBoundingRectangle();

        buildOffset.x = bounds.x;
        buildOffset.y = bounds.y;

        for (int i = 0; i < result.length; i += 2) {
            result[i] -= (buildOffset.x + textureOffset.x);
            result[i + 1] -= (buildOffset.y + textureOffset.y);
        }

        gridOffset.x = (int) Math.floor(-(textureOffset.x / gridWidth));
        gridOffset.y = (int) Math.floor(-(textureOffset.y / gridHeight));

        return result;
    }

    public void draw(PolygonSpriteBatch batch) {
        if (dirtyGrid || parts.size == 0) {
            prepareVertices();
        }
        if (dirtyAttributes || vertices.size == 0) {
            buildVertices();
        }

        Texture textureToDraw;
        if (textureRegion != null) {
            textureToDraw = textureRegion.getTexture();
        } else {
            textureToDraw = whiteTextureRegion.getTexture();
        }

        for (int i = 0; i < vertices.size; i++) {
            batch.draw(textureToDraw, vertices.get(i), 0, vertices.get(i).length, indices.get(i), 0, indices.get(i).length);
        }
    }

    public void drawDebug(ShapeRenderer shapes, Color color) {
        if (dirtyGrid) {
            prepareVertices();
        }
        if (dirtyAttributes) {
            buildVertices();
        }

        // draw grid
        for (int i = 0; i < vertices.size; i++) {

            // draw vertices in grid
            shapes.setColor(color);
            float[] curVerts = vertices.get(i);
            short[] curIndices = this.indices.get(i);
            for (int j = 0; j < curIndices.length; j += 3) {
                float x1 = curVerts[curIndices[j] * 5];
                float y1 = curVerts[curIndices[j] * 5 + 1];
                float x2 = curVerts[curIndices[j + 1] * 5];
                float y2 = curVerts[curIndices[j + 1] * 5 + 1];
                float x3 = curVerts[curIndices[j + 2] * 5];
                float y3 = curVerts[curIndices[j + 2] * 5 + 1];
                shapes.triangle(x1, y1, x2, y2, x3, y3);
            }
        }

        //draw cross on grid 0/0
        shapes.setColor(Color.RED);
        shapes.line(textureDebugX - 1, textureDebugY - 1,
                textureDebugX + 1, textureDebugY + 1);
        shapes.line(textureDebugX - 1, textureDebugY + 1,
                textureDebugX + 1, textureDebugY - 1);
    }

    @Override
    public void dispose() {
        whiteTextureRegion.getTexture().dispose();
        whiteTextureRegion = null;
        if (textureRegion != null) {
            textureRegion.getTexture().dispose();
            textureRegion = null;
        }
        polygon = null;
        boundingRect = null;
        parts.clear();
        parts = null;
        vertices.clear();
        vertices = null;
        indices.clear();
        indices = null;
        buildOffset = null;
        gridOffset = null;
        textureOffset = null;
    }

    /**
     * Sets the outline vertices of the polygon
     *
     * @param vertices - vertices of polygon relative to the origin
     */
    public void setVertices(float[] vertices) {
        if (vertices == null) {
            Polygon tempPolygon = new Polygon();
            tempPolygon.setPosition(getX(), getY());
            tempPolygon.setOrigin(getOriginX(), getOriginY());
            tempPolygon.setRotation(getRotation());
            tempPolygon.setScale(getScaleX(), getScaleY());
            polygon = tempPolygon;
        } else {
            polygon.setVertices(vertices);
        }
        dirtyGrid = true;
    }

    /**
     * Sets the texture region, the size of repeating grid is equal to region size
     *
     * @param textureRegion - texture region mapped on the polygon
     * @param wrapTypeX     - WrapType how the texture region is drawn along the X-Axis
     * @param wrapTypeY     - WrapType how the texture region is drawn along the Y-Axis
     */
    public void setTextureRegion(TextureRegion textureRegion, WrapType wrapTypeX, WrapType wrapTypeY) {
        setTextureRegion(textureRegion);
        setWrapTypeX(wrapTypeX);
        setWrapTypeY(wrapTypeY);
    }

    /**
     * Sets the texture region, the size of repeating grid is equal to region size
     *
     * @param textureRegion - texture region mapped on the polygon
     * @param textureWidth  - width of the repeating region
     * @param textureHeight - height of the repeating region
     */
    public void setTextureRegion(TextureRegion textureRegion, float textureWidth, float textureHeight) {
        setTextureRegion(textureRegion);
        setTextureSize(textureWidth, textureHeight);
    }

    /**
     * Sets the texture region, the size of repeating grid is equal to region size
     *
     * @param textureRegion - texture region mapped on the polygon
     * @param textureWidth  - width of the repeating region
     * @param textureHeight - height of the repeating region
     * @param wrapTypeX     - WrapType how the texture region is drawn along the X-Axis
     * @param wrapTypeY     - WrapType how the texture region is drawn along the Y-Axis
     */
    public void setTextureRegion(TextureRegion textureRegion, float textureWidth, float textureHeight, WrapType wrapTypeX, WrapType wrapTypeY) {
        setTextureRegion(textureRegion);
        setTextureSize(textureWidth, textureHeight);
        setWrapTypeX(wrapTypeX);
        setWrapTypeY(wrapTypeY);
    }

    /**
     * Sets the texture region, the size of repeating grid is equal to region size if not set already
     *
     * @param textureRegion - texture region mapped on the polygon
     */
    public void setTextureRegion(TextureRegion textureRegion) {
        this.textureRegion = textureRegion;
        if (this.textureWidth == 0) this.textureWidth = textureRegion.getRegionWidth();
        if (this.textureHeight == 0) this.textureHeight = textureRegion.getRegionHeight();
        dirtyGrid = true;
    }

    /**
     * Sets the position of the texture where 0 is the bottom left corner of the bounding rectangle
     */
    public void setTextureOffset(float x, float y) {
        this.textureOffset.set(x, y);
        dirtyGrid = true;
    }

    /**
     * Sets the to be drawn width and height of the texture
     */
    public void setTextureSize(float width, float height) {
        this.textureWidth = width;
        this.textureHeight = height;
        dirtyGrid = true;
    }

    /**
     * Sets the sprite's position in the world
     */
    public void setPosition(float x, float y) {
        polygon.setPosition(x, y);
        dirtyAttributes = true;
    }

    /**
     * Sets the sprite's x position in the world
     */
    public void setX(float x) {
        polygon.setPosition(x, getY());
        dirtyAttributes = true;
    }

    /**
     * Sets the sprite's y position in the world
     */
    public void setY(float y) {
        polygon.setPosition(getX(), y);
        dirtyAttributes = true;
    }

    /**
     * Sets the sprite's position in the world
     */
    public void translate(float x, float y) {
        polygon.setPosition(getX() + x, getY() + y);
        dirtyAttributes = true;
    }

    /**
     * Sets the origin in relation to the sprite's position for scaling and rotation.
     */
    public void setOrigin(float x, float y) {
        polygon.setOrigin(x, y);
        dirtyAttributes = true;
    }

    /**
     * Sets the origin x in relation to the sprite's position for scaling and rotation.
     */
    public void setOriginX(float x) {
        setOrigin(x, getOriginY());
    }

    /**
     * Sets the origin y in relation to the sprite's position for scaling and rotation.
     */
    public void setOriginY(float y) {
        setOrigin(getOriginX(), y);
    }

    /**
     * Sets the scale along both axises where 1 = normal Size
     */
    public void setScale(float scaleX, float scaleY) {
        polygon.setScale(scaleX, scaleY);
        dirtyAttributes = true;
    }

    /**
     * Sets the scale along the x axis where 1 = normal Size
     */
    public void setScaleX(float scaleX) {
        polygon.setScale(scaleX, getScaleY());
        dirtyAttributes = true;
    }

    /**
     * Sets the scale along the y axis where 1 = normal Size
     */
    public void setScaleY(float scaleY) {
        polygon.setScale(getScaleX(), scaleY);
        dirtyAttributes = true;
    }

    /**
     * Adds the specified scale to the current scale.
     */
    public void scaleBy(float scaleXY) {
        polygon.scale(scaleXY);
        dirtyAttributes = true;
    }

    /**
     * Adds the specified scale to the current scale.
     */
    public void scaleBy(float scaleX, float scaleY) {
        polygon.setScale(getScaleX() + scaleX, getScaleY() + scaleY);
        dirtyAttributes = true;
    }

    public void setRotation(float degrees) {
        polygon.setRotation(degrees);
        dirtyAttributes = true;
    }

    /**
     * Adds the specified rotation to the current rotation.
     */
    public void rotateBy(float amountInDegrees) {
        polygon.rotate(amountInDegrees);
        dirtyAttributes = true;
    }

    /**
     * Sets the type how the texture region is drawn along the X-Axis
     *
     * @param wrapType - a type of WrapType
     */
    public void setWrapTypeX(WrapType wrapType) {
        this.wrapTypeX = wrapType;
        dirtyGrid = true;
    }

    /**
     * Sets the type how the texture region is drawn along the Y-Axis
     *
     * @param wrapType - a type of WrapType
     */
    public void setWrapTypeY(WrapType wrapType) {
        this.wrapTypeY = wrapType;
        dirtyGrid = true;
    }

    /**
     * @param color - Tint color to be applied to entire polygon
     */
    public void setColor(Color color) {
        this.color.set(color);
        dirtyAttributes = true;
    }

    public WrapType getWrapTypeX() {
        return wrapTypeX;
    }

    public WrapType getWrapTypeY() {
        return wrapTypeY;
    }

    public TextureRegion getTextureRegion() {
        return textureRegion;
    }

    public float getTextureOffsetX() {
        return textureOffset.x;
    }

    public float getTextureOffsetY() {
        return textureOffset.y;
    }

    public float getTextureWidth() {
        return textureWidth;
    }

    public float getTextureHeight() {
        return textureHeight;
    }

    public float getX() {
        return polygon.getX();
    }

    public float getY() {
        return polygon.getY();
    }

    public float getOriginX() {
        return polygon.getOriginX();
    }

    public float getOriginY() {
        return polygon.getOriginY();
    }

    public float getScaleX() {
        return polygon.getScaleX();
    }

    public float getScaleY() {
        return polygon.getScaleY();
    }

    public float getRotation() {
        return polygon.getRotation();
    }

    public Color getColor() {
        return color;
    }

    /**
     * Returns the packed vertices, colors, and texture coordinates for this sprite.
     */
    public Array<float[]> getVertices() {
        return vertices;
    }

    public float[] getOriginalVertices() {
        return polygon.getVertices().clone();
    }

    public float[] getTransformedVertices() {
        return polygon.getTransformedVertices().clone();
    }

    public Polygon getPolygon() {
        Polygon tempPolygon = new Polygon();
        if (getOriginalVertices().length != 0) tempPolygon.setVertices(getOriginalVertices());
        tempPolygon.setPosition(getX(), getY());
        tempPolygon.setOrigin(getOriginX(), getOriginY());
        tempPolygon.setRotation(getRotation());
        tempPolygon.setScale(getScaleX(), getScaleY());
        return tempPolygon;
    }

    public Rectangle getBoundingRectangle() {
        return this.boundingRect;
    }
}
`

**Comment by jenskofodhansen** [comment]
@Kablion That is definatly usefull for me 👍 Very well featured :)

**Pull request merged**
