### PR TITLE
Remove commented code

### PR DESCRIPTION
**Pull request by BobDorland**
This pull request removes commented code from three files in the `gdx/src/com/badlogic` folder, in order to make these files more neat.

### CODE REVIEW

**Comment by NathanSweet** [comment]
FWIW, the commented code removed from Array.java prints about concurrent usage, which is occasionally useful if not using `Collections.allocateIterators = true`.

**Comment by BobDorland** [comment]
> FWIW, the commented code removed from Array.java prints where the iterator is acquired, which is occasionally useful if not using `Collections.allocateIterators = true` and having a crash from modifications while iterating.

I see, sorry. I didn't realize these lines were still used for debugging. Would you prefer to have it in? I can add it back in a separate PR.

**Comment by MrStahlfelge** [comment]
They are of no real use if they are commented and not usable via a debug flag.

**Comment by NathanSweet** [comment]
I don't mind much that the comments are gone, no need to put them back.

They are certainly of use when running from source and the functionality is needed. Overhead of a debug flag is not wanted.

**Pull request merged**
