### PR TITLE
Unit testing on travis

### PR DESCRIPTION
**Pull request by SimonIT**
You can see [here](https://travis-ci.com/SimonIT/libgdx/builds/105577057/) that the configuration works. The tests run via `gradlew test`

### CODE REVIEW

**Comment by intrigus** [comment]
I might have missed it, but where exactly are unit tests executed? I don't see any.
Otherwise +1.
The more tests, the better.

**Comment by SimonIT** [comment]
[This](https://travis-ci.com/SimonIT/libgdx/jobs/187284558#L1299) is the line where tests from `gdx/test` are executed. It's a bit hidden.

**Comment by mgsx-dev** [comment]
it would be nice to have test resutls to be sure tests are really executed : see https://stackoverflow.com/a/20359498/5198450

**Comment by NathanSweet** [comment]
Is this good to be merged, or is something else needed? @mgsx-dev

**Comment by SimonIT** [comment]
@mgsx-dev @NathanSweet done

**Pull request merged**
