### PR TITLE
Allow custom window icons in Lwjgl3

### PR DESCRIPTION
**Pull request by cypherdare**
You can set up your icons as image files and pass them into the app configuration. It takes image filepaths because Pixmaps are difficult to load from files before LibGDX is initialized.

You can also pass Pixmaps to an existing Lwjgl3Window to change the icon dynamically.

And I also added a method to change the title of an existing Lwjgl3Window.

Finally, I fixed a GLFW window size limits bug with a work-around, since I was in the area.

### CODE REVIEW

**Comment by viniciuspjardim** [comment]
I would like to have this feature in Lwjgl3. I need to use Lwjgl3 because it has the controller connect / disconnect events. If I could also use the window icon, would be very nice.

**Comment by Quexten** [comment]
I'd also like this to be pulled.

**Comment by CreamyCookie** [comment]
I'd also like to get this fixed, but the [GLFW bug](https://github.com/glfw/glfw/pull/805) is fixed, so that part should be removed from the pull request.

**Comment by cypherdare** [comment]
@CreamyCookie, It's fixed, but given Lwjgl's slow release schedule, I could see it taking more than a year to trickle down to an Lwjgl release build. I'd vote for keeping the hack until that happens, so this non-obvious bug doesn't waste anyone's time.

**Comment by cypherdare** [comment]
@code-disaster, Your consolidation makes very good sense. I merged it in. I also added a convenience method to the config that assumes Internal files, since that's almost always going to be the case. There are similar convenience constructors for may core classes, so I think it makes sense here.

The GLFW size limits bug fix didn't make it into Lwjgl 3.1, so I think the workaround should stay.

**Comment by cypherdare** [comment]
@code-disaster 
OK, turns out the GLFW update did make it in, so I removed the workaround. Window size limits seem to be entirely non-functional now in Lwjgl 3.1.0, but that's a separate issue from this PR.

**Comment by cypherdare** [comment]
I realized there was a ridiculous amount of copy-pasted code from Lwjgl3WindowConfiguration in Lwjgl3ApplicationConfiguration, so I fixed it.

**Comment by code-disaster** [comment]
I probably would have done the duplicate code removal in a separate PR, but overall it looks fine to me now.

**Comment by cypherdare** [comment]
Probably should have. I separated them.

**Pull request merged**
