### PR TITLE
boxed integer map / helper cleanup

### PR DESCRIPTION
**Pull request by stefanhaustein**
Change gl handle to webgl object hash maps to an efficient jso int map (based on sparse js arrays) tailored towards this purpose. Remove unneeded helpers

Any testing recommendations / pointers (on linux)?

### CODE REVIEW

**Comment by badlogic** [comment]
Looks good to me. Try Super Jumper or any of the other demos. BulletTestCollection is also a nice test.

**Comment by stefanhaustein** [comment]
I was hoping for something I could paste into the command line that lets me run the html tests via gradle without choking on some android gradle version thing or ios dependencies that do not seem to be available on linux?

**Comment by Tom-Ski** [comment]
Remove the Moe tests from the build. Remove it from the settings.gradle file, and in the main build.gradle remove the MOE plugin and project definition.

**Comment by stefanhaustein** [comment]
@Tom-Ski Thanks a lot! I had missed settings.gradle. 

gradle test runs successfully now.

**Comment by stefanhaustein** [comment]
ping?

**Comment by Tom-Ski** [comment]
Has conflicts now, If you can fix those up I can test and pull.

**Comment by stefanhaustein** [comment]
Sorry had some trouble with git, should be finally properly merged now O:)

**Comment by Tom-Ski** [comment]
It can be merged but it contains commits that it shouldn't. Could you have another look so this can be reviewed?

**Comment by stefanhaustein** [comment]
Sorry had messed up my repro, will create a new PR

**Pull request closed without merging**
