### PR TITLE
Add polygon intersection method.

### PR DESCRIPTION
**Pull request by AldousP**
As mentioned in issue #3632 this adds a new Intersector method to determine the overlapping area between two polygons.

### CODE REVIEW

**Comment by badlogic** [comment]
Nice, thanks! Do we have a CLA from you? If not, please see https://github.com/libgdx/libgdx/wiki/Contributing

**Comment by intrigus** [comment]
I absolutely don't like this method, it creates so much garbage. I'm pretty sure that it could be so programmed that it produces less garbage.

**Comment by MobiDevelop** [comment]
I was also just going to make a comment on the amount of garbage this produces. Three ArrayLists plus a Vector2 for each of the polygons vertices seems a little much.

**Comment by davebaol** [comment]
Yeah couldn't agree more.

**Comment by xoppa** [comment]
Ow indeed, @AldousP could you please fix this (and perhaps add a test as well)?

**Comment by AldousP** [comment]
Yeah should have one in the next little bit.

**Comment by AldousP** [comment]
@MobiDevelop New pull has been opened at #3770

**Pull request merged**
