### PR TITLE
Added support for name provider in SelectBox and List

### PR DESCRIPTION
**Pull request by kotcrab**
Current implementation of SelectBox and List is limited and always uses `toString()` method to show item as text. I added way to set custom name provider for SelectBox/List. This way it's possible to customize what text will be shown for given item (or just call different method than `toString()`). 
If provider is not set it defaults to `toString()` so it doesn't break old stuff.

### CODE REVIEW

**Comment by NathanSweet** [comment]
This is a pretty heavy solution for such a simple problem. I'd prefer just have a protected SelectBox#toString(Object) that can be overridden to customize the display.

**Comment by kotcrab** [comment]
That would only allow to customize text in selectbox itself, not in it's dropdown list. Notice that in `SelectBox#setItemNameProvider` I also must call `selectBoxList.list.setItemNameProvider`.

**Comment by kotcrab** [comment]
Updated, if that change is OK tell me and I'll rebase.

**Comment by NathanSweet** [comment]
Ah oops, merged before you rebased. Ah well.

Thanks!

**Pull request merged**
