### PR TITLE
Add action6

### PR DESCRIPTION
**Pull request by aliasifk**

### CODE REVIEW

**Review by Frosty-J — CHANGES_REQUESTED** [review]
Wouldn't [`ParallelAction`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/actions/ParallelAction.java) and [`SequenceAction`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/actions/SequenceAction.java) also need updating? This is a silly pull request anyway.

**Comment by aliasifk** [comment]
Its very beneficial as the (Object..) method creates garbage

**Comment by Frosty-J** [comment]
It's not the only thing around here that creates garbage.

**Comment by MobiDevelop** [comment]
I personally feel like 5 actions before varargs is sufficient. Otherwise, why stop at 6? Why not 10? It's easy enough to make your own utility class that takes as many args as you like and makes an action.

**Pull request closed without merging**
