### PR TITLE
Adding ability to set line height for BitmapFont

### PR DESCRIPTION
**Pull request by rinold**
While using BitmapFont I've faced issue that sometimes fonts have too big line height, which makes drawn multiline text a bit ugly. #setLineHeight method gives an easy way to change it, e.g. make smaller, to have a more pretty text drawing result. Thought that also might be useful to someone facing the same issue.

### CODE REVIEW

**Comment by mk1x86** [comment]
Although I appreciate the commit, why don't you just set the line height in the fnt file? Seems like a rather straightforward solution.

**Comment by NathanSweet** [comment]
Agreed, I usually change it in the fnt file. I suppose this method doesn't hurt, but can you move it to `BitmapFontData`?

**Comment by rinold** [comment]
@mk1x86, @NathanSweet 
Actually I use the gdx-freetype to generate BitmapFonts at runtime. As for me it's quite hard to correctly edit ttf/otf files, they look quite complicated for me as I'm kind of a newbie with fonts. Also from one font file I create several bitmap fonts with different line height.

@NathanSweet,
Regarding moving it to BitmapFontData, will it be really better? I mean i can do it without this commit by accessing myFont.getData().lineHeight/down, but resulting code looks a bit weird. I'll update the PR, but I also really want to understand the reasons of moving to BitmapFontData.

**Comment by NathanSweet** [comment]
The method only affects BitmapFontData. The question is why have a method on BitmapFont that only affects BitmapFontData?

**Comment by rinold** [comment]
@NathanSweet, all genius is simple, thank you for answer :)
I'll make needed changes in some time.

**Pull request closed without merging**
