### PR TITLE
Fix missing gwt.xml for Box2D on gwt

### LINKED ISSUE #6137: A Box2D dependent GWT module fails to build
#### Issue details

After upgrading my projects to LibGDX 1.9.11 (from 1.9.10) the GWT modules fail to build if they include Box2D dependencies.

This is the error message from `./gradlew html:superDev`

```
Loading inherited module 'com.mygdx.game.GdxDefinitionSuperdev'
   Loading inherited module 'com.badlogic.gdx.physics.box2d.box2d-gwt'
      [ERROR] Unable to find 'com/badlogic/gdx/physics/box2d/box2d-gwt.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

Apparently the `box2d-gwt.gwt.xml` file is missing in [`com.badlogicgames.gdx:gdx-box2d-gwt:1.9.11:sources`](https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-gwt/1.9.11/gdx-box2d-gwt-1.9.11-sources.jar)

This issue is most likely a regression from #5956

#### Reproduction steps/code
1. Generate a clean project using the setup app with HTML backend and Box2D dependency.
2. Issue `./gradlew html:superDev`

#### Version of LibGDX and/or relevant dependencies
- 1.9.11
- Box2D
- GWT

#### Please select the affected platforms
- [x] HTML/GWT
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] Windows
- [ ] Linux
- [ ] MacOS

### PR DESCRIPTION
**Pull request by SimonIT**
fixes #6137

### CODE REVIEW

**Comment by MacCode7110** [comment]
I am new to LibGDX, how do I apply this fix to a project?

**Comment by metaphore** [comment]
@MacCode7110 the file should be inside of the `gdx-box2d-gwt-1.9.11-sources.jar`. Until the patched artifact is available on Maven, the only option is to put the file into the archive manually and use a local JAR instead of the Maven dependency.

1. Extract the contents of this ZIP archive to the GWT module's _"libs"_ dir of your project  
[gdx-box2d-gwt-patched.zip](https://github.com/libgdx/libgdx/files/5127425/gdx-box2d-gwt-patched.zip)
2. In the respective `build.gradle` use this file instead of the Maven dependency.
```
//    A broken one to remove/comment
//    implementation "com.badlogicgames.gdx:gdx-box2d-gwt:$1.9.11:sources" 

//    The local patched JAR
      implementation files('libs/gdx-box2d-gwt-1.9.11-sources.jar')
```

**Comment by BeppeMarnell** [comment]
> @MacCode7110 the file should be inside of the `gdx-box2d-gwt-1.9.11-sources.jar`. Until the patched artifact is available on Maven, the only option is to put the file into the archive manually and use a local JAR instead of the Maven dependency.
> 
> 1. Extract the contents of this ZIP archive to the GWT module's _"libs"_ dir of your project
>    [gdx-box2d-gwt-patched.zip](https://github.com/libgdx/libgdx/files/5127425/gdx-box2d-gwt-patched.zip)
> 2. In the respective `build.gradle` use the patched file instead of the Maven dependency.
> 
> ```
> //    A broken one to remove/comment
> //    implementation "com.badlogicgames.gdx:gdx-box2d-gwt:$1.9.11:sources" 
> 
> //    The local patched JAR
>       implementation files('libs/gdx-box2d-gwt-1.9.11-sources.jar')
> ```

I also have this same problem and it's really annoying because I spent a lot of time trying to fix it. I am using IntelliJ, after downloading and importing your ".jar" as a java project library, the following error keeps appearing no matter what module I choose. Therefore, is impossible to deploy in html.
Screenshot 2020-08-31 at 17 45 20

**Comment by Lovegiver** [comment]
Hi everyone,
I'm new to LibGdx, Gradle & IntelliJ. I'm really doing my best to fix the problem.

Like u said, I've created a '**libs**' folder in the **HTML** part of the project.

In the project 'build.gradle' file, I've done so :
```
//api "com.badlogicgames.gdx:gdx-box2d-gwt:$gdxVersion:sources"
implementation files('libs/gdx-box2d-gwt-1.9.11-sources.jar')
```

But what change should I do in the **GdxDefinition.gwt.xml** because this line doesn't seem to work too :
`<inherits name='com.badlogic.gdx.physics.box2d.box2d-gwt' />`

When compiling I still have an error :
```
Compiling module com.citizenweb.games.hr.GdxDefinition
   Tracing compile failure path for type 'com.badlogic.gdx.physics.box2d.joints.MotorJoint'
      [ERROR] Errors in 'jar:file:/C:/Users/Loveg/IdeaProjects/HR_Game/html/libs/gdx-box2d-gwt-1.9.11-sources.jar!/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/joints/MotorJoint.java'
```
[...]

I'm quite lost at this point.
[Box2d.txt](https://github.com/libgdx/libgdx/files/5404914/Box2d.txt)

**Pull request merged**
