### PR TITLE
Remove unnecessary normalization

### PR DESCRIPTION
**Pull request by yuripourre**
This PR will not break anything, it just removed unnecessary normalizations to reduce the number of operations (and errors) when lookAt method is called multiple times. It will avoid 1 square root calculation (2 if you call the update method).

This is an attempt to fix: #5159

### How to test
A good way to test it is to run the [SimpleDecalTest](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/SimpleDecalTest.java) (or any other test that calls lookAt) and check if the behavior is the same.

### Why it works?
The first line will produce a non-unit vector but the second line will calculate the perpendicular vector and normalize it. (as @obigu explained, the length of the vector will not affect the cross product).

```
tmpVec.set(direction).crs(up);
up.set(tmpVec).crs(direction).nor();
```
If you are not convinced yet, the same thing is done at: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Matrix4.java#L1522

### CODE REVIEW

**Comment by intrigus** [comment]
Why is this unnecessary?

**Comment by obigu** [comment]
@intrigus On a cross product, the vectors magnitudes don't affect the direction of the resulting vector. I think there's no need to normalize the vector resulting from the first cross product because we only use it to find a perpendicular vector to it (and to `direction`).

**Comment by yuripourre** [comment]
@obigu that's right, unless I can't see the real reason for that, the first normalization is unnecessary.

@intrigus thank you for asking, I updated the description a bit.

**Comment by yuripourre** [comment]
@noblemaster, @mgsx-dev Can you test it, please?

**Comment by yuripourre** [comment]
@noblemaster Thanks!

**Pull request merged**
