### PR TITLE
Implemented layer offsets for tiled maps

### PR DESCRIPTION
**Pull request by piotr-j**
Tests included. See #4047

### CODE REVIEW

**Comment by MobiDevelop** [comment]
Looks ok to me.

**Comment by badlogic** [comment]
Thanks!

**Comment by SuckyNoob** [comment]
Is this for all Layers? Even in Isometric Maps? Because I can't get my layers to render properly in my isometric Tiled TMX map. It sets all of them at the ground level.

**Comment by piotr-j** [comment]
The tests include isometric and isometric staggered maps. And they looked fine last time ive checked.  That was months ago, its possible that stuff changed in tiled or that ive missed some combination of parameters.

**Comment by SuckyNoob** [comment]
? I apologize, I am new to using github. What "tests"? are there files or code where I can see this?

**Comment by piotr-j** [comment]
They are in the changed files.
https://github.com/piotr-j/libgdx/blob/f35c50b5f1d7967548dd30d078dfb326c2b9f6e9/tests/gdx-tests/src/com/badlogic/gdx/tests/TiledMapLayerOffsetTest.java

**Comment by SuckyNoob** [comment]
I will try them out! I've been searching everywhere for months trying to get this all to work for different libraries etc.

**Comment by SuckyNoob** [comment]
Perhaps just one other question.

Can you point me in the right direction to see how I can edit that file. I can't access the External libraries, or the files, like the Map Loader, to change them.

How do I use your tests in my project exactly? If you have the time to explain

**Comment by piotr-j** [comment]
You clone the forked repo and run the tests like other tests https://github.com/libgdx/libgdx/wiki/Running-Tests

**Comment by SuckyNoob** [comment]
Ah well, this is beyond my skill level, I can't figure out how to work with libraries in this IntelliJ, this gradle stuff is confusing as hell compared to Visual Studio, not sure how to get the Libraries in manually. And the folder my project points to that says it's holding the library for tileLayerLoading and such, is just has a jar file called "gdx-1.9.6-sources.jar" that does nothing when I try and open it.

**Pull request merged**
