### PR TITLE
Adding link to JavaDocs for offline use

### PR DESCRIPTION
**Pull request by epochofentropy**
This link wasn't available anyplace, and is useful for those that can't be online all the time.

### CODE REVIEW

**Comment by nooone** [comment]
The links works.

However 3 commits for this are a bit much. Usually, before you want to start a new PR, switch to your masterbranch, update that and then create a new branch. Then make the change and start the PR from this branch. This will avoid additional commits.

**Comment by epochofentropy** [comment]
I apologize, still getting the hang of Github. I didn't realize that updates to my branch from the remote master were part of the pull request.

Just to be clear: For every change intended to be a PR, a new branch needs to be created?

**Comment by nooone** [comment]
Yes, it helps to seperate the changes you want to make with the PR from all other ones.

It might even happen that you want to make two PRs at once. In this case doing both via master will be pretty difficult...

**Comment by epochofentropy** [comment]
Gotcha. Thank you for the advice and input.

If it's easier, since this is just a simple change, you may ignore this PR and manually copy/paste the file. I'm not so concerned about attribution, just that this obscure link is documented somewhere.

**Comment by MobiDevelop** [comment]
I'm not sure we should link to things in the Jenkins workspace.

**Comment by epochofentropy** [comment]
MobiDevelop,

Fair enough. I'll look into alternatives.

**Comment by MobiDevelop** [comment]
I'm going to go ahead and close this.

**Pull request closed without merging**
