### PR TITLE
ETC1Data IO fix and update

### PR DESCRIPTION
**Pull request by JFixby**
In this PR:

Commit 1:
 - matryoshka ```new DataOutputStream(new GZIPOutputStream(file.write(false)));``` was refactored to allow closing ```gzipStream``` and ```dataStream```

- new method ```write(OutputStream outputStream)``` added

- output ```fileStream``` properly closed to avoid locking output file.

Commit 2:
 - another matryoshka ```new DataInputStream(new BufferedInputStream(new GZIPInputStream(pkmFile.read())));``` refactored for the same reasons

- new method ```static ETC1Data.read(inputStream)``` introduced to replace unsafe constructor

- input ```fileStream``` properly closed to avoid locking input file.

Commit 3:
- class ```final``` modifier removed to allow class extension for custom implementations.

### CODE REVIEW

**Comment by Tom-Ski** [comment]
Please squash into one commit.

**Comment by JFixby** [comment]
@Tom-Ski something like this: https://github.com/libgdx/libgdx/pull/3925 ?

**Comment by Tom-Ski** [comment]
You have committed the merge, which isn't ideal.  Could you also close PRs that are no longer in use, it is very confusing to have multiple issues/PRs open for the same problem/issue.

**Comment by JFixby** [comment]
I need some help with that. How can I remove/avoid the merge commit from appearing?

**Comment by JFixby** [comment]
@Tom-Ski https://github.com/libgdx/libgdx/pull/3926

**Pull request closed without merging**
