### PR TITLE
Remove need of Vector2 in World#rayCast()

### PR DESCRIPTION
**Pull request by rcdvl**

### CODE REVIEW

**Comment by MobiDevelop** [comment]
Please also add this to the GWT emulation of World.

**Comment by rcdvl** [comment]
Done :)

**Comment by intrigus** [comment]
Could you please squash your commits ?

**Comment by rcdvl** [comment]
@intrigus like this? Never worked with squashed commits in github before

**Comment by intrigus** [comment]
Yes, exactly like this :)

**Comment by Tom-Ski** [comment]
Great, thanks!

**Pull request merged**
