### PR TITLE
modify GestureDetector

### PR DESCRIPTION
**Pull request by McoyJiang**
fix bug about long press not call under some circumstances

### CODE REVIEW

**Comment by Darkyenus** [comment]
I am not sure what the issue is, but creating a new `Thread` on each click is probably not the right solution. When is the long press not called - what does this fix?

**Comment by Tom-Ski** [comment]
Agreed. What is the issue? How can we reproduce?

**Comment by McoyJiang** [comment]
### under this circumstance, the longPress method won't be call :
1 if there are two AndroidApplication classes, and within each of them there is a specific AndroidApplicationAdatper.  and make a event to jump from one Adapter to Another Adapter
2 in each AndroidApplication Adapter initialize the absolutely same ActorGestureListener, and addListener to Actor
3 the second ActorGestureListener's longPress won't be called

example link:
[https://github.com/McoyJiang/GestureDetectorTest](url)

**Comment by Darkyenus** [comment]
libGDX is not designed to run multiple instances of itself on one VM. I'm surprised that this was the only thing that broke...

**Comment by McoyJiang** [comment]
since Android can show many activities, there must be many occasions that we will use multiple Stage or ApplicationAdapter.  Then how could we solve this problem ?

**Comment by Darkyenus** [comment]
This is exactly what [Game](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/Game.java) and [Screen(Adapter)](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/ScreenAdapter.java) is for :)

**Comment by McoyJiang** [comment]
so in Android System, if we want to use Libgdx, then there must be only one Activity ?

**Comment by Darkyenus** [comment]
Not necessarily one Activity, just only one libGDX activity. Making your whole game in a single activity is also better for portability - other platforms don't have any concept of Android Activities. If you structure your game correctly, you can even develop most of your game on desktop, which is arguably faster/easier.

(If you want to ask more, it would be better to use [forums or IRC](https://github.com/libgdx/libgdx/wiki/Community-%26-Support) as this discussion is not a good fit for the issue tracker)

**Pull request closed without merging**
