### PR TITLE
Fix false-positive of vibration support

### PR DESCRIPTION
**Pull request by intrigus**
See https://github.com/libgdx/libgdx/pull/3428

### CODE REVIEW

**Comment by MobiDevelop** [comment]
While we are making changes, does it make sense to also check whether permission has been granted to use the vibrator?

**Comment by intrigus** [comment]
The "android.permission.VIBRATE"-permission is automatically granted if it's declared in the Manifest.xml.
Or what do you mean?
See http://developer.android.com/guide/topics/security/permissions.html#normal-dangerous and 
http://developer.android.com/guide/topics/security/normal-permissions.html.

**Comment by MobiDevelop** [comment]
And if you don't add that permission to the manifest, then you don't have permission, and you don't have vibrator support.

**Comment by intrigus** [comment]
You suggest that we check if the application has the permission?And if that's the case, vibrate?
I don't really see the advantage of permission checking.

**Comment by MobiDevelop** [comment]
I'm suggesting that reporting support for Vibrator is incorrect if you can't use it (due to not having the correct permission to do so).

**Comment by intrigus** [comment]
I don't think that we should return false, if we don't have the correct permission. 

Pseudoc
'''
if (isVibratorAvailable())
{
vibrate ()
}

**Comment by MobiDevelop** [comment]
It was just a suggestion. If you want to pick and choose which false positives you want to catch, then it is what it is.

It doesn't lead to hard to find bugs, it leads to a correct indication of whether vibrate is supported. I'll leave it to others to weigh in.

**Comment by xoppa** [comment]
I agree that the method `isPeripheralAvailable` should return whether the peripheral is available. Imo "available" means that you can actually use it. If there's no permission, then you can not use it, so i'd say it is not available. I don't see how this will lead to hard to find bugs, can you explain that @intrigus? Note that you can still call the vibrate method without checking whether it is available, if you prefer it to crash.

**Comment by intrigus** [comment]
If you always check whether isPeripheralAvailable returns true and only vibrate if it returns true you will never vibrate. 
I think it's very hard to debug this,  because you have no crash, no exceptions, nothing. And the cause is not too obvious. 

I'd say that isPeripheralAvailable should return whether the peripheral is available. Available means that the peripheral exists. 

@Tom-Ski Could you please share your opinion on this?

**Comment by MobiDevelop** [comment]
Knowing something exists does you absolutely no good if you cannot use it. It might as well not exist.

It isn't hard to debug because it isn't a bug... not vibrating when the vibrator is not available for use is the expected behavior.

**Comment by xoppa** [comment]
Ow, you mean that not having the permission is clearly a programmer error. You should never have to check at runtime whether it has the permission, because it is always granted. If you don't have the permission then that's an indication that something is wrong with the manifest xml.

There's something to say for that indeed. But then, it would also indicate that the developer didn't even test the vibrate functionality he wrote.

However, if android, for some reason, decides in the future that the user does have to explicitly grand permission to use vibrate (and the user can decide not to grand that right but still use the application). Then I don't think that simply crashing is the desired behavior. Instead, not vibrating would be better in that case.

**Comment by MobiDevelop** [comment]
Android 6.0 introduces the ability for users to grant permissions on demand.

**Comment by intrigus** [comment]
Can you also revoke normal permissions like vibration? I'm not sure because normal permissions are automatically granted.

**Comment by MobiDevelop** [comment]
I just installed the 6.0 update for my phone and it appears that vibration is not a permission you can revoke.

**Pull request merged**
